[과제번역] Part 1 6.3
javascript-tutorial/ko.javascript.info pull request #1051
Opened 2021-03-28 15:37 UTC by Star-ho

# Pull Request 체크리스트
## TODO
- [ ] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [ ] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [ ] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [ ] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [ ] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [ ] PR 하나엔 번역문 하나만 넣으셨나요?
- [ ] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

2021-04-26 11:43 UTC, Violet-Bora-Lee requested changes
앞쪽 부분만 리뷰 진행해보았습니다.

번역 모범사례와 기여 가이드를 정독해주시고, 수정 부탁드릴게요.

감사합니다.

2021-04-26 11:43 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/03-closure/1-closure-latest-changes/solution.md
> +이전 name값은 어디에도 존재하지 않습니다. 함수가 변수에 접근할 때, 외부 렉시컬 환경 또는 또 다른 외부 환경에서 name의 값을 가져옵니다.
```suggestion
이전 name값은 어디에도 저장되어있지 않습니다. 함수는 변수에 접근할 때, 현재 렉시컬 환경 또는 외부 렉시컬 환경에서 변수 값을 가져옵니다.
```

- saved를 번역해보았습니다.
- own을 외부로 번역하지 않아야할것같습니다.

2021-04-26 11:43 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/03-closure/1-closure-latest-changes/task.md
> +sayHi함수는 외부 변수 name을 사용하고 있습니다. 함수가 실행될 때 어떤 name을 사용될까요?
```suggestion
함수 sayHi는 외부 변수인 name을 사용하고 있습니다. 함수가 실행되면 어떤 name을 사용할까요?
```

https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%ED%95%A8%EC%88%98

모범사례를 참고해주세요

2021-04-26 11:43 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/03-closure/1-closure-latest-changes/task.md
> +위 상황은 프론트엔드와 백엔드 개발 시 공통적으로 나타납니다. 예를 들면 함수가 생성되고, 사용자 작업 또는 네트워크 요청 끝난 후 함수가 실행되도록 구현하는 경우입니다.
```suggestion
함수가 생성되고, 사용자 작업 또는 네트워크 요청이 끝난 후 함수를 실행해야 하는 상황은 프론트엔드, 백엔드 개발 상관없이 자주 나타납니다.
```

2021-04-26 11:43 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/03-closure/10-make-army/solution.md
> +답을 명확히 하기 위해, `makeArmy`함수 내부 동작을 확인해보자.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%89%BC%ED%91%9C%EB%A5%BC-%EB%AA%A8%EB%91%90-%EC%98%AE%EA%B8%B8-%ED%95%84%EC%9A%94%EB%8A%94-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4

모범사례 참고 부탁드릴게요

2021-04-26 11:43 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/03-closure/10-make-army/solution.md
> +1.  `shooters`라는 빈 배열을 생성한다.
- 불필요한 공백은 넣지말아주세요.
- 경어체를 유지해주세.

2021-04-26 11:43 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/03-closure/10-make-army/solution.md
> +2.  `shooters.push(function...)`를 통해 배열을 채웁니다.
불필요한 공백을 넣지말아주셍

2021-04-26 11:43 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/03-closure/10-make-army/solution.md
> +    모든 요소는 함수로 바뀌고, 아래와 같은 배열이 됩니다.
오역같은데.. 다시한번 검토 부탁드릴게요.

```suggestion
    모든 요소는 함수이기 때문에 최종 배열은 아래 같이 생겼을겁니다.
```

2021-04-26 11:43 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/03-closure/10-make-army/solution.md
> +3. 함수는 배열을 반환합니다.
```suggestion
3. 배열은 함수로부터 반환됩니다.
```
오역같은데 수정부탁드릴게요

2021-04-26 11:43 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/03-closure/10-make-army/solution.md
> +    let shooter = function() { // shooter 함수
```suggestion
    let shooter = function() { // 함수 shooter
```

2021-04-26 11:43 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/03-closure/10-make-army/solution.md
> +이후에 `army[5]()`의 호출은 배열로부터 `army[5]`요소(요소는 함수일 것이다.)를 가져와서 호출하는 것입니다.
```suggestion
이후에 `army[5]()`를 호출하면 배열에서 요소 `army[5]`(함수)를 가져와서 호출하게 됩니다.
```

2021-04-26 11:43 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/03-closure/10-make-army/solution.md
> +이제 결과가 모두 같은 이유가 무엇일까요?
```suggestion
그렇다면 왜 결과가 모두 같은걸까요?
```

2021-04-26 11:43 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/03-closure/10-make-army/solution.md
> +이유는 `shooter`안에 있는 `i`가 지역 변수가 아니기 때문입니다. 각 함수가 호출될 때, 함수는 외부 렉시컬 환경에서 `i`를 가져옵니다.
```suggestion
이유는 `shooter` 함수들 안에는 지역변수 `i`가 없기 때문입니다. 각 함수를 호출할 때, 함수는 외부 렉시컬 환경에서 `i`를 가져옵니다.
```

2021-04-26 11:43 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/03-closure/10-make-army/solution.md
> +...우리는 `makeArmy()`가 실행되는 시점에 연관된 렉시컬 환경이 존재하는 것을 확인할 수 있습니다. 그러나 `army[5]()`가 호출됐을 때 `makeArmy`는 이미 종료되었고, `i`는 마지막 값인 `10`(`while`이 종료된 시점의 값)을 갖습니다.
https://github.com/javascript-tutorial/ko.javascript.info/blob/master/CONTRIBUTING.md#%EB%B2%88%EC%97%AD-%ED%8C%81

두번째 항목을 참고해주세요

2021-04-26 11:43 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/03-closure/10-make-army/solution.md
> +결과적으로, 모든 `shooter`함수는 외부 렉시컬 환경에서 마지막 값인 `i=10`을 가져옵니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%89%BC%ED%91%9C%EB%A5%BC-%EB%AA%A8%EB%91%90-%EC%98%AE%EA%B8%B8-%ED%95%84%EC%9A%94%EB%8A%94-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4

쉼표관련 한번 전반적으로 퇴고 부탁드립니다.

2021-04-26 11:43 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/03-closure/10-make-army/solution.md
> +우리는 반복문안에서 변수를 정의하여 이 상황을 해결할 수 있습니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#we-you-she-he%EB%93%B1%EC%9D%98-%EC%9D%B8%EC%B9%AD%EB%8C%80%EB%AA%85%EC%82%AC%EB%8A%94-%EB%B2%88%EC%97%AD%ED%95%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4

'우리'가 꼭 필요한지 검토 한번 부탁드릴게요

2021-04-26 11:43 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/03-closure/10-make-army/solution.md
> +여기서 우리는 `while`을 `for`로 다시 사용했습니다
마침표가 없습니다.

2021-04-26 11:43 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/03-closure/10-make-army/solution.md
> +`i`의 값은 조금 더 가까이 존재합니다. `makeArmy()`의 렉시컬 환경 안에 존재하는 것이 아닌, 현재 반복문에 해당하는 렉시컬 환경 안에 존재합니다. 그것이 현재 작동하는 이유입니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EB%8C%80%EB%AA%85%EC%82%AC%EB%8A%94-%EB%AA%85%ED%99%95%ED%95%98%EA%B2%8C

대명사를 번역해주세요

2021-04-26 11:43 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/03-closure/10-make-army/solution.md
> +`i`의 값은 조금 더 가까이 존재합니다. `makeArmy()`의 렉시컬 환경 안에 존재하는 것이 아닌, 현재 반복문에 해당하는 렉시컬 환경 안에 존재합니다. 그것이 현재 작동하는 이유입니다.
두 문장 퇴고한번 다시 부탁드립니다.

2021-04-29 05:19 UTC, Star-ho commented
요청사항 반영하여 push 했습니다.
처음 PR하는 거라 push할때마다 반영 되는지 몰랐습니다.
다음부터는 push를 최소화 하겠습니다.

2021-04-29 05:21 UTC, Star-ho commented on 1-js/06-advanced-functions/03-closure/10-make-army/solution.md
> +3. 함수는 배열을 반환합니다.
고민해 봤는데 제 생각에는 '함수는 배열을 반환합니다.' 이 좀 더 명확할 것 같습니다.
한번 다시 읽어보시고 틀린것 같다고 생각하시면 한번 더 말씀해주세요!
수정하겠습니다

2021-08-09 08:01 UTC, closed without merging