[과제번역] Part2. 2 Introduction to browser events 과제 번역 #
javascript-tutorial/ko.javascript.info pull request #1106
Opened 2021-05-03 20:07 UTC by sese3211

# Pull Request 체크리스트
## TODO
- [ ] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [ ] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [ ] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [ ] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [ ] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [ ] PR 하나엔 번역문 하나만 넣으셨나요?
- [ ] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

2021-05-03 20:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ko.javascript.info?pullRequest=1106) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ko.javascript.info?pullRequest=1106) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ko.javascript.info?pullRequest=1106) it.</sub>

2021-05-13 12:28 UTC, Violet-Bora-Lee requested changes
위쪽 글 몇개만 리뷰해보았습니다. 가이드를 정독하시고 수정부탁드릴게요.

https://github.com/javascript-tutorial/ko.javascript.info/blob/master/CONTRIBUTING.md#%EB%B2%88%EC%97%AD-%ED%8C%81

https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%89%BC%ED%91%9C%EB%A5%BC-%EB%AA%A8%EB%91%90-%EC%98%AE%EA%B8%B8-%ED%95%84%EC%9A%94%EB%8A%94-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4

2021-05-13 12:28 UTC, Violet-Bora-Lee commented on 2-ui/2-events/01-introduction-browser-events/01-hide-other/task.md
> +중요도: 5
important는 번역하지 않습니다.

다른 번역본을 참고해주세요.

2021-05-13 12:28 UTC, Violet-Bora-Lee commented on 2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/task.md
> +이렇게요:
https://github.com/javascript-tutorial/ko.javascript.info/blob/master/CONTRIBUTING.md#%EB%B2%88%EC%97%AD-%ED%8C%81

한국어에선 문장끝이 :로 종료되는 경우가 없습니다. 

위 팁을 참고해주세요.

2021-05-13 12:28 UTC, Violet-Bora-Lee commented on 2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/task.md
>  <input type="button" onclick="this.hidden=true" value="Click to hide">
value 값도 번역해주세요

2021-05-13 12:28 UTC, Violet-Bora-Lee commented on 2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/solution.md
> +함수 객체를 제거하려면, 다음과 같이 참조를 저장해야 합니다:
문장끝 수정

2021-05-13 12:28 UTC, Violet-Bora-Lee commented on 2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/solution.md
> +해답: `1` 과 `2`.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EB%AC%B8%EC%9E%A5%EC%9D%B4-%EB%AA%85%EC%82%AC%ED%98%95%EC%9C%BC%EB%A1%9C-%EB%81%9D%EB%82%A0-%EB%95%8C%EB%8A%94-%EB%A7%88%EC%B9%A8%ED%91%9C%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4

2021-05-13 12:28 UTC, Violet-Bora-Lee commented on 2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/task.md
> +# 어떤 핸들러가 실행될까요?
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%A0%9C%EB%AA%A9%EC%97%90%EB%8A%94-%EB%AC%B8%EC%9E%A5%EB%B6%80%ED%98%B8-%EB%84%A3%EC%A7%80-%EC%95%8A%EA%B8%B0

2021-05-13 12:28 UTC, Violet-Bora-Lee commented on 2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/task.md
> +아래 코드 다음에 클릭 시 어떤 핸들러가 실행될까요? 어떤 alert창이 표시될까요?
첫번째 문장이 부자연스럽습니다.

alert 번역은 용어집 참고하여 번역해주세요.

2021-05-13 12:28 UTC, Violet-Bora-Lee commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
> +그래서 `position:absolute`를 사용해야 하고 위치를 확고히 하기 위해서 `field` 자체를 포지셔닝해야 합니다.
포지셔닝을 번역해주세요

2021-05-13 12:28 UTC, Violet-Bora-Lee commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
> +그리고 공을 필드에 상대적으로 배치시킵니다:
문장끝은 마침표로

2021-05-13 12:28 UTC, Violet-Bora-Lee commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
> +  transition: 1s all; /* CSS 애니메이션으로 왼쪽/위쪽으로 공이 날아가요 */
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%A7%9D%EC%9D%84-%EC%9D%B4%EB%A3%A8%EB%8A%94-%EB%8B%A8%EC%96%B4%EB%A5%BC-%EC%9D%B4%EC%9D%84-%EB%95%8C%EB%8A%94-%EA%B0%80%EC%9A%B4%EB%8E%83%EC%A0%90-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

2021-05-13 12:28 UTC, Violet-Bora-Lee commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
> +`event.clientX/clientY`가 있습니다. -- 클릭 window-relative 좌표를 표시합니다.
-- 은 한국어에서 잘 사용하지 않는 문장부호입니다.

2021-05-13 12:28 UTC, Violet-Bora-Lee commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
> +일반적으로, `ball.style.left`는 "요소의 왼쪽 가장자리"(공)를 의미합니다. 따라서 `left`를 할당하면 중앙이 아닌 공 가장자리가 마우스 커서 아래에 있게 됩니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EA%B0%95%EC%A1%B0%EC%9D%B8%EC%9A%A9%EC%8B%9C-%EC%82%AC%EC%9A%A9%EB%90%98%EB%8A%94-%EB%94%B0%EC%98%B4%ED%91%9C

2021-05-13 12:28 UTC, Violet-Bora-Lee commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
> +자, 따라서 `left`은 다음과 같습니다:
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%89%BC%ED%91%9C%EB%A5%BC-%EB%AA%A8%EB%91%90-%EC%98%AE%EA%B8%B8-%ED%95%84%EC%9A%94%EB%8A%94-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4

2021-05-20 12:29 UTC, sese3211 commented
미숙하여 죄송합니다. 일단 2.1장과 2.3장 과제본은 다시 번역했으니 확인부탁드려요! /done

2021-05-20 15:10 UTC, sese3211 commented
하나씩 나누어 PR 하는 법을 몰라 부득이하게 같이 보냅니다. ㅜㅜ

2021-05-20 23:50 UTC, Violet-Bora-Lee commented
안녕하세요. PR의 체크리스트를 충족하지 않은 경우엔 리뷰를 진행하지 않고 있습니다...
번거로우시겠지만 체크 리스트 항목을 확인해보신 이후에 다시 재 리뷰 요청 부탁드립니다.

2021-05-22 15:23 UTC, closed without merging

2021-05-24 06:46 UTC, sese3211 commented
기존 PR closed 하고, 새로 branch 만들어서 분리했습니다.
기존 번역들도 다시 수정했으니 시간있으실 때 확인 후 피드백 부탁드려요!
감사합니다 :)

2021년 5월 13일 목요일, JavaScript Translate Bot ***@***.***>님이 작성:

> Please make the requested changes. After it, add a comment "/done".
> Then I'll ask for a new review 👻
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/javascript-tutorial/ko.javascript.info/pull/1106#issuecomment-840523136>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATC2RKHWYFAKWXYBAV7EGOLTNPAX7ANCNFSM44BNRQVA>
> .
>