[과제번역] Part1 5.2 숫자형 과제번역  #1509
javascript-tutorial/ko.javascript.info pull request #1515
Opened 2022-08-16 05:19 UTC by Hotsumm

# 요약
Part1 5.2 숫자형의 과제 5, 6번을 번역하였습니다.

5번 
<img width="635" alt="스크린샷 2022-08-16 14 16 55" src="https://user-images.githubusercontent.com/73235751/184803145-f27c9fbe-3958-4ff0-be64-a7c24efa3a24.png">

6번 
<img width="617" alt="스크린샷 2022-08-16 14 17 56" src="https://user-images.githubusercontent.com/73235751/184803269-c05a7e90-01d1-4651-9e1e-babad9a77a59.png">
<img width="386" alt="스크린샷 2022-08-16 14 18 13" src="https://user-images.githubusercontent.com/73235751/184803302-ce5cee79-631a-4b53-a913-56c1f051d287.png">

# 연관 이슈
[#1509](https://github.com/javascript-tutorial/ko.javascript.info/issues/1509)

# Pull Request 체크리스트
## TODO
- [x] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [x] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [x] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [x] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [x] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [x] PR 하나엔 번역문 하나만 넣으셨나요?
- [x] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

2022-09-13 10:12 UTC, Violet-Bora-Lee requested changes

2022-09-13 10:12 UTC, Violet-Bora-Lee commented on 1-js/05-data-types/02-number/9-random-int-min-max/solution.md
> +# 간단 하지만 틀린 해답
`간단하지만`으로 수정부탁드립니다.
https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=116122

2022-09-13 10:12 UTC, Violet-Bora-Lee commented on 1-js/05-data-types/02-number/9-random-int-min-max/solution.md
> +기능은 동작하지만, 올바르지 않습니다. 에지값 `min`과 `max`가 나올 확률이 다른 것보다 두 배 적습니다.
여기서 function은 randomInteger `함수`를 의미합니다. 

번역기를 돌린것으로 판단됩니다.

자연스럽게 수정 하시고, 코멘트 달아주시면 다시 리뷰 진행하도록 하겠습니다.

2022-09-13 10:12 UTC, Violet-Bora-Lee commented
8번과 9번 문제 PR을 따로 작성해주실수 있을까요?
리뷰가 길어질것같아서요

2022-09-21 07:49 UTC, Hotsumm commented on 1-js/05-data-types/02-number/9-random-int-min-max/solution.md
> +# 간단 하지만 틀린 해답
수정하겠습니다.

2022-09-21 07:50 UTC, Hotsumm commented on 1-js/05-data-types/02-number/9-random-int-min-max/solution.md
> +기능은 동작하지만, 올바르지 않습니다. 에지값 `min`과 `max`가 나올 확률이 다른 것보다 두 배 적습니다.
다시보니까 말씀대로 
자연스러운 번역같지가 않네요
수정하겠습니다!

2022-09-21 07:51 UTC, Hotsumm commented
> 8번과 9번 문제 PR을 따로 작성해주실수 있을까요? 리뷰가 길어질것같아서요

넵 8번 9번 나눠서 PR 올릴게요~

2022-09-21 08:28 UTC, closed without merging