#1717 random-min-max solution 번역 5번째 줄
javascript-tutorial/ko.javascript.info pull request #1729
Opened 2023-12-01 07:21 UTC by cocoa-salon

# 요약
random-min-max solution 번역 5번째 줄

# 연관 이슈
#1717

# Pull Request 체크리스트
## TODO
- [x] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [x] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [x] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [x] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [x] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [x] PR 하나엔 번역문 하나만 넣으셨나요?
- [x] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

2023-12-01 07:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ko.javascript.info?pullRequest=1729) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ko.javascript.info?pullRequest=1729) before we can accept your contribution.<br/><hr/>**Kevin Lee** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ko.javascript.info?pullRequest=1729) it.</sub>

2023-12-01 07:39 UTC, Violet-Bora-Lee approved these changes
잘 해주셨습니다.
다만 조금더 독자를 위해 개선해주셨으면 하는 부분에 대해 코멘트 달아보았습니다.

2023-12-01 07:39 UTC, Violet-Bora-Lee commented on 1-js/05-data-types/02-number/8-random-min-max/solution.md
> +1. 0..1의 임의의 숫자에 `max-min`를 곱하면 가능한 값의 간격이 `0..1`에서 `0..max-min`으로 증가합니다.
```suggestion
1. 0과 1 사이의 임의의 숫자에 `max-min`을 곱하면 가능한 값의 간격이 `0..1`에서 `0..max-min`으로 증가합니다.
```

2023-12-01 11:03 UTC, cocoa-salon commented
피드백 반영하여 orign 에 푸시하였습니다. 확인 부탁드립니다.

2023-12-06 08:40 UTC, Violet-Bora-Lee commented
커밋을 하나로 합쳐주세요.
작업 단위에 비해 커밋 갯수가 너무 많습니다.

2023-12-06 08:44 UTC, Violet-Bora-Lee requested changes
코멘트 달아두었습니다.

2023-12-06 09:30 UTC, cocoa-salon commented
@Violet-Bora-Lee 네 커밋을 하나로 합쳐서 다시 push 하였습니다. 확인 부탁드립니다.

2023-12-06 09:54 UTC, Violet-Bora-Lee commented
커밋과 이슈를 연동해주세요.

2023-12-06 10:02 UTC, Violet-Bora-Lee requested changes

2023-12-06 10:02 UTC, Violet-Bora-Lee commented on 1-js/05-data-types/02-number/8-random-min-max/solution.md
> +```
여기는 왜 변경된거죠?

PR 리뷰 요청을 하기전에 자신이 만든 PR을 점검해주세요.

2023-12-06 10:12 UTC, cocoa-salon commented on 1-js/05-data-types/02-number/8-random-min-max/solution.md
> +```
자동 포맷팅 기능으로 인한 기존 코드 포맷 변경 사항 복원이 완전히 이루어지지 않은 것 같습니다. 다시 수정하겠습니다.

2023-12-10 13:04 UTC, Violet-Bora-Lee commented
그냥 머지해도 되긴하는데,,
위에 코멘트 달린거 확인하셨나요?
PR을 만들게되면 항상 메일링을 통해 PR을 추적하셔야합니다.

2023-12-10 14:15 UTC, cocoa-salon reviewed
기존 자동 포맷이 적용된 코드를 복원 후 실제 번역 수정된 부분만 반영하였습니다.

2023-12-10 14:21 UTC, Violet-Bora-Lee commented
> Please make the requested changes. After it, add a comment "/done". Then I'll ask for a new review 👻

@cocoa-salon 여기요..

2023-12-10 14:22 UTC, Violet-Bora-Lee commented
PR을 만들었을땐 항상 댓글을 확인해주세요. 요즘엔 bot이 자동으로 다는경우도 많아서 오픈소스 기여할땐 항상 확인하셔야합니다.

2023-12-10 14:22 UTC, cocoa-salon commented
/done

2023-12-10 14:25 UTC, Violet-Bora-Lee commented
머지 진행하겠습니다~
한줄짜리 기여인데도 챙길게 많았네요... 
앞으론 항상 꼼꼼하게 확인하셔서 오픈소스 잘 기여하시길 바랍니다~

2023-12-10 14:25 UTC, merged

2023-12-10 14:28 UTC, cocoa-salon commented
@Violet-Bora-Lee 네 끝까지 지도해주셔서 감사합니다. 늦은 시간까지 고생 많으셨습니다!