[파일 업로드 재개하기] 번역
javascript-tutorial/ko.javascript.info pull request #678
Opened 2020-08-12 07:30 UTC by DavidYang2149

# Pull Request 체크리스트
## TODO
- [X] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [X] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [X] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [X] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [X] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [X] PR 하나엔 번역문 하나만 넣으셨나요?
- [X] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

안녕하세요.
[파일 업로드 재개하기] 번역 Pull Request를 올립니다.
상단의 가이드라인을 토대로 작업하였는데 첫번역 작업이라서 수정할 부분을 알려주시면 고치도록 하겠습니다.
감사합니다.

2020-08-12 07:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ko.javascript.info?pullRequest=678) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ko.javascript.info?pullRequest=678) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ko.javascript.info?pullRequest=678) it.</sub>

2020-09-06 04:05 UTC, DavidYang2149 commented
/done

2020-09-06 13:09 UTC, Violet-Bora-Lee requested changes
대명사 번역이 누락되어있어서 문장 전달력이 떨어집니다.

다시 퇴고 부탁드립니다.

2020-09-06 13:09 UTC, Violet-Bora-Lee commented on 5-network/09-resume-upload/article.md
> +2. 서버에 요청을 보내어 바이트가 이미 얼마나 되는지 물어봅니다. 이렇게요.
바이트가 이미 얼마가 되는지 <-- 이부분이 부자연스럽습니다.

얼마만큼의 바이트를 전송했는지 질의합니다. 정도로 번역하면 어떨까요?

2020-09-06 13:09 UTC, Violet-Bora-Lee commented on 5-network/09-resume-upload/article.md
>      let startByte = +await response.text();
41번째 줄의 주석 번역 누락

2020-09-06 13:09 UTC, Violet-Bora-Lee commented on 5-network/09-resume-upload/article.md
>      xhr.open("POST", "upload", true);
주석 번역 모두 누락

2020-09-06 13:09 UTC, Violet-Bora-Lee commented on 5-network/09-resume-upload/article.md
> +    서버에 파일 아이디인 `X-File-Id`를 보내 업로드를 할 파일을 알고 시작 바이트인 `X-Start-Byte`를 서버에 보내 처음부터 업로드를 하지 않고 재개하게 합니다.
업로드를 할 파일을 아는것은 누구인가요?
재개하는 주체는 누구인가요?

대명사 번역이 누락되어 전체적으로 문장 전달력이 떨어집니다.

2020-09-06 13:09 UTC, Violet-Bora-Lee commented on 5-network/09-resume-upload/article.md
> +    서버는 기록을 확인해서 파일에 업로드가 있었는지 그리고 현재 올리는 크기가 정확히 `X-Start-Byte`인지 확인하고 데이터를 확장합니다.
'올리는 크기'에서 어떤것의 크기는 어떤것의 크기를 말하는건가요?

수식어는 수식하는 대상을 명시해주어야합니다.

2020-09-06 13:09 UTC, Violet-Bora-Lee commented on 5-network/09-resume-upload/article.md
> +Node.js는 Nginx의 서버 뒤에서 버퍼 업로드가 완료되었을 때 Node.js로 전달하기 때문에 이 사이트에서만 부분적으로 작동합니다.
'무엇을' 노드js로 전달하나요?
대명사 번역이 누락되어있습니다.

2020-09-07 01:54 UTC, DavidYang2149 commented on 5-network/09-resume-upload/article.md
> +2. 서버에 요청을 보내어 바이트가 이미 얼마나 되는지 물어봅니다. 이렇게요.
말씀하신 부분이 더 자연스럽네요. 해당 내용 반영했습니다. 감사합니다.

2020-09-07 01:55 UTC, DavidYang2149 commented on 5-network/09-resume-upload/article.md
>      let startByte = +await response.text();
해당 주석 번역 작업을 추가했습니다.

2020-09-07 01:56 UTC, DavidYang2149 commented on 5-network/09-resume-upload/article.md
>      xhr.open("POST", "upload", true);
53, 56, 63번째 줄의 주석 번역을 추가했습니다.

2020-09-07 01:58 UTC, DavidYang2149 commented on 5-network/09-resume-upload/article.md
> +    서버에 파일 아이디인 `X-File-Id`를 보내 업로드를 할 파일을 알고 시작 바이트인 `X-Start-Byte`를 서버에 보내 처음부터 업로드를 하지 않고 재개하게 합니다.
업로드를 할 파일을 아는 것은 서버고 재개하는 주체는 우리(클라이언트)라서 문장을 '우리가 업로드를 진행할 파일이 어떤 것인지 서버에 알리고'와 '우리가 파일 업로드를 초기화하지 않고 재개할 것을 서버에 알게 합니다'로 수정하였습니다.

2020-09-07 01:59 UTC, DavidYang2149 commented on 5-network/09-resume-upload/article.md
> +    서버는 기록을 확인해서 파일에 업로드가 있었는지 그리고 현재 올리는 크기가 정확히 `X-Start-Byte`인지 확인하고 데이터를 확장합니다.
대상은 서버가 가지고 있던 파일이기 때문에 '현재 서버에 업로드가 되었던 파일의 크기가'로 수정하였습니다.

2020-09-07 02:00 UTC, DavidYang2149 commented on 5-network/09-resume-upload/article.md
> +Node.js는 Nginx의 서버 뒤에서 버퍼 업로드가 완료되었을 때 Node.js로 전달하기 때문에 이 사이트에서만 부분적으로 작동합니다.
노드js에 전달할 대상은 완료된 버퍼 업로드이기 때문에 '완료된 버퍼 업로드를'로 수정하였습니다.

2020-09-07 02:03 UTC, DavidYang2149 commented
@Violet-Bora-Lee

- 누락된 대명사에 대한 번역 작업을 추가하였습니다.
- 누락된 주석 번역 작업을 추가하였습니다.
- 문장을 전달력을 고려하였습니다.

피드백 주셔서 감사합니다.
다시 한번 검토 요청드립니다. 😊

2020-09-07 02:03 UTC, DavidYang2149 commented
/done

2020-09-17 12:06 UTC, Violet-Bora-Lee requested changes
감사합니다 👍 
거의 마무리된것같아요! 
코멘트 남겨드린 부분 확인 부탁드리고, 마지막으로 
http://m.blog.naver.com/ojhnews/220840570533
이글 읽어보신 후, 퇴고 한번 더 부탁드립니다

2020-09-17 12:06 UTC, Violet-Bora-Lee commented on 5-network/09-resume-upload/article.md
> +    // 업로드를 할 파일은 input.files[0]나 또 다른 소스가 될 수 있습니다.
소스도 번역해주세요

2020-09-17 12:06 UTC, Violet-Bora-Lee commented on 5-network/09-resume-upload/article.md
> +    서버에 파일 아이디인 `X-File-Id`를 보내 우리가 업로드를 진행할 파일이 어떤 것인지 서버에 알리고 시작 바이트인 `X-Start-Byte`를 서버에 보내 우리가 파일 업로드를 초기화하지 않고 재개할 것을 서버에 알게 합니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#we-you-she-he%EB%93%B1%EC%9D%98-%EC%9D%B8%EC%B9%AD%EB%8C%80%EB%AA%85%EC%82%AC%EB%8A%94-%EB%B2%88%EC%97%AD%ED%95%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4

모범사례 확인 부탁드립니다

2020-09-26 03:33 UTC, DavidYang2149 commented on 5-network/09-resume-upload/article.md
> +    // 업로드를 할 파일은 input.files[0]나 또 다른 소스가 될 수 있습니다.
`input.files[0]`를 `입력.파일들[0]`로 수정하였습니다.

2020-09-26 03:34 UTC, DavidYang2149 commented on 5-network/09-resume-upload/article.md
> +    서버에 파일 아이디인 `X-File-Id`를 보내 우리가 업로드를 진행할 파일이 어떤 것인지 서버에 알리고 시작 바이트인 `X-Start-Byte`를 서버에 보내 우리가 파일 업로드를 초기화하지 않고 재개할 것을 서버에 알게 합니다.
**As-is**
서버에 파일 아이디인 `X-File-Id`를 보내 우리가 업로드를 진행할 파일이 어떤 것인지 서버에 알리고 시작 바이트인 `X-Start-Byte`를 서버에 보내 우리가 파일 업로드를 초기화하지 않고 재개할 것을 서버에 알게 합니다.

**To-be**
서버에 파일 아이디인 `X-File-Id`를 보내 업로드를 진행할 파일이 어떤 것인지 서버에 알리고 시작 바이트인 `X-Start-Byte`를 서버에 보내 파일 업로드를 초기화하지 않고 재개할 것을 서버에 알게 합니다.

로 수정하였습니다.

2020-09-26 04:15 UTC, DavidYang2149 commented
@Violet-Bora-Lee

- 피드백 주신 부분을 수정하였습니다.
- `~의` 불필요한 사용을 줄였습니다.
- `~ 때문에`, `~의해` 불필요한 사용을 줄였습니다.
- `~던`의 사용을 수정하였습니다.

피드백 주셔서 감사합니다.
다시 한번 검토 요청드립니다. 😊

2020-09-26 04:15 UTC, DavidYang2149 commented
/done

2020-10-09 07:51 UTC, Violet-Bora-Lee requested changes
형식적인것은 지난번 리뷰까지 해서 거의다 잡았는데요(위키 문서에 나와있는것들...)

오역과 직역 관련하여 코멘트 달아드렸습니다

잘 모르시는 내용이면 공부 후에 번역부탁드릴게요

2020-10-09 07:51 UTC, Violet-Bora-Lee commented on 5-network/09-resume-upload/article.md
> +    // 파일 아이디를 통해 우리가 어떤 파일을 업로드 할지 서버는 알게 됩니다.
we 같은 인칭대명사는 번역하지 않습니다.

https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#we-you-she-he%EB%93%B1%EC%9D%98-%EC%9D%B8%EC%B9%AD%EB%8C%80%EB%AA%85%EC%82%AC%EB%8A%94-%EB%B2%88%EC%97%AD%ED%95%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4

2020-10-09 07:51 UTC, Violet-Bora-Lee commented on 5-network/09-resume-upload/article.md
> +    // 우리가 업로드를 재개할 파일의 시작 바이트를 통해 서버는 파일 업로드가 재개될 것을 알게 됩니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#we-you-she-he%EB%93%B1%EC%9D%98-%EC%9D%B8%EC%B9%AD%EB%8C%80%EB%AA%85%EC%82%AC%EB%8A%94-%EB%B2%88%EC%97%AD%ED%95%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4

2020-10-09 07:51 UTC, Violet-Bora-Lee commented on 5-network/09-resume-upload/article.md
> +    // 업로드를 할 파일은 입력.파일들[0]이나 또 다른 소스가 될 수 있습니다.
input.files[0] 이거는 input이라는 객체에 있는 files 프로퍼티의 0번째 요소에 접근한다는 의미의 '코드'이기 때문에 번역하지 않으셔야해요

2020-10-09 07:51 UTC, Violet-Bora-Lee commented on 5-network/09-resume-upload/article.md
> +    서버에 파일 아이디인 `X-File-Id`를 보내 업로드를 진행할 파일이 어떤 것인지 서버에 알리고 시작 바이트인 `X-Start-Byte`를 서버에 보내 파일 업로드를 초기화하지 않고 재개할 것을 서버에 알게 합니다.
문장 다시한번 읽어주세요.

```suggestion
    파일 아이디인 `X-File-Id`를 서버로 보내 업로드를 진행할 파일이 어떤 것인지 알리고, 시작 바이트인 `X-Start-Byte`를 보내 파일 업로드를 초기화하지 않고 파일 업로드를 다시 시작한다는 것을 서버에 알게 합니다.
```

2020-10-09 07:51 UTC, Violet-Bora-Lee commented on 5-network/09-resume-upload/article.md
> +    서버는 기록을 확인해서 파일에 업로드가 있었는지 그리고 현재 서버에 업로드가 된 파일 크기가 정확히 `X-Start-Byte`인지 확인하고 업로드를 진행할 파일 데이터를 확장합니다.
파일 데이터를 '확장한다'라는 표현은 들어보지 못한것같아요

기존에 서버에 올린 데이터에 아직 올리지 못한 데이터를 다시 올려서 추가한다는 말인데요, 수정을 해주세요.

2020-10-09 07:51 UTC, Violet-Bora-Lee commented on 5-network/09-resume-upload/article.md
> +Node.js는 Nginx 서버 뒤에서 버퍼 업로드가 완료되었을 때 Node.js로 완료된 버퍼 업로드를 전달하기 때문에 이 사이트에서만 부분적으로 작동합니다.
buffer는 동사로 쓰이고있어요
오역이기 때문에 문장을 제대로 이해하신 후 수정부탁드릴게요

2020-10-10 02:12 UTC, DavidYang2149 commented on 5-network/09-resume-upload/article.md
> +    // 파일 아이디를 통해 우리가 어떤 파일을 업로드 할지 서버는 알게 됩니다.
'우리가' 부분을 삭제하였습니다.

2020-10-10 02:12 UTC, DavidYang2149 commented on 5-network/09-resume-upload/article.md
> +    // 우리가 업로드를 재개할 파일의 시작 바이트를 통해 서버는 파일 업로드가 재개될 것을 알게 됩니다.
'우리가' 부분을 삭제하였습니다.

2020-10-10 02:13 UTC, DavidYang2149 commented on 5-network/09-resume-upload/article.md
> +    // 업로드를 할 파일은 입력.파일들[0]이나 또 다른 소스가 될 수 있습니다.
'소스'를 수정해달라는 요청을 제가 오해했습니다. 해당 코드는 원복하였고 '소스'는 '출처'로 수정하였습니다.

2020-10-10 02:13 UTC, DavidYang2149 commented on 5-network/09-resume-upload/article.md
> +    서버에 파일 아이디인 `X-File-Id`를 보내 업로드를 진행할 파일이 어떤 것인지 서버에 알리고 시작 바이트인 `X-Start-Byte`를 서버에 보내 파일 업로드를 초기화하지 않고 재개할 것을 서버에 알게 합니다.
문장 내용이 훨씬 매끄럽네요. 내용 반영하여 수정하였습니다. 감사합니다!

2020-10-10 02:24 UTC, DavidYang2149 commented on 5-network/09-resume-upload/article.md
> +    서버는 기록을 확인해서 파일에 업로드가 있었는지 그리고 현재 서버에 업로드가 된 파일 크기가 정확히 `X-Start-Byte`인지 확인하고 업로드를 진행할 파일 데이터를 확장합니다.
말씀하신 내용을 확인하여
기존의 '확인하고 업로드를 진행할 파일 데이터를 확장합니다' 를
'확인한 후에 서버에 업로드가 된 파일 크기의 시점부터 파일 데이터를 추가합니다'로 변경하였습니다.

2020-10-10 04:06 UTC, DavidYang2149 commented on 5-network/09-resume-upload/article.md
> +Node.js는 Nginx 서버 뒤에서 버퍼 업로드가 완료되었을 때 Node.js로 완료된 버퍼 업로드를 전달하기 때문에 이 사이트에서만 부분적으로 작동합니다.
버퍼를 어떻게 표기할지 고민하다가 사전에서 '완충 기억 장치에 저장하다'는 뜻이 있어 해당 틀에 맞추어 수정하였습니다.
파일을 업로드할 때 Nginx에서 업로드할 파일을 버퍼한 후 작업이 완료되면 Node.js로 전달한다고 이해했습니다.
추가로 수정할 내용한 부분이 있어 피드백을 주신다면 수정하도록 하겠습니다.

2020-10-10 04:14 UTC, DavidYang2149 commented
@Violet-Bora-Lee

오역과 직역에 대한 부분을 수정하였습니다.

피드백 주셔서 감사합니다.
다시 한번 검토 요청드립니다. 😊

2020-10-10 04:14 UTC, DavidYang2149 commented
/done

2020-10-10 04:25 UTC, Violet-Bora-Lee commented on 5-network/09-resume-upload/article.md
> +    // 업로드를 할 파일은 input.files[0]나 또 다른 소스가 될 수 있습니다.
Source를 소스로 번역하지 마시고 적합한 한글 단어를 찾아주세요..

2020-10-10 05:27 UTC, DavidYang2149 commented on 5-network/09-resume-upload/article.md
> +    // 업로드를 할 파일은 input.files[0]나 또 다른 소스가 될 수 있습니다.
@Violet-Bora-Lee 
앗! 
'소스'는 '출처' 로 변경하였는데 해당 내용을 기제하지 않았네요.
해당 내용은 이미 수정하였습니다.
괜찮으시다면 review need로 변경해도 될까요?

2020-10-10 06:22 UTC, DavidYang2149 commented on 5-network/09-resume-upload/article.md
> +    // 업로드를 할 파일은 input.files[0]나 또 다른 소스가 될 수 있습니다.
우선 이미 수정된 내용이여서 review need로 상태 변경해놓겠습니다~

2020-10-10 06:22 UTC, DavidYang2149 commented
/done

2020-11-21 08:11 UTC, Violet-Bora-Lee commented
감사합니다. 머지 진행할게요!
긴 시간동안 리뷰 반영해주시고 고생 진짜 많으셨습니다 👍

2020-11-21 08:11 UTC, merged

2020-11-21 10:51 UTC, DavidYang2149 commented
감사합니다. 피드백 주시느라 고생 많으셨습니다!