[fetch] - 과제 번역 #679
javascript-tutorial/ko.javascript.info pull request #682
Opened 2020-08-13 06:28 UTC by C17AN

# Pull Request 체크리스트
## TODO
- [✅] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [✅] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [✅] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [✅] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [✅] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [✅] PR 하나엔 번역문 하나만 넣으셨나요?
- [✅] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

2020-08-24 12:31 UTC, C17AN commented
/done

2020-08-30 03:33 UTC, Violet-Bora-Lee requested changes
코멘트 확인 부탁드립니다.

2020-08-30 03:33 UTC, Violet-Bora-Lee commented on 5-network/01-fetch/01-fetch-users/_js.view/source.js
> +  /* 여기에 코드를 작성하세요 */
문장이니 마침표 붙여주세요

2020-08-30 03:33 UTC, Violet-Bora-Lee commented on 5-network/01-fetch/01-fetch-users/_js.view/test.js
> +    let users = await getUsers(["C17AN", "Violet-Bora-Lee", "이런.사용자는.없습니다"]);
1. 되도록이면 자연어만 수정해주세요.
쌍따옴표 대신 기존 따옴표를 사용해주시기 바랍니다.

2. 중간에 점 없이 '이런사용자는없습니다' 이렇게 해도 될것같아요.

2020-08-30 03:33 UTC, Violet-Bora-Lee commented on 5-network/01-fetch/01-fetch-users/solution.md
> +만약 응답의 상태 코드가 `200` 이라면, 수신한 객체를 읽기 위해 `.json()` 을 호출합니다.
모범사례 확인부탁드립니다.

https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#if%EB%8A%94-%EC%83%9D%EB%9E%B5%ED%95%A0-%EC%88%98%EB%8F%84-%EC%9E%88%EC%8A%B5%EB%8B%88%EB%8B%A4

https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%89%BC%ED%91%9C%EB%A5%BC-%EB%AA%A8%EB%91%90-%EC%98%AE%EA%B8%B8-%ED%95%84%EC%9A%94%EB%8A%94-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4

2020-08-30 03:33 UTC, Violet-Bora-Lee commented on 5-network/01-fetch/01-fetch-users/solution.md
> +반면 `fetch` 에 실패하거나 응답의 상태 코드가 200이 아니라면 `null`을 리턴하고 배열에 담아야 합니다.
응답의 상태코드, 응답 상태 코드

둘 중 어떤게 적절한지 생각하시어 수정부탁드릴게요

2020-08-30 03:33 UTC, Violet-Bora-Lee commented on 5-network/01-fetch/01-fetch-users/solution.md
> +유의할 점으로는 `.then` 은 `fetch` 직후 호출되므로 다른 fetch 동작을 기다리지 않고 곧바로 `.json()` 으로 응답을 읽기 시작합니다.
주의할 점으로는~~~~ 읽기 시작합니다.

주술 구조가 안맞습니다. 확인해주세요.

2020-08-30 03:33 UTC, Violet-Bora-Lee commented on 5-network/01-fetch/01-fetch-users/solution.md
> +만약 `await Promise.all(names.map(name => fetch(...)))` 의 수행 결과에 `.json()` 을 사용한다면, 모든 fetch의 응답이 수신되기 전까지 기다려야 할 것입니다. 그 대신 각 `fetch`마다 `.json()` 을 호출함으로써 fetch들이 서로 기다리지 않고 JSON 형식으로 데이터를 읽어 나가도록 보장합
if관련 모범사례 확인해주세요.

2020-08-30 03:33 UTC, Violet-Bora-Lee commented on 5-network/01-fetch/01-fetch-users/task.md
> +# Fetch를 사용해 Github 에서 사용자 정보 가져오기
fetch는 코드이니까 대문자 안쓰고 소문자로 해도될것같아요.

```suggestion
# fetch를 사용해 Github에서 사용자 정보 가져오기
```

2020-08-30 03:33 UTC, Violet-Bora-Lee commented on 5-network/01-fetch/01-fetch-users/task.md
> +GitHub 사용자 이름의 배열을 인자로 받는 비동기 함수 `getUsers(names)` 를 만든 후, GitHub 에서 fetch 한 사용자 정보의 배열을 반환하는 함수를 만들어 보세요.
getUsers는 복수의 사용자에 대한 처리를 해준다는점이 특징인것같습니다.
이럴땐 복수형 표현 `들`을 써도되니, 고려하시어 설명 수정 부탁드립니다.

2020-08-30 03:33 UTC, Violet-Bora-Lee commented on 5-network/01-fetch/01-fetch-users/task.md
> +3. 요청에 실패하거나 사용자가 존재하지 않는다면 `null`을 리턴하고 배열에 담아야 합니다.
`여러` 사용자에 대한 `요청`을 보내는데, `그 중 하나라도` 실패하면 null을 리턴한다는 말인데,
이런부분이 문제에 녹아있지 않습니다.

2020-09-08 07:59 UTC, C17AN commented on 5-network/01-fetch/01-fetch-users/task.md
> +3. 요청에 실패하거나 사용자가 존재하지 않는다면 `null`을 리턴하고 배열에 담아야 합니다.
이 부분은 해답 코드를 실행해봤는데, 각 요청에 대해 검사한 후 실패한 요청에 대해서만 null을 리턴하는게 맞는 것 같아 이렇게 번역했어요!!

혹시 더 괜찮은 문장이 있으면 제안 한번만 부탁드리겠습니다! 😂

[해답 코드]
```
async function getUsers(names) {
  let jobs = [];

  for(let name of names) {
    let job = fetch(`https://api.github.com/users/${name}`).then(
      successResponse => {
        if (successResponse.status != 200) {
          return null;
        } else {
          return successResponse.json();
        }
      },
      failResponse => {
        return null;
      }
    );
    jobs.push(job);
  }

  let results = await Promise.all(jobs);

  return results;
}
```

[해답 코드 실행 결과]
![image](https://user-images.githubusercontent.com/26535030/92448977-547cca00-f1f4-11ea-87ae-08c467447c42.png)

2020-09-08 08:08 UTC, C17AN commented
/done

2020-09-10 11:35 UTC, Violet-Bora-Lee requested changes

2020-09-10 11:35 UTC, Violet-Bora-Lee commented on 5-network/01-fetch/01-fetch-users/solution.md
> +fetch를 통해 사용자 정보를 가져오기 위해서는 `fetch('https://api.github.com/users/사용자명')`를 사용해야 합니다.
```suggestion
fetch를 통해 사용자 정보를 가져오려면 `fetch('https://api.github.com/users/사용자명')`를 사용해야 합니다.
```
'~하기 위해서는'은 번역투입니다. 퇴고 한번만 더 해주시면서 최대한 군더더기를 빼봐주세요.

2020-09-10 11:35 UTC, Violet-Bora-Lee commented on 5-network/01-fetch/01-fetch-users/solution.md
> +응답의 상태 코드가 `200` 이라면 수신한 객체를 읽기 위해 `.json()` 을 호출합니다.
```suggestion
응답 상태 코드가 `200`이면 `.json()`을 호출해 객체를 읽습니다. 
```

2020-09-10 11:35 UTC, Violet-Bora-Lee commented on 5-network/01-fetch/01-fetch-users/solution.md
> +반면 `fetch`에 실패하거나 응답 상태 코드가 200이 아니라면 `null`을 리턴하고 배열에 담아야 합니다.
```suggestion
반면 `fetch`가 실패하거나 응답 상태 코드가 200이 아니라면 `null`을 리턴하고 배열에 담아야 합니다.
```

2020-09-10 11:35 UTC, Violet-Bora-Lee commented on 5-network/01-fetch/01-fetch-users/solution.md
> +`.then`은 `fetch` 직후 호출되므로 다른 fetch를 기다리지 않고 곧바로 `.json()`으로 응답을 읽기 시작한다는 점에 유의하세요.
so that when we have the response, 번역이 누락되어있습니다.

2020-09-10 11:35 UTC, Violet-Bora-Lee commented on 5-network/01-fetch/01-fetch-users/solution.md
> +`await Promise.all(names.map(name => fetch(...)))` 의 수행 결과에 `.json()`을 사용한다면, 모든 fetch의 응답이 수신되기 전까지 기다려야 할 것입니다. 그 대신 각 `fetch`마다 `.json()`을 호출함으로써 fetch들이 서로 기다리지 않고 JSON 형식으로 데이터를 읽도록 보장합니다.
```suggestion
`await Promise.all(names.map(name => fetch(...)))`의 반환값을 대상으로 `.json()`을 호출한다면, 모든 fetch 응답이 완료되기 전까지 기다려야 합니다. 그 대신 각 `fetch`마다 `.json()`을 호출하면 다른 fetch가 완료되는 것을 기다리지 않고도 JSON 형식으로 데이터를 읽을 수 있습니다.
```

2020-09-10 11:35 UTC, Violet-Bora-Lee commented on 5-network/01-fetch/01-fetch-users/solution.md
> +이 예제를 통해 비록 `async/await`을 주로 사용하더라도 여전히 하위 수준의 프로미스(Promise) API가 유용하게 사용될 수 있음을 알 수 있습니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%A7%9D%EC%9D%84-%EC%9D%B4%EB%A3%A8%EB%8A%94-%EB%8B%A8%EC%96%B4%EB%A5%BC-%EC%9D%B4%EC%9D%84-%EB%95%8C%EB%8A%94-%EA%B0%80%EC%9A%B4%EB%8E%83%EC%A0%90-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

2020-09-10 11:35 UTC, Violet-Bora-Lee commented on 5-network/01-fetch/01-fetch-users/task.md
> +주어진 `사용자명` 에 해당하는 사용자 정보가 포함된 GitHub URL은 `https://api.github.com/users/사용자명` 입니다.
```suggestion
`사용자명`에 해당하는 사용자 정보를 가져오려면 GitHub API `https://api.github.com/users/사용자명`에 요청을 보내면 됩니다.
```

2020-09-10 11:35 UTC, Violet-Bora-Lee commented on 5-network/01-fetch/01-fetch-users/task.md
> +1. 사용자당 한 번의 `fetch` 요청만을 수행해야 합니다.
```suggestion
1. 사용자당 `fetch` 요청은 한 번만 수행해야 합니다.
```

2020-09-10 11:35 UTC, Violet-Bora-Lee commented on 5-network/01-fetch/01-fetch-users/task.md
> +3. 요청에 실패하거나 사용자가 존재하지 않는다면 `null`을 리턴하고 배열에 담아야 합니다.
그럼 이렇게 하면 어떨까요?
```suggestion
3. 요청에 실패하거나 존재하지 않는 사용자에 대한 요청을 보냈다면 `null`을 리턴하고 배열 요소에 담아야 합니다.
```

2020-09-22 14:10 UTC, C17AN commented
/done.

2020-09-22 14:26 UTC, Violet-Bora-Lee commented on 5-network/01-fetch/01-fetch-users/solution.md
> +이 예제를 통해 비록 `async-await`을 주로 사용하더라도 여전히 하위 수준의 프로미스(Promise) API가 유용하게 사용될 수 있음을 알 수 있습니다.
promise는 프라미스로 번역하기로 하였습니다.
용어집을 확인해주세요.

2020-09-22 14:27 UTC, Violet-Bora-Lee reviewed
용어집 참고하시어 한개만 더 수정부탁드려요

2020-09-22 14:53 UTC, C17AN commented on 5-network/01-fetch/01-fetch-users/solution.md
> +이 예제를 통해 비록 `async-await`을 주로 사용하더라도 여전히 하위 수준의 프로미스(Promise) API가 유용하게 사용될 수 있음을 알 수 있습니다.
아차차 죄송합니다 😂

2020-09-22 14:53 UTC, C17AN commented
/done.

2020-09-30 10:58 UTC, Violet-Bora-Lee commented
머지 진행하겠습니다.
고생많으셨습니다 👍

2020-09-30 10:58 UTC, merged

2020-10-01 03:19 UTC, C17AN commented
감사합니다!! 피드백을 받다 보니 결국에는 멘토님이 다 해주신 것 같지만.... ㅋㅋㅋㅋ
이렇게 큰 프로젝트에 작게나마 한 획을 그었다는게 너무 뿌듯하네요 😍

정말 오래오래 끝까지 리뷰해주셔서 감사드리며, 즐거운 명절 보내세요!! 😆