[1.6.10 함수 바인딩] 첫 번째 과제&해답 번역
javascript-tutorial/ko.javascript.info pull request #728
Opened 2020-08-20 18:58 UTC by rovin0805

# Pull Request 체크리스트
## TODO
- [x] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [x] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [x] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [x] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [x] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [x] PR 하나엔 번역문 하나만 넣으셨나요?
- [x] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

2020-08-30 03:35 UTC, Violet-Bora-Lee requested changes
코멘트 확인해주세요

2020-08-30 03:35 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/2-write-to-object-after-bind/task.md
> +# 메서드로서의 묶인 함수
번역투가 너무 심한 번역입니다.

실제 독자라고 생각하고 이 문제가 어떤 제목을 가져야 좋을지 고민해서 번역해주세요.

2020-08-30 03:35 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/2-write-to-object-after-bind/task.md
> +결과는 무엇일까요?
```suggestion
아래 코드를 실행하면 어떤 결과가 나올까요?
```

이렇게 해야 독자가 편하게 읽을수있지 않을까요?

2020-08-30 16:21 UTC, rovin0805 commented
리뷰 참고 후 번역 수정하였습니다..!

2020-09-03 13:16 UTC, rovin0805 commented
/done

2020-09-06 13:13 UTC, Violet-Bora-Lee commented
감사합니다.
커밋 하나로 합쳐주시면 바로 머지 진행할게요

2020-09-07 16:03 UTC, rovin0805 commented
/done

2020-09-08 14:35 UTC, Violet-Bora-Lee commented
나머지 과제들도 따로 PR 만들지 마시고 여기에서 작업해주세요.
불필요한 PR을 만들지 말아주세요.

2020-09-09 05:41 UTC, rovin0805 commented
PR을 다시 하나로 합치고 나머지 부분도 번역해서 올려놓았습니다..!

2020-09-10 11:47 UTC, Violet-Bora-Lee requested changes

2020-09-10 11:47 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/5-question-use-bind/solution.md
> +에러는 `ask`가 함수 `loginOk/loginFail`를 객체 없이 가지기 때문에 발생합니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%A7%9D%EC%9D%84-%EC%9D%B4%EB%A3%A8%EB%8A%94-%EB%8B%A8%EC%96%B4%EB%A5%BC-%EC%9D%B4%EC%9D%84-%EB%95%8C%EB%8A%94-%EA%B0%80%EC%9A%B4%EB%8E%83%EC%A0%90-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

2020-09-10 12:30 UTC, rovin0805 commented
/done

2020-09-10 14:54 UTC, Violet-Bora-Lee requested changes

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/2-write-to-object-after-bind/task.md
> +# 메서드로 쓰이는 묶인 함수
```suggestion
# bind를 적용한 함수를 메서드에 정의하기
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/2-write-to-object-after-bind/solution.md
> +정답: `null`.
```suggestion
정답: `null`
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/2-write-to-object-after-bind/solution.md
> +따라서 `user.g()`를 실행하는 동안에도 기존 함수는 `this=null`로 호출됩니다.
```suggestion
따라서 `user.g()`를 실행했음에도 불구하고 기존 함수의 컨텍스트는 `null`이 되기 때문에 `null`이 출력됩니다.
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/4-function-property-after-bind/task.md
> +함수 프로퍼티 안에는 값이 있습니다. `바인드`를 한 후에 그 값을 바꿀 수 있을까요? 그렇다면 혹은 그렇지않는다면 그 이유는 무엇인가요?
```suggestion
함수 프로퍼티에 값을 하나 할당해봅시다. 이 함수에 `bind` 메서드를 적용하면 프로퍼티 값은 바뀔까요? 그렇다면 혹은 그렇지않다면 그 이유는 무엇일까요?
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/4-function-property-after-bind/task.md
> +# 바인드 이후 함수 프로퍼티
```suggestion
# bind를 적용한 함수의 프로퍼티
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/4-function-property-after-bind/task.md
> +alert( bound.test ); // 이 코드를 실행하면 어떤 결과가 나올까요? 그렇게 나온 이유가 무엇일까요?
```suggestion
alert( bound.test ); // 얼럿 창엔 어떤 값이 출력될까요? 값이 나온 이유는 무엇일까요?
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/4-function-property-after-bind/solution.md
> +`바인드`를 한 결과인 bound는 또 다른 객체입니다. bound는 `test` 프로퍼티를 갖고 있지 않습니다.
```suggestion
`bind`를 적용하면 또 다른 객체가 반환됩니다. 새로운 객체엔 `test` 프로퍼티가 없으므로 `undefined`가 출력됩니다.
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/5-question-use-bind/task.md
> +아래 코드에서 `askPassword()`를 실행하는 호출은 비밀번호를 먼저 확인하고 나서 그 결과에 따라 `user.loginOk·loginFail`를 호출해야 합니다.
```suggestion
아래 함수 `askPassword()`는 비밀번호를 먼저 확인하고 그 결과에 따라 `user.loginOk`나 `user.loginFail`을 호출해야 합니다.
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/5-question-use-bind/task.md
> +하지만 이 논리는 에러를 발생시킵니다. 왜일까요?
```suggestion
그런데 함수를 호출하면 에러가 발생합니다. 에러는 왜 발생했을까요?
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/5-question-use-bind/solution.md
> +에러는 `ask`가 함수 `loginOk·loginFail`를 객체 없이 가지기 때문에 발생합니다.
```suggestion
에러는 `ask`가 함수 `loginOk`, `loginFail`을 객체 없이 가지고 오기 때문에 발생합니다.
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/5-question-use-bind/solution.md
> +ask가 loginOk·loginFail를 호출할 때 loginOk·loginFail는 `this=undefined`라고 자연스레 가정합니다.
```suggestion
ask는 `loginOk`, `loginFail`을 호출할 때 `this=undefined`라고 자연스레 가정합니다.
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/5-question-use-bind/solution.md
> +컨텍스트에 `바인딩`을 해봅시다.
```suggestion
`bind` 함수를 사용해 컨텍스트를 고정시켜 봅시다.
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/5-question-use-bind/solution.md
문제도 번역해주세요.

프롬프트 창엔 '비밀번호를 입력해주세요.' 라고 해주시고,
결과 메시도 적절히 번역 부탁드립니다.

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/5-question-use-bind/solution.md
> +대체될 수 있는 해답은 아래와 같습니다.
```suggestion
이 외에도 다른 답이 있는데, 아래에서 확인 가능합니다.
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/5-question-use-bind/solution.md
> +위의 대체 해답 또한 대개 잘 동작하며 가독성도 좋습니다.
```suggestion
이렇게 화살표 함수를 사용하는 방법 또한 대개 잘 동작하며 가독성도 좋습니다.
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/5-question-use-bind/solution.md
> +다만 이 대체 해답은 `askPassword`가 호출*됐으나* 사용자가 프롬프트 대화상자에 값을 제출하고 `() => user.loginOk()`를 호출하기 *전*인 시점에 `user` 변수가 바뀔 수도 있는 좀 더 복잡한 상황에서는 신뢰성이 떨어집니다.
```suggestion
다만 이 방법은 `askPassword`가 호출*됐으나* 사용자가 프롬프트 대화상자에 값을 제출하고 `() => user.loginOk()`를 호출하기 *전*에 `user` 변수가 바뀌는 등의 복잡한 상황에서는 오작동할 가능성이 있습니다.
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/5-question-use-bind/task.md
> +# this 값이 undefined가 돼버린 함수 고치기
```suggestion
# this 값이 undefined인 함수 고치기
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/6-ask-partial/task.md
> +여기에서는 `user` 객체가 수정되었습니다. 이제 user는 두 함수 `loginOk·loginFail` 대신에 오직 하나의 함수 `user.login(true·false)`만을 가집니다.
```suggestion
여기서는 `user` 객체를 수정해 user가 `loginOk`, `loginFail` 대신에 오직 하나의 함수 `user.login(true·false)`만 가질 수 있게 해놓았습니다.
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/6-ask-partial/task.md
> +아래 코드에서 askPassword가 `user.login(true)`를 `ok`로, `user.login(false)`를 `fail`로 호출하려면 `askPassword`에 무엇을 넘겨주어야 할까요?
```suggestion
`user.login(true)`는 `ok`, `user.login(false)`은 `fail`을 호출하게 하려면 `askPassword`에 무엇을 넘겨줘야 할까요?
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/6-ask-partial/task.md
> +색칠된 라인의 물음표 부분을 수정해보세요.
```suggestion
색칠된 줄의 물음표 부분만 수정해야 합니다.
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/6-ask-partial/solution.md
> +1. 래퍼 함수와 화살표를 사용하여 간결하게 하세요.
```suggestion
1. 래퍼 함수나 화살표 함수를 사용하면 간결하게 원하는 기능을 구현할 수 있습니다.
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/6-ask-partial/solution.md
> +2. 혹은 `user.login`에서 컨텍스트로 `user`를 사용하고 올바른 첫 번째 인수를 가지는 partial 함수를 만드세요.
```suggestion
2. 컨텍스트가 `user`이면서 올바른 첫 번째 인수가 있는 부분 적용 함수를 만들면 원하는 기능을 구현할 수 있습니다.
```

2020-09-10 14:54 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/10-bind/6-ask-partial/solution.md
> +    이제 askPassword는 외부 변수인 `user`를 가져와서 이를 정상적으로 실행할 수 있습니다.
```suggestion
    이 방법을 사용하면 askPassword는 외부 변수에서 `user`를 가져오기 때문에 원하는 결과를 얻을 수 있습니다.
```

2020-09-10 17:46 UTC, rovin0805 commented
/done

2020-09-10 17:48 UTC, rovin0805 commented
bind는 영어 그대로 bind 라고 번역해주셨는데, 용어집에는 '바인드', binding 또한 '바인딩'이라고 명시되어있습니다. 
이부분은 영어 원문 그대로 번역하도록 용어집 수정란에 올려놓을까요?

2020-09-10 21:42 UTC, Violet-Bora-Lee commented
여기는 bind라는 메서드를 다루고있어서 번역을 안하는게 맞아요

코드는 번역을 안하고있습니다

2020-09-11 05:33 UTC, rovin0805 commented
앗 그렇군요! 참고하겠습니다..!

리뷰 토대로 다시 번역 수정하였고, 커밋도 하나로 합쳐놓았습니다.

처음 참여하는 기여인지라 열심히 한다고는 했는데도, 번역이 거의 다라고 해도 될 만큼 보라님 손을 다시 한번 거쳐서 다듬어져야 할 부분이 많네요 😖
그래도 이번 컨트리뷰톤과 멘토님 덕분에 정말 많은 것을 배워갑니다..! 😄

2020-09-12 02:08 UTC, Violet-Bora-Lee commented
'코드는 번역을 안한다'는 모범사례나 리드미 파일에 잘 명시가 안되있어서 혼돈을 드린것같아 송구스럽네요.
관련하여 이런 이슈가 만들어졌고, https://github.com/javascript-tutorial/ko.javascript.info/issues/762 곧 해결될 예정이니 참고부탁드려요.

'어떻게 하면 좋고, 그 근거는 무엇이다'라고 가이드 드리는 게 좋은데, 기여자가 많아지고 대회 기간이여서 리뷰할 양이 많아지다보니 suggestion만 많이 달아놓아서 저도 아쉽네요 ㅠㅠ

실제 (코드)리뷰는 절대 이렇게 하시면 안되고, 저도 이렇게 하면 안되는데.. 양해의 말씀을 드립니다.

고생 많으셨습니다! 감사합니다. 머지 진행할게요 👍

2020-09-12 02:08 UTC, merged