[1.6.9 call/apply] 첫 번째 과제&해답 번역
javascript-tutorial/ko.javascript.info pull request #729
Opened 2020-08-20 19:04 UTC by rovin0805

# Pull Request 체크리스트
## TODO
- [x] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [x] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [x]  [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [x] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [x] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [x] PR 하나엔 번역문 하나만 넣으셨나요?
- [x] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

2020-08-30 03:40 UTC, Violet-Bora-Lee requested changes
코멘트 확인후 수정부탁드립니다.

한글만 읽었을 때 독자가 이해할 수 있게 문장을 많이 다듬어주셔야해요.

2020-08-30 03:40 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/09-call-apply-decorators/01-spy-decorator/task.md
> +`calls` 프로퍼티에서 동작하기 위해 모든 호출을 저장하는 래퍼를 반환하는 데코레이터 `spy(func)`를 구현하세요.
영어 원문을 보지 않고, 이 한글 번역본만 보았을때 문제의 의도가 이해되지 않습니다.

2020-08-30 03:40 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/09-call-apply-decorators/01-spy-decorator/task.md
> +모든 호출은 배열의 인자로서 저장됩니다.
https://m.blog.naver.com/ojhnews/220840570533

이글 한번 읽읽어보시고

~의, ~로서 등의 불필요한 조사는 빼주세요.

2020-08-30 03:40 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/09-call-apply-decorators/01-spy-decorator/task.md
> +  alert( a + b ); // work는 임의의 함수 혹은 메서드입니다
완전한 문장의 끝엔 마침표를 찍어주세요.

2020-08-30 03:40 UTC, Violet-Bora-Lee commented on 1-js/06-advanced-functions/09-call-apply-decorators/01-spy-decorator/task.md
> +P.S.  스파이 데코레이터는 때때로 단위별 테스트에 유용합니다. 이 데코레이터의 고급 형태는 [Sinon.JS](http://sinonjs.org/) 라이브러리에 있는 `sinon.spy`입니다.
P.S. 뒤에 불필요한 공백이 들어가있습니다.

unit-testing은 `단위 테스팅`이라고 부릅니다. IT분야에서 통상적으로 사용되는 용어는 직접 번역하지마시고 리서치 후에 번역해주세요.

2020-08-31 17:16 UTC, rovin0805 commented
리뷰 참고하여 번역 수정하였습니다. 
특히, 'Create a decorator `spy(func)` that should return a wrapper that saves all calls to function in its `calls` property.' 
이 부분을 독자가 읽었을 때 문제 의도를 좀 더 이해하기 쉽도록 고쳐보았습니다.
이와 관련해서 영어 원문 또한 명확하게 바뀌면 좋을 것 같은데, 처음에 읽었을 때 저는 이해가 잘 안가더라구요ㅠ 모호한 감이 있는 것 같아서요..!

Create a decorator function<sup>A</sup> called `spy` that accepts a function<sup>B</sup> as an argument and returns a wrapper that saves all calls to that function<sup>B</sup> in its `calls` property.

예를 들면 이런 식으로 바뀌면 조금 더 이해하는데 쉬울 것 같은데 보라님 의견은 어떠신가요? (사실 저도 제 의견에 확신이 없어서 의견을 먼저 여쭤봅니다ㅠㅠ)

2020-09-03 13:17 UTC, rovin0805 commented
/done

2020-09-06 13:16 UTC, Violet-Bora-Lee commented
@rovin0805 
원문 작성자가 러시아인이셔서 조금 모호한 문장이 있긴한데요. 그럴때 저는 영어 원문에 수정 제의 PR을 보내고있습니다.
대명사가 모호한 경우에 특히 그렇게 하고있어요.

원문에 PR 보내주시고, 한글도 같이 작업 해봅시다 😄 

이 PR은 머지하지않고 기다려볼게요.

2020-09-09 19:09 UTC, rovin0805 commented
'Create a decorator spy(func) that should return a wrapper that saves all calls to function in its calls property.' 이 부분을 원문에 PR 보내지 않아도 될 것 같습니다..! 다시 검토해보니 제가 애초에 잘못 이해를 해서 틀린 번역을 했더라구요 😖 그래서 영어는 원래 있던대로 두어도 괜찮을 것 같아요 😅

2020-09-11 21:00 UTC, closed without merging

2020-09-11 21:22 UTC, rovin0805 commented
헉 브랜치에서 작업중 클로즈가 돼서 새로 pr 열었습니다..!
https://github.com/javascript-tutorial/ko.javascript.info/pull/856