[신규 번역]파트2 4.3이벤트 원문번역 #641
javascript-tutorial/ko.javascript.info pull request #741
Opened 2020-08-22 04:32 UTC by sowon-dev

# Pull Request 체크리스트
## TODO
- [x] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [x] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [x] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [x] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [x] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [x] PR 하나엔 번역문 하나만 넣으셨나요?
- [x] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

2020-08-30 03:52 UTC, Violet-Bora-Lee requested changes
매우매우 좋은 글입니다.

몇가지 코멘트 남겨보았습니다.

확인부탁드려요

2020-08-30 03:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +데이터 변경 시 실행되는 다양한 이벤트들이 있습니다.
`다양한`에 복수라는 정보가 담겨있기 때문에 `들`은 빼주셔도됩니다.

https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%96%B4%EC%83%89%ED%95%98%EC%A7%80-%EC%95%8A%EB%8B%A4%EB%A9%B4-%EB%8B%A8%EC%88%98%ED%98%95%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%A9%EC%8B%9C%EB%8B%A4

모범사례 확인해주세요

2020-08-30 03:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +```smart header="그 무엇도 `oninput`를 막을 수 없다"
마침표를 붙여주세요.

2020-08-30 03:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +이 이벤트들은 값 잘라내기/복사하기/붙여넣기 할 때 발생합니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%A7%9D%EC%9D%84-%EC%9D%B4%EB%A3%A8%EB%8A%94-%EB%8B%A8%EC%96%B4%EB%A5%BC-%EC%9D%B4%EC%9D%84-%EB%95%8C%EB%8A%94-%EA%B0%80%EC%9A%B4%EB%8E%83%EC%A0%90-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0


모범사례 확인부탁드립니다.

2020-08-30 03:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +이 이벤트들은 값 잘라내기/복사하기/붙여넣기 할 때 발생합니다.
아래쪽도 마찬가지로 수정부탁드려요

2020-08-30 03:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +이 이벤트들은 [ClipboardEvent](https://www.w3.org/TR/clipboard-apis/#clipboard-event-interfaces) 클래스 소속이며 복사하기/붙여넣기 한 데이터에 대한 접근을 제공합니다.
클래스 상속에선 '소속'이라는 표현을 잘 쓰지 않아요
`하위 클래스이다` 정도로 순화할수 있을것같습니다.

2020-08-30 03:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +클립보드에서 읽기/쓰기, 파일 등 다양한 데이터 타입에서 작동하는 메서드 목록 [명세서(specification)](https://www.w3.org/TR/clipboard-apis/#dfn-datatransfer)를 확인할 수 있습니다.
여기서는 명세서를 한영병기하지 않아도 될것같습니다.

튜토리얼 앞쪽에 명서세에 대한 글이 있기 때문입니다.

2020-08-31 15:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ko.javascript.info?pullRequest=741) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ko.javascript.info?pullRequest=741) before we can accept your contribution.<br/>**11** out of **12** committers have signed the CLA.<br/><br/>:white_check_mark: sowon-dev<br/>:white_check_mark: GreatLaboratory<br/>:white_check_mark: dazzel3<br/>:white_check_mark: moonkii<br/>:white_check_mark: LuiGee3471<br/>:white_check_mark: OMEGA-Y<br/>:white_check_mark: hannut91<br/>:white_check_mark: sanghyo95<br/>:white_check_mark: C17AN<br/>:white_check_mark: marco0332<br/>:white_check_mark: Violet-Bora-Lee<br/>:x: KimHunJin<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ko.javascript.info?pullRequest=741) it.</sub>

2020-08-31 16:32 UTC, sowon-dev commented
감사합니다! 말씀해주신대로하니 훨씬 자연스러워요! 보라님 최고최고
/done

2020-09-01 10:52 UTC, Violet-Bora-Lee requested changes
코멘트 남겨봤어요

event.clipboardData가 사용되고있는 예시는 해당 프로퍼티가 잘 이해가 안가서 공부좀 해보고 다시 코멘트 달아볼게요.

리베이스 연습 한번 더 한다고 생각하시고, 일단 커밋 하신 후 done 남겨주세요

2020-09-01 10:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +데이터 변경 시 실행되는 다양한 이벤트가 있습니다.
`Let's cover`를 넣어서 제안을 드려보자면 아래와 같습니다.

```suggestion
이번 챕터에선 데이터가 변경될 때 실행되는 다양한 이벤트에 대해 다루겠습니다.
```

2020-09-01 10:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +다만 텍스트 입력의 경우 포커스를 잃을 때 이벤트가 발생합니다.
'다만'은 예외상황을 나타낼 때 쓰는 부사인데 여기 넣으신 이유가 있을까요?

그리고 it 에 대한 번역이 빠져있어서 문장이 조금 어색하네요.

모범사례 확인부탁드립니다.

https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EB%8C%80%EB%AA%85%EC%82%AC%EB%8A%94-%EB%AA%85%ED%99%95%ED%95%98%EA%B2%8C

```suggestion
텍스트 입력 요소라면 포커스를 잃을 때 `change` 이벤트가 발생합니다.
```

2020-09-01 10:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +예를 들어 아래 텍스트 필드에 텍스트를 입력하는 동안에는 이벤트가 발생하지 않습니다. 하지만 버튼을 클릭하는 등 포커스를 다른 곳으로 옮기는 순간 `change` 이벤트가 발생합니다.
```suggestion
예시를 살펴봅시다. 아래 텍스트 입력 필드에 글자를 입력하는 동안엔 이벤트가 발생하지 않습니다. 하지만 버튼을 클릭하는 등의 동작을 해서 포커스를 다른 곳으로 옮기는 순간 `change` 이벤트가 발생합니다.
```

2020-09-01 10:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
>  <input type="button" value="Button">
```suggestion
<input type="button" value="버튼">
```

2020-09-01 10:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +또 다른 예로 `select`, `input type=checkbox/radio`는 선택상태가 변경된 직후에 이벤트가 발생합니다.
```suggestion
또 다른 요소를 기준으로 `change` 이벤트가 언제 발생하는지 살펴봅시다. `select`와 `input type=checkbox`, `input type=radio`는 선택 값이 변경된 직후에 이벤트가 발생합니다.
```

2020-09-01 10:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +  <option value="">선택하세요</option>
```suggestion
  <option value="">선택하세요.</option>
```

2020-09-01 10:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
>    <option value="1">Option 1</option>
```suggestion
  <option value="1">옵션 1</option>
```

2020-09-01 10:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
>  </select>
option도 번역해주세요

2020-09-01 10:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +키보드 이벤트와 달리 `input` 이벤트는 값이 변하면 발생합니다. 심지어 키보드 동작에 포함되지 않는 마우스로 텍스트를 붙여넣거나 음성인식으로 텍스트를 입력한 때에도 `input` 이벤트가 발생합니다.
```suggestion
키보드 이벤트와 달리 `input` 이벤트는 어떤 식으로든 값을 변경시킬 때 발생합니다. 마우스를 사용해 글자를 붙여넣거나 음성 인식 기능을 사용해 글자를 입력할 때같이 키보드가 아닌 다른 수단을 사용해 값을 변경시킬 때도 `input` 이벤트가 발생합니다.
```

2020-09-01 10:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +모든 수정사항마다 이벤트를 실행하고 싶다면 `<input>` 이벤트야말로 최고의 선택입니다.
```suggestion
수정이 일어날 때마다 이벤트를 실행하고 싶다면 `<input>` 이벤트가 가장 적절합니다.
```

2020-09-01 10:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +다만 `input` 이벤트는 입력 중에 방향키를 `key:⇦` `key:⇨` 사용하는 등 값이 변경되지 않는 키보드 입력이나 동작에는 반응하지 않습니다.
```suggestion
한편, `input` 이벤트는 `key:⇦`, `key:⇨` 키같이 값을 변경시키지 않는 키보드 입력이나 동작에는 반응하지 않습니다.
```

2020-09-01 10:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +```smart header="그 무엇도 `oninput`를 막을 수 없다."
```suggestion
```smart header="그 무엇도 `oninput`를 막을 수 없습니다."
```

2020-09-01 10:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +따라서 `event.preventDefault()`를 사용하기엔 이미 늦어버려서 써봤자 아무런 효과가 없습니다.
```suggestion
따라서 `event.preventDefault()`를 사용해 기본 동작을 막더라도 값이 수정되면 그 즉시 `input` 이벤트가 발생하기 때문에 `event.preventDefault()`를 써봤자 아무런 효과가 없습니다.
```

2020-09-01 10:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +이 이벤트들은 값 잘라내기·복사하기·붙여넣기 할 때 발생합니다.
```suggestion
`cut`, `copy`, `paste` 이벤트는 각각 값을 잘라내기·복사하기·붙여넣기 할 때 발생합니다.
```

2020-09-01 10:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +이 이벤트들은 [ClipboardEvent](https://www.w3.org/TR/clipboard-apis/#clipboard-event-interfaces) 클래스의 하위 클래스이며 복사하기·붙여넣기 한 데이터에 대한 접근을 제공합니다.
```suggestion
세 이벤트는 [ClipboardEvent](https://www.w3.org/TR/clipboard-apis/#clipboard-event-interfaces) 클래스의 하위 클래스이며 복사하거나 붙여넣기 한 데이터에 접근할 수 있도록 해줍니다.
```

2020-09-01 10:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +`event.preventDefault()`를 사용하여 동작을 중단하면 아무것도 복사·붙여넣기 되지 않습니다.
```suggestion
`input` 이벤트와는 달리 세 이벤트는 `event.preventDefault()`를 사용해 기본 동작을 막을 수 있습니다. 이렇게 하면 아무것도 복사·붙여넣기 할 수 없습니다.
```

2020-09-01 10:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +| `change` | 값에 변화가 있을 때 이벤트 발생 | 텍스트 입력의 경우 포커스를 잃을 때 실행 |
```suggestion
| `change` | 값이 변경될 때 이벤트 발생 | 텍스트 입력의 경우 포커스를 잃을 때 실행 |
```

2020-09-01 10:52 UTC, Violet-Bora-Lee commented on 2-ui/4-forms-controls/3-events-change-input/article.md
> +| `cut/copy/paste` | 잘라내기·복사하기·붙여넣기 동작시 이벤트 발생 | 이벤트실행 막기 가능, `event.clipboardData` 프로퍼티가 클립보드의 읽기·쓰기에 대한 접근을 허용 |
```suggestion
| `cut`, `copy, `paste` | 잘라내기·복사하기·붙여넣기 할 때 이벤트 발생 | 브라우저 기본 동작을 막아 이벤트 실행을 막을 수 있음. `event.clipboardData` 프로퍼티를 사용하면 클립보드에 저장된 데이터를 읽고 쓸 수 있음 |
```

2020-09-06 08:33 UTC, sowon-dev commented
/done

2020-09-06 13:11 UTC, Violet-Bora-Lee commented
LGTM!
감사합니다. 바로 머지 진행할게요 👍

2020-09-06 13:12 UTC, merged