[과제번역] Part2. 2.4 Browser default actions 과제 번역 #711
javascript-tutorial/ko.javascript.info pull request #746
Opened 2020-08-22 18:28 UTC by hysimok

# Pull Request 체크리스트
## TODO
- [x] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [x] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [x] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [x] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [x] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [x] PR 하나엔 번역문 하나만 넣으셨나요?
- [x] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

2020-08-25 12:33 UTC, Violet-Bora-Lee requested changes
리뷰 마쳤습니다.
큰 수정사항은 없는것 같습니다.

코멘트 보시고 확인 부탁드릴게요.

2020-08-25 12:33 UTC, Violet-Bora-Lee commented on 2-ui/2-events/04-default-browser-action/1-why-return-false-fails/task.md
> +# 왜 "return false"가 작동하지 않을까요?
따옴표 관련 모범사례를 확인해주세요.

https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EA%B0%95%EC%A1%B0%EC%9D%B8%EC%9A%A9%EC%8B%9C-%EC%82%AC%EC%9A%A9%EB%90%98%EB%8A%94-%EB%94%B0%EC%98%B4%ED%91%9C

2020-08-25 12:33 UTC, Violet-Bora-Lee commented on 2-ui/2-events/04-default-browser-action/1-why-return-false-fails/task.md
> +<a href="https://w3.org" onclick="handler()">브라우저가 w3.org로 이동합니다</a>
완전한 문장인데 마침표가 없습니다.

2020-08-25 12:33 UTC, Violet-Bora-Lee commented on 2-ui/2-events/04-default-browser-action/2-catch-link-navigation/task.md
> +`id="contents"`가 포함된 요소 안의 모든 링크가 사용자에게 정말 종료할 것인지 물어볼 수 있게 만들어 보세요. 그리고 사용자가 종료하길 원하지 않는다고 하면, 종료하지 않습니다.
질문이 모호합니다.

2020-08-25 12:33 UTC, Violet-Bora-Lee commented on 2-ui/2-events/04-default-browser-action/2-catch-link-navigation/task.md
> +세부사항
쌍점을 붙여주세요.

2020-08-25 12:33 UTC, Violet-Bora-Lee commented on 2-ui/2-events/04-default-browser-action/2-catch-link-navigation/task.md
> +- 요소 안의 HTML은 언제든지 로드되거나 동적으로 재생성될 수 있습니다. 그래서 모든 링크를 찾아 핸들러를 적용할 수는 없습니다. 이벤트 위임을 사용하세요.
마지막 문장 앞에 접속사를 넣어주시면 읽으시는 분들이 더 편할것같아요.

2020-08-25 12:33 UTC, Violet-Bora-Lee commented on 2-ui/2-events/04-default-browser-action/3-image-gallery/solution.md
> +해결 방법은 컨테이너에 핸들러를 할당해 클릭을 추적하는 것입니다. 클릭이 `<a>` 링크에서 발생했다면, `#largeImg`의 `src`를 썸네일의 `href`로 변경합니다.
컨테이너 보다는 '이벤트 핸들러를 달아놓은 최상위 요소'라는 의미를 넣어서 번역하는게 좋을것같아요.

이벤트 위임관련 글에서 '컨테이너'라고 번역하긴 했는데, 이슈 하나 올려주실수있으실까요?

컨테이너 보다는 다른 방향으로 번역할수있게요.

2020-08-25 12:33 UTC, Violet-Bora-Lee commented on 2-ui/2-events/04-default-browser-action/3-image-gallery/task.md
> +섬네일(Thumbnail)을 클릭하면 이미지가 바뀌는 이미지 갤러리를 만들어보세요.
thumbnail은 용어집에 등록부탁드립니다.

2020-08-25 12:33 UTC, Violet-Bora-Lee commented on 2-ui/2-events/04-default-browser-action/3-image-gallery/task.md
> +섬네일(Thumbnail)을 클릭하면 이미지가 바뀌는 이미지 갤러리를 만들어보세요.
대문자 t를 소문자로 바꿔주세요.

2020-08-31 16:32 UTC, hysimok commented on 2-ui/2-events/04-default-browser-action/3-image-gallery/solution.md
> +해결 방법은 컨테이너에 핸들러를 할당해 클릭을 추적하는 것입니다. 클릭이 `<a>` 링크에서 발생했다면, `#largeImg`의 `src`를 썸네일의 `href`로 변경합니다.
이슈 만들었습니다.
https://github.com/javascript-tutorial/ko.javascript.info/issues/820#issue-689335019

2020-08-31 16:32 UTC, hysimok commented
/done

2020-08-31 16:58 UTC, hysimok commented on 2-ui/2-events/04-default-browser-action/3-image-gallery/solution.md
> +해결 방법은 이벤트 핸들러를 할당할 수 있는 상위 요소에 핸들러를 할당해 클릭을 추적하는 것입니다. 클릭이 `<a>` 링크에서 발생했다면, `#largeImg`의 `src`를 섬네일의 `href`로 변경합니다.
@Violet-Bora-Lee 수정사항 적어주신 것 보고 이렇게 고쳐봤는데, 매끄러운지 잘 모르겠습니다. ㅠㅠ

2020-09-03 13:46 UTC, Violet-Bora-Lee requested changes
리뷰 남겨보았습니다.

2020-09-03 13:46 UTC, Violet-Bora-Lee commented on 2-ui/2-events/04-default-browser-action/2-catch-link-navigation/task.md
> +- 요소 안의 HTML은 언제든지 동적으로 로드되거나 재생성될 수 있습니다. 따라서 모든 링크를 찾아 핸들러를 적용할 수는 없습니다. 이럴 때 이벤트 위임을 사용하세요.
```suggestion
- 요소 안 HTML은 언제든지 동적으로 로드되거나 재생성될 수 있습니다. 따라서 모든 링크를 찾아 핸들러를 적용할 수 없습니다. 그러니 이벤트 위임을 사용해 답안을 작성해보세요.
```

2020-09-03 13:46 UTC, Violet-Bora-Lee commented on 2-ui/2-events/04-default-browser-action/2-catch-link-navigation/task.md
> +- 콘텐츠 안에 중첩된 태그가 있을 수도 있습니다. 링크 내부도 마찬가지로 `<a href=".."><i>...</i></a>` 이렇게 중첩된 태그가 존재할 수 있습니다.
```suggestion
- `id`가 `contents`인 요소 안에는 중첩 태그가 있을 수 있습니다. 링크 안에도 마찬가지로 `<a href=".."><i>...</i></a>` 이렇게 중첩 태그가 존재할 수 있습니다.
```

2020-09-03 13:46 UTC, Violet-Bora-Lee commented on 2-ui/2-events/04-default-browser-action/3-image-gallery/solution.md
> +해결 방법은 이벤트 핸들러를 할당할 수 있는 상위 요소에 핸들러를 할당해 클릭을 추적하는 것입니다. 클릭이 `<a>` 링크에서 발생했다면, `#largeImg`의 `src`를 섬네일의 `href`로 변경합니다.
```suggestion
상위 요소에 핸들러를 할당하면 어떤 이미지를 클릭했는지 추적할 수 있습니다. 사용자가 `<a>` 링크를 클릭한 경우, `#largeImg`의 `src` 값을 섬네일의 `href`로 변경하면 됩니다.
```

2020-09-08 04:53 UTC, hysimok commented
/done

2020-09-10 11:54 UTC, Violet-Bora-Lee requested changes

2020-09-10 11:54 UTC, Violet-Bora-Lee commented on 2-ui/2-events/04-default-browser-action/2-catch-link-navigation/solution.md
> +실제 세계에서는 물어보는 대신 서버에게 "logging" 요청을 보낼 수 있습니다. "logging" 요청은 방문자가 떠난 위치를 저장할 수 있게 합니다. 가능하다면 내용을 불러와서 페이지에 바로 보이게 할 수도 있습니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EA%B0%95%EC%A1%B0%EC%9D%B8%EC%9A%A9%EC%8B%9C-%EC%82%AC%EC%9A%A9%EB%90%98%EB%8A%94-%EB%94%B0%EC%98%B4%ED%91%9C

모범사례 확인부탁드립니다

2020-09-10 11:54 UTC, Violet-Bora-Lee commented on 2-ui/2-events/04-default-browser-action/2-catch-link-navigation/solution.md
> +해야할 일은 `contents.onclick`를 잡아낸 다음 사용자에게 물어보기 위해 `confirm`을 사용하는 것 뿐입니다. URL에 `link.href` 대신 `link.getAttribute('href')`를 사용하는 것이 좋은 아이디어가 될 수 있습니다. 자세한 사항은 샌드박스의 해답에서 확인해보세요.
전반적으로 퇴고 한번 부탁드릴게요.

2020-09-11 18:00 UTC, hysimok commented
/done

2020-09-12 02:03 UTC, Violet-Bora-Lee commented
커밋 하나로 합쳐주시면 머지 진행하겠습니다.
고생많으셨습니다!

2020-09-12 02:15 UTC, hysimok commented
/done 커밋 합치기 완료했습니다! 감사합니다.

2020-09-12 03:55 UTC, Violet-Bora-Lee commented
커밋 메시지 수정부탁드릴게요.
메시지만 보고 이 커밋에서 어떤 작업을 했는지 알수있도록 해주세요.

2020-09-12 05:22 UTC, hysimok commented
/done  커밋 메시지 한줄로 수정했습니다 !

2020-09-12 06:07 UTC, Violet-Bora-Lee commented
translate/2.2.4 task and solution <-- 이 커밋메시지를 보면 2.2.4가 무엇인지 찾아보아야합니다. 어떤 글인지 한눈에 볼수있게 해주세요. 다른 커밋 메시지들을 참고해주세요.

2020-09-12 10:48 UTC, hysimok commented
/done 아하, 제가 잘못이해했었네요 ㅠㅠ 수정완료했습니다.

2020-09-13 11:29 UTC, Violet-Bora-Lee commented
기여 감사합니다.
머지 진행할게요 👍

2020-09-13 11:29 UTC, merged