[번역]파트1 2.4변수와상수 미번역분 추가번역 #654
javascript-tutorial/ko.javascript.info pull request #751
Opened 2020-08-23 09:34 UTC by sowon-dev

# Pull Request 체크리스트
## TODO
- [x] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [x] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [x] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [x] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [x] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [x] PR 하나엔 번역문 하나만 넣으셨나요?
- [x] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

이슈번호 #654

2020-08-30 04:02 UTC, Violet-Bora-Lee requested changes
훌륭한 번역 퀄리티입니다.
몇가지 코멘트 달아보았는데 확인부탁드려요.

2020-08-30 04:02 UTC, Violet-Bora-Lee commented on 1-js/02-first-steps/04-variables/article.md
> +let message = "That"; // SyntaxError: 'message'를 이미 선언했습니다.
에러 메시지는 번역하지 않습니다.

리드미 파일 확인해주세요.

2020-08-30 04:02 UTC, Violet-Bora-Lee commented on 1-js/02-first-steps/04-variables/article.md
> +따라서 변수를 한 번 선언한 다음 `let`없이 변수를 사용하면 됩니다.
```suggestion
따라서 일단 변수가 선언되면 이 변수를 참조할 때는 `let`이 없어야 합니다.
```

이렇게 하면 어떨까요? 문장이 잘 이해가 안되서, 조금 풀어보았는데 의견부탁드려요.

2020-08-31 16:48 UTC, sowon-dev commented on 1-js/02-first-steps/04-variables/article.md
> +따라서 변수를 한 번 선언한 다음 `let`없이 변수를 사용하면 됩니다.
아 고민했던 부분인데 감사해요! 속이 다 시원하네요! 
변수 사용에 초점을 맞춰서 응용해보았어요.
아래 문장이 원문과 결을 같이하면서 자연스러운 것 같아요.

```
따라서 이미 선언된 변수를 참조할 때는 `let`없이 사용하면 됩니다.
```

하지만 번역 초점을 **변수 두 번 선언하기**에 둔다면 보라님 문장이 딱 들어맞는 것 같아요. 의견부탁드려요.

2020-09-03 12:40 UTC, Violet-Bora-Lee commented on 1-js/02-first-steps/04-variables/article.md
> +따라서 변수를 한 번 선언한 다음 `let`없이 변수를 사용하면 됩니다.
따라서 이미 선언된 변수를 참조할 때는 `let`없이 사용하면 됩니다. <-- 이 문장 좋습니다.
이걸로 가시죠 👍

2020-09-05 15:39 UTC, sowon-dev commented
/done

2020-09-06 13:24 UTC, Violet-Bora-Lee commented
충돌 해결 부탁드립니다.

2020-09-06 13:25 UTC, Violet-Bora-Lee commented
https://github.com/javascript-tutorial/ko.javascript.info/commit/734ac146b45f1c3980b77fc836f28ab274902c3d

다른분이 이렇게 해주셨네요!

2020-09-06 14:52 UTC, sowon-dev commented
네 동일한 부분을 번역한 다른 분의 pr이 먼저 머지되어서 이 pr은 닫도록 하겠습니다

2020-09-06 14:52 UTC, closed without merging