04Binary-03Blob 번역
javascript-tutorial/ko.javascript.info pull request #753
Opened 2020-08-23 10:56 UTC by ccppoo

# Pull Request 체크리스트
## TODO
- [x] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [x] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [x] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [x] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [x] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [x] PR 하나엔 번역문 하나만 넣으셨나요?
- [x] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

2020-08-30 04:03 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +`blobParts`로는 일련의 `Blob` 객체, 문자열, 그리고 `BufferSource`가 있습니다.
번역시 줄바꿈을 마음대로 하시면 안됩니다.

리드미 파일의 번역규칙 섹션 확인 후, 다시 작업부탁드려요

https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99

2020-08-30 04:04 UTC, Violet-Bora-Lee requested changes
재작업부탁드립니다.

리드미 파일과 위키문서 꼭 1회이상 정독후 작업해주세요.

https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EA%B0%95%EC%A1%B0%EC%9D%B8%EC%9A%A9%EC%8B%9C-%EC%82%AC%EC%9A%A9%EB%90%98%EB%8A%94-%EB%94%B0%EC%98%B4%ED%91%9C

2020-08-30 05:14 UTC, ccppoo commented on 4-binary/03-blob/article.md
> +`blobParts`로는 일련의 `Blob` 객체, 문자열, 그리고 `BufferSource`가 있습니다.
수정했습니다

2020-08-30 05:14 UTC, ccppoo commented
/done

2020-08-30 07:26 UTC, ccppoo commented
/done

2020-08-30 08:12 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +# 블롭 (Blob, Binary Large OBject)
https://github.com/javascript-tutorial/ko.javascript.info/issues/63

이 이슈 확인부탁드릴게요

2020-08-30 08:23 UTC, Violet-Bora-Lee requested changes
모범사례를 다시한번 읽으시고 작업부탁드립니다.

같은 사항이 계속 나오고 있어서 위쪽만 리뷰 하였습니다.

2020-08-30 08:23 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +`ArrayBuffer` 와  뷰(views)는 자바스크립트의 한 부분으로써 ECMA 표준입니다.
```suggestion
`ArrayBuffer` 와  뷰(view)는 자바스크립트의 한 부분으로써 ECMA 표준입니다.
```

2020-08-30 08:23 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +브라우저에는 뷰와 더불어 [File API](https://www.w3.org/TR/FileAPI/)에서 설명하고 있는 고차(higher-level) 객체가 존재합니다. 존재하는 여러 고차 객체 중 이 페이지에서는 `Blob`에 대해서 설명할 것입니다.
https://m.blog.naver.com/PostView.nhn?blogId=ojhnews&logNo=220840570533

이 글확인해보시고, `것`은 되도록이면 지양해주세요

2020-08-30 08:23 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +- **`blobParts`** 는 `Blob`/`BufferSource`/`String`으로 이루어진 배열입니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%A7%9D%EC%9D%84-%EC%9D%B4%EB%A3%A8%EB%8A%94-%EB%8B%A8%EC%96%B4%EB%A5%BC-%EC%9D%B4%EC%9D%84-%EB%95%8C%EB%8A%94-%EA%B0%80%EC%9A%B4%EB%8E%83%EC%A0%90-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

모범사례 확인 부탁드립니다.

2020-08-30 08:23 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +  - **`type`** -- `Blob`의 타입(대부분 MIME 타입)을 의미합니다. (예: `image/png`),
괄호 관련 모범사례 확인 부탁드립니다.

https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EA%B4%84%ED%98%B8-%EC%95%88%EC%9D%98-%EB%AC%B8%EC%9E%A5

2020-08-30 08:23 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +// 알아두세요! 첫 번째 인수는 배열(array) [...] 이어야 합니다
주술구조가 있는 문장이므로 마침표를 찍어주세요.

2020-08-30 08:23 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +// 타입이 지정된 배열(array)과 문자열로 Blob 생성하기
배열은 구지 원문을 병기표시하지 않아도 됩니다.

2020-08-30 08:23 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +let hello = new Uint8Array([72, 101, 108, 108, 111]); // 바이너리 형식의 "Hello"입니다(아스키코드 값)
마침표 찍어주시고, 문장안에 괄호를 넣고싶으시다면 모범사례확인해주세요.

2020-08-30 08:23 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +다음과 같이 `Blob` 객체를 슬라이스(slice) 함으로써 일부를 추출할 수 있습니다.
```suggestion
다음과 같이 `Blob` 객체에 slice 메서드를 적용해 일부를 추출할 수 있습니다.
```

2020-08-30 08:23 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +인수는 `array.slice` 메서드와 유사하며, 음수도 인수로 사용할 수 있습니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%89%BC%ED%91%9C%EB%A5%BC-%EB%AA%A8%EB%91%90-%EC%98%AE%EA%B8%B8-%ED%95%84%EC%9A%94%EB%8A%94-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4

모범사례 확인하시여 글 전반에서 사용되고 있는 쉼표 중 불필요한것들은 삭제해주세요.

2020-08-30 08:23 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +```smart header="`Blob` 객체는 불변입니다"
마침표 누락

2020-08-30 08:23 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +```
```suggestion
```
```

불필요한 공백이 들어가있습니다.

2020-08-30 08:23 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +Blob의 `타입` 속성 덕분에 `Blob` 객체를 다운로드/업로드 할 수 있으며, 네트워크 요청이 있을 때 자연스럽게 `타입`은 `Content-Type`으로 사용됩니다.
```suggestion
Blob의 `type` 프로퍼티 덕분에 `Blob` 객체를 다운로드·업로드 할 수 있으며, 네트워크 요청이 있을 때 자연스럽게 `type`은 `Content-Type`으로 사용됩니다.
```

내장 프로퍼티이므로 번역하지 않습니다.

속성과 프로퍼티에 대한 차이는 용어집을 확인해주세요.

2020-08-30 08:23 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +Blob은 URL과 같이 사용될 수 있어 `<a>`, `<img>`, 등 태그에서 컨텐츠를 볼 수 있습니다.
문장이 잘 이해가 되지 않는데요. 해당 문장을 보고 독자가 이 문장이 무엇을 설명하고 있는지 알 수 있도록 수정해주세요.

2020-08-30 08:23 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +간단한 예시를 통해서 알아볼까요? 링크를 클릭해서 `hello world`가 포함된 파일을 동적으로 생성된(dynamically-generated) `Blob`을 다운로드 할 수 있습니다.
문장 구조가 이상합니다.

2020-08-30 08:23 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +<!--다운로드 속성은 브라우저에게 네비게이팅 대신 다운로드를 강제합니다-->
```suggestion
<!--download 속성은 브라우저에게 네비게이팅 대신 다운로드를 강제합니다.-->
```

1. 내장 속성명은 번역하지 않습니다.
2. 네비게이팅도 번역해주세요

2020-08-30 08:23 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
>  <a download="hello.txt" href='#' id="link">Download</a>
Download도 번역해주세요

2020-08-30 08:23 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +위 예시 코드에서 `link.href`의 값은 다음과 같이 생겼습니다 :
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%8C%8D%EC%A0%90%EC%9D%80-%EA%B1%B0%EC%9D%98-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4

쌍점 모범사례 확인해주세요

2020-08-30 08:23 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +매핑된 메모리는 document를 언로드(unload)될 때 해제됩니다. 하지만, 웹 앱이 지속적해서 유지되는 경우(예 : SPA,singal-page-app) 메모리는 계속 해제되지 않습니다.
쌍점 앞뒤의 띄어쓰기에 관한 사항을 검색해보시고, 수정해주세요

2020-08-30 08:23 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +**그래서 `Blob`을 통해 URL을 만들면, 사용하지 않아도, 메모리를 계속 점유하고 있을 겁니다**
쉼표, 마침표 관련 수정부탁드립니다.

2020-08-30 10:03 UTC, ccppoo commented
/done

2020-08-31 13:48 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +`ArrayBuffer` 와  뷰(view)는 자바스크립트의 한 부분으로써 ECMA 표준입니다.
```suggestion
`ArrayBuffer`와 뷰(view)는 자바스크립트의 한 부분으로써 ECMA 표준입니다.
```

첫 문장붙터 띄어쓰기 오류가 발견되고 있습니다.

맞춤법 검사기를 돌리시지 않았다고 판단되어 리뷰는 하지않겠습니다.

맞춤법 검사기 돌리신 후 다시 리뷰요청해주세요.

2020-09-01 07:28 UTC, ccppoo commented
/done

2020-09-17 12:22 UTC, Violet-Bora-Lee requested changes
모범사례 적용 부탁드려요

2020-09-17 12:22 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +생성자 문법은 다음과 같습니다.
```suggestion
`Blob`의 생성자 문법은 다음과 같습니다.
```

the가 의미하는것을 추가번역해보았습니다.

https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EB%8C%80%EB%AA%85%EC%82%AC%EB%8A%94-%EB%AA%85%ED%99%95%ED%95%98%EA%B2%8C

2020-09-17 12:22 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +  - **`endings`** -- 현재 사용하고 있는 OS에 알맞은 EOL(end-of-line), 줄 바꿈 문자(`\r\n` 또는 `\n`)의 변경 여부를 의미합니다. 기본값으로는 `'transparent'`(아무것도 안 함)이며, `'native'` 옵션을 통해 자동으로 바꾸도록 할 수 있습니다.
```suggestion
  - **`endings`** -- 현재 사용하고 있는 OS에 알맞은 EOL(end-of-line), 줄 바꿈 문자(`\r\n` 또는 `\n`)의 변경 여부를 의미합니다. 기본값으로는 `'transparent'`(아무것도 안 함)이며, `'native'` 옵션을 사용해 자동으로 바꿀 수 있습니다.
```

https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%ED%94%BC%EB%8F%99%ED%98%95-%EB%AC%B8%EC%9E%A5%EC%97%90-%EC%A3%BC%EC%9D%98%ED%95%98%EC%84%B8%EC%9A%94

불필요한 피동 표현을 수정해보았습니다.

2020-09-17 12:22 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +// 타입이 지정된 배열과 문자열로 Blob 생성하기.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EB%AC%B8%EC%9E%A5%EC%9D%B4-%EB%AA%85%EC%82%AC%ED%98%95%EC%9C%BC%EB%A1%9C-%EB%81%9D%EB%82%A0-%EB%95%8C%EB%8A%94-%EB%A7%88%EC%B9%A8%ED%91%9C%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4

모범사례 확인해주세요

2020-09-17 12:22 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +`Blob`의 데이터를 수정할 수 없지만, `Blob`을 필요한 부분을 슬라이스를 한 뒤, 새로운 `Blob` 객체를 따로 만든다거나, 또 다른 `Blob`에 추가할 수 있습니다.
```suggestion
`Blob` 안 데이터를 직접 수정할 수 없습니다. 대신 필요한 데이터를 잘라 새로운 `Blob` 객체를 만들거나 다른 `Blob`에 추가할 순 있습니다.
```
m.blog.naver.com/ojhnews/220840570533

https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%89%BC%ED%91%9C%EB%A5%BC-%EB%AA%A8%EB%91%90-%EC%98%AE%EA%B8%B8-%ED%95%84%EC%9A%94%EB%8A%94-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4

2020-09-17 12:22 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +이런 특징은 자바스크립트의 문자열과 유사합니다. 문자열의 문자를 수정할 수 없지만, 수정된 문자열을 새로 만들 수 있듯이 말이죠.
character 번역은 용어집을 참고해서 수정해주세요

2020-09-17 12:22 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +HTML에서 `<a>`, `<img>`, 등 태그에 URL을 통해 콘텐츠를 사용할 수 있듯이, Blob 객체도 사용할 수 있습니다.
이 문장 퇴고 다시 부탁드려도될까요? 잘 안읽혀서요

2020-09-17 12:22 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +Blob의 `type` 프로퍼티 덕분에 `Blob` 객체를 다운로드·업로드 할 수 있으며, 네트워크 요청이 있을 때 자연스럽게 `type`은 `Content-Type`으로 사용됩니다.
이문장도 퇴고 한번 더 부탁드립니다.

2020-09-17 12:22 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +<!-- 다운로드 속성은 브라우저에게 네비게이팅 대신 다운로드를 강제합니다 -->
문장이므로 끝에 마침표 찍어주세요

2020-09-17 12:22 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +생성된 URL(그리고 생성된 링크를 포함해서)은 현재 열린 HTML document에서만 유효합니다. 그리고 URL을 필요로하는 `<img>`, `<a>`, 등 다른 태그에서도 `Blob`을 참조하는 것이 가능합니다.
document 번역해주세요

2020-09-17 12:22 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +매핑된 Blob 객체 메모리는 document를 언로드(unload)될 때 해제됩니다. 하지만 웹 앱이 계속 유지되는 경우, 메모리는 해제되지 않습니다.
blob을 백틱으로 감싸주세요

app은 애플리케이션으로 번역해주세요(용어집 참고)

2020-09-17 12:22 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +**`Blob`을 이용한 URL을 만들면, 더는 사용하지 않음에도 불구하고 Blob 객체는 메모리를 계속 점유하고 있을 겁니다.**
```suggestion
**`Blob`을 이용한 URL을 만들면, 더는 사용하지 않음에도 불구하고 Blob 객체는 메모리를 계속 점유하고 있을 겁니다.**
```
더는 사용하지 않는게 blob인지, url인지 명시해주세요

2020-09-17 12:22 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +이와 달리, 위에서 다룬 실행 가능한 첫 번째 예시(HTML)의 경우, `URL.revokeObjectURL(link.href)`를 호출하지 않았습니다. 호출한다면, 매핑이 제거됨으로써 아직 HTML 상에 존재하는 URL 링크가 작동하지 않기 때문입니다.
쉼표 관련 모범사례를 전반적으로 다시 적용해주세요.

2020-09-17 12:22 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +다음은 base64를 통해 Blob을 다운로드하는 데모입니다:
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%8C%8D%EC%A0%90%EC%9D%80-%EA%B1%B0%EC%9D%98-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4

2020-09-17 12:22 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +이미지 연산은 HTML의 `<canvas>` 요소를 통해 완성됩니다:
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%8C%8D%EC%A0%90%EC%9D%80-%EA%B1%B0%EC%9D%98-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4

2020-09-17 12:22 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +다음 예시는 Blob을 만들기 전에 단순히 이미지를 복사한 것입니다. Blob이 아니어도 canvas에서 이미지 수정·변환이 가능합니다.
http://m.blog.naver.com/ojhnews/220840570533

글 한번 읽어보시고, 전체적으로 적용부탁드립니다

2020-09-17 12:22 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +  // blob 준비 완료!, 다운로드합시다
쉼표 없어도됨
마침표 누락

2020-09-17 12:22 UTC, Violet-Bora-Lee commented on 4-binary/03-blob/article.md
> +`async/await` 방식을 사용하는 경우:
쌍점 모범사례 확인

2020-09-25 06:37 UTC, closed without merging