[과제 번역] - 문서 수정하기 #689
javascript-tutorial/ko.javascript.info pull request #758
Opened 2020-08-24 15:30 UTC by C17AN

# Pull Request 체크리스트
## TODO
- [✅] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [✅] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [✅] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [✅] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [✅] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [✅] PR 하나엔 번역문 하나만 넣으셨나요?
- [✅] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

---

과제 분량이 생각보다 많아서 먼저 절반 분량 리뷰를 요청드립니다! :)

- 맞춤법 검사 중 "~방법이 구체적으로 정해져 있으므로" 라는 부분을 "있음으로" 고쳐야 한다고 나왔는데, "까닭이나 근거를 나타낼 때" 는 "있으므로" 를 사용하는 것이 옳다는 [국립국어원 글](https://korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=180645&pageIndex=1) 을 참고하여 고치지 않았습니다!

회사일이 바빠도 행복한 하루 되시길 바라겠습니다!! 😆

2020-08-30 05:58 UTC, Violet-Bora-Lee requested changes
정말 긴 작업이었네요...
저도 과제가 너무 많아서 손대지 못하고있었는데 이렇게 기여해주셔서 감사합니다.

코멘트 달아보았습니다.
보시고 의견이 있으시면 다시 코멘트 달아주세요.

2020-08-30 05:58 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/1-createtextnode-vs-innerhtml/task.md
> +빈 DOM 요소 `elem` 과 `text`라는 문자열이 있습니다.
```suggestion
빈 DOM 요소 `elem`과 `text`라는 문자열이 있습니다.
```

2020-08-30 05:58 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.md
![image](https://user-images.githubusercontent.com/6451384/91652213-e0de0d00-eacf-11ea-9ccb-34470c2cff8c.png)

pr올리고 난후엔 diff 체크 부탁드립니다.

2020-08-30 05:58 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.md
> +`update()` 의 호출은 `clockStart()` 에서뿐만 아니라 `(*)` 표시된 곳에서도 이루어집니다. 그렇지 않으면 사용자들은 `setInterval`이 실행되기 전까지 내용이 없는 시계를 봐야 하기 때문입니다.
```suggestion
`update()`는 `clockStart()` 에서뿐만 아니라 `(*)` 표시된 줄에서도 호출됩니다. 양쪽 모두에서 `update()`를 호출하지 않으면 `setInterval`이 실행되기 전까지 사용자는 아무런 내용이 없는 시계를 봐야 하기 때문입니다.
```

2020-08-30 05:58 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.view/index.html
> +      update(); // <--  setInterval의 첫 번째 실행 전까지 기다릴 필요 없이 시작합니다
```suggestion
      update(); // <--  첫 번째 setInterval이 실행되기 전까지 기다릴 필요 없이 시작합니다.
```

2020-08-30 05:58 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.view/index.html
> +  <!-- 이 버튼을 클릭하면 clockStart() 함수가 수행됩니다 -->
주술구조가 있는 문장은 마침표를 찍어주세요.

(여러 곳에서 이런 패턴이 발견되는데, 코멘트는 이제 남기지 않을게요.)

2020-08-30 05:58 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/10-clock-setinterval/task.md
> +다음과 같이 색칠된 시계를 만들어 보세요.
![image](https://user-images.githubusercontent.com/6451384/91652277-83968b80-ead0-11ea-84ad-24e92fa25775.png)

diff 체크 부탁드립니다.

2020-08-30 05:58 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/12-sort-table/solution.md
> +꼼수처럼 보일지도 모르겠지만, 해답은 간단합니다. 구체적인 설명은 아래에 적어 두었습니다.
쉼표 관련 모범사례 확인 부탁드립니다.

https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%89%BC%ED%91%9C%EB%A5%BC-%EB%AA%A8%EB%91%90-%EC%98%AE%EA%B8%B8-%ED%95%84%EC%9A%94%EB%8A%94-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4

2020-08-30 05:58 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/12-sort-table/solution.md
> +행에 해당하는 요소들을 지울 필요 없이 "재삽입" 하면, 기존 위치를 저절로 떠나게 됩니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EA%B0%95%EC%A1%B0%EC%9D%B8%EC%9A%A9%EC%8B%9C-%EC%82%AC%EC%9A%A9%EB%90%98%EB%8A%94-%EB%94%B0%EC%98%B4%ED%91%9C

따옴표 모범사례 확인 부탁드립니다.

2020-08-30 05:58 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/12-sort-table/task.md
> +여기 표가 하나 있습니다.
![image](https://user-images.githubusercontent.com/6451384/91652291-c8222700-ead0-11ea-8d87-bfeadd6d1b95.png)

2020-08-30 05:58 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/4-clear-elem/solution.md
> +`remove()` 는 `elem.childNodes`을 변화시키기 때문에 반복문을 실행할 때마다 `0` 번째 인덱스부터 시작해야만 합니다. 그러나 `i` 는 계속해서 증가하므로, 결국 일부 원소들을 지나치게 됩니다.
```suggestion
`remove()`는 `elem.childNodes`을 변화시키기 때문에 반복문을 실행할 때마다 `0` 번째 인덱스부터 시작해야만 합니다. 그러나 `i` 는 계속해서 증가하므로, 결국 일부 원소들을 지나치게 됩니다.
```

2020-08-30 05:58 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/5-why-aaa/task.md
> +# 왜 "aaa" 가 남아 있을까요
따옴표관련 모범사례 확인해주세요

2020-08-30 05:58 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/7-create-object-tree/source.view/index.html
![image](https://user-images.githubusercontent.com/6451384/91652304-f4d63e80-ead0-11ea-81b5-76774c47c4bf.png)

불필요한 수정이 들어가있습니다.

2020-08-30 05:58 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/9-calendar-table/solution.view/index.html
> +      let mon = month - 1; // 자바스크립트의 월은 1..12가 아닌 0..11입니다
```suggestion
      let mon = month - 1; // 자바스크립트에선 월을 1월~12월이 아닌 0월~11월로 취급합니다.
```

2020-09-02 07:27 UTC, C17AN commented on 2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.md
> +`update()` 의 호출은 `clockStart()` 에서뿐만 아니라 `(*)` 표시된 곳에서도 이루어집니다. 그렇지 않으면 사용자들은 `setInterval`이 실행되기 전까지 내용이 없는 시계를 봐야 하기 때문입니다.
이부분 코멘트는... 진짜 아름답네요..!

2020-09-02 10:36 UTC, C17AN commented
우선 완전한 문장에 온점 X, 큰따옴표 사용 문제는 모두 고쳤습니다!
줄바뀜이 맞지 않던 부분 및 일부 남아있던 영어 원문 역시 수정하였으며, 번거로우시더라도 한번 더 읽어주시면 감사드리겠습니다!

이런 글 수십개를 몇 번씩 봐야 한다니 리뷰도 보통 힘든게 아닐 것 같네요! 🤣
바쁜 시간을 내어 리뷰해주셔서 감사드리며, 내일도 행복한 하루 보내시길 바라겠습니다!

2020-09-02 10:36 UTC, C17AN commented
/done

2020-09-10 11:23 UTC, Violet-Bora-Lee requested changes
반정도 리뷰 마쳤는데요,
모범사례에 나와있는 내용들이 자꾸 중복되어 이정도로 1차 리뷰는 마무리하려합니다.
모범사례 다시 읽어주시고, 퇴고 부탁드립니다.

2020-09-10 11:23 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/1-createtextnode-vs-innerhtml/solution.md
> +정답: **1 and 3**.
and는 왜 번역을 안하신건가요?

2020-09-10 11:23 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.md
> +먼저 HTML/CSS를 만들어 줍니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%A7%9D%EC%9D%84-%EC%9D%B4%EB%A3%A8%EB%8A%94-%EB%8B%A8%EC%96%B4%EB%A5%BC-%EC%9D%B4%EC%9D%84-%EB%95%8C%EB%8A%94-%EA%B0%80%EC%9A%B4%EB%8E%83%EC%A0%90-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

2020-09-10 11:23 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.md
> +`(*)` 표시된 줄에서는 현재 날짜를 검사합니다. `setInterval`을 사용해 호출하면 지연이 생길 수 있기 때문에 신뢰성이 떨어집니다.
```suggestion
`(*)`로 표시한 줄에서는 현재 날짜를 확인합니다. `setInterval`을 사용해 호출하면 지연이 생길 수 있기 때문에 신뢰성이 떨어집니다.
```

2020-09-10 11:23 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.md
> +`update()`는 `clockStart()` 에서뿐만 아니라 `(*)` 표시된 줄에서도 호출됩니다. 양쪽 모두에서 `update()`를 호출하지 않으면 `setInterval`이 실행되기 전까지 사용자는 아무런 내용이 없는 시계를 봐야 하기 때문입니다.
```suggestion
`update()`는 `clockStart()` 에서뿐만 아니라 `(*)`로 표시한 줄에서도 호출됩니다. 양쪽 모두에서 `update()`를 호출하지 않으면 `setInterval`이 실행되기 전까지 사용자는 아무런 내용이 없는 시계를 봐야 하기 때문입니다.
```

~된은 불필요한 피동표현입니다. https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%ED%94%BC%EB%8F%99%ED%98%95-%EB%AC%B8%EC%9E%A5%EC%97%90-%EC%A3%BC%EC%9D%98%ED%95%98%EC%84%B8%EC%9A%94

2020-09-10 11:23 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.view/index.html
> +  <!-- 이 버튼을 클릭하면 clockStart() 함수가 수행됩니다. -->
```suggestion
  <!-- 이 버튼을 클릭하면 clockStart() 함수가 호출됩니다. -->
```

2020-09-10 11:23 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.view/index.html
> +  <!-- 이 버튼을 클릭하면 clockStop() 함수가 수행됩니다. -->
'함수가 수행된다'라는 표현은 잘 안쓰는것같아요

2020-09-10 11:23 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/10-clock-setinterval/source.view/index.html
> +  <!-- 이 버튼을 클릭하면 clockStop() 함수가 수행됩니다. -->
'수행' 고쳐주세요

2020-09-10 11:23 UTC, Violet-Bora-Lee commented on 2-ui/1-document/07-modifying-document/10-clock-setinterval/task.md
> +# setInterval을 사용한 색칠된 시계
```suggestion
# setInterval을 사용한 색칠된 시계
```
'색칠된 시계'라는 표현을 살다가 들어본, 들어볼 일이 있을까요...
직역해서 이렇게 번역하셨다는것은 이해가지만 최대한 한글처럼 풀어주세요

2020-10-11 16:41 UTC, C17AN commented
/done

2020-12-05 04:38 UTC, Violet-Bora-Lee commented
기여해주셔서 감사합니다!
머지 진행할게요 👍 
너무 늦었네요..ㅠㅠ
죄송하고 감사합니다 👏 👏 👏 👏

2020-12-05 04:38 UTC, merged