[Date 객체와 날짜] - 미번역분 번역 #759
javascript-tutorial/ko.javascript.info pull request #760
Opened 2020-08-24 16:24 UTC by C17AN

# Pull Request 체크리스트
## TODO
- [✅] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [✅] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [✅] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [✅] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [✅] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [✅] PR 하나엔 번역문 하나만 넣으셨나요?
- [✅] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

---

#759번 이슈 PR 제출합니다!

[번역 전]
Dates before 01.01.1970 have negative timestamps, e.g.:

[번역 후]
1970년 1월 1일 이전의 날짜는 음수 값의 타임스탬프를 가집니다. 예시:

2020-08-30 05:59 UTC, Violet-Bora-Lee commented on 1-js/05-data-types/11-date/article.md
> +    1970년 1월 1일 이전의 날짜는 음수 값의 타임스탬프를 가집니다. 예시:
```suggestion
    1970년 1월 1일 이전의 날짜는 음수 값의 타임스탬프를 가집니다. 예시를 살펴봅시다.
```

2020-08-30 06:00 UTC, Violet-Bora-Lee commented on 1-js/05-data-types/11-date/article.md
> +    1970년 1월 1일 이전의 날짜는 음수 값의 타임스탬프를 가집니다. 예시:
이렇게 자연스럽게 이어주는게 좋을것같습니다.

2020-08-30 06:00 UTC, Violet-Bora-Lee requested changes
제안 하나 드려봅니다.

2020-09-02 06:57 UTC, C17AN commented on 1-js/05-data-types/11-date/article.md
> +    1970년 1월 1일 이전의 날짜는 음수 값의 타임스탬프를 가집니다. 예시:
오! 그럼 혹시 이렇게 잇는건 어떨까요?

-> "1970년 1월 1일 이전의 날짜는 음수 값의 타임스탬프를 가지는데, 예시를 통해 살펴봅시다."

약간 군살이 붙는 느낌일까요?!

2020-09-02 10:45 UTC, C17AN commented
우선 "1970년 1월 1일 이전의 날짜는 음수 값의 타임스탬프를 가지는데, 예시를 통해 살펴봅시다." 로 수정 후 커밋한 상태입니다!

혹시 문장이 과하다 싶으면 원래 제안해주신 문장으로 다시 고쳐서 제출할게요!! 😄

2020-09-02 10:46 UTC, C17AN commented
/done

2020-09-10 11:15 UTC, Violet-Bora-Lee commented on 1-js/05-data-types/11-date/article.md
> +    1970년 1월 1일 이전의 날짜는 음수 값의 타임스탬프를 가집니다. 예시:
http://m.blog.naver.com/ojhnews/220840570533

'의'가 꼭 필요한건가요?

2020-09-10 11:15 UTC, Violet-Bora-Lee commented on 1-js/05-data-types/11-date/article.md
> +    1970년 1월 1일 이전의 날짜는 음수 값의 타임스탬프를 가집니다. 예시:
1970년 1월 1일 이전 날짜에 해당하는 타임스탬프 값은 음수입니다. 예시를 살펴봅시다.

이렇게 수정해볼수있을것같은데, 앞 뒤문장을 읽어보지 않아서 적절히 수정해주세요

2020-09-10 11:16 UTC, Violet-Bora-Lee commented
http://m.blog.naver.com/ojhnews/220840570533

'의'가 꼭 필요한건가요?

1970년 1월 1일 이전 날짜에 해당하는 타임스탬프 값은 음수입니다. 예시를 살펴봅시다.

이렇게 수정해볼수있을것같은데, 앞 뒤문장을 읽어보지 않아서 적절히 수정해주세요

2020-09-12 02:11 UTC, C17AN commented
/done

2020-09-13 11:30 UTC, Violet-Bora-Lee commented
감사합니다 
머지 진행할게요 👍

2020-09-13 11:30 UTC, merged