[번역] Part1 5.6 iterable 객체 누락된 부분 번역 #756
javascript-tutorial/ko.javascript.info pull request #776
Opened 2020-08-27 07:27 UTC by OMEGA-Y

# Pull Request 체크리스트
## TODO
- [ ] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [ ] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [ ] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [ ] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [ ] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [ ] PR 하나엔 번역문 하나만 넣으셨나요?
- [ ] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

2020-08-30 06:27 UTC, Violet-Bora-Lee commented on 1-js/05-data-types/06-iterable/article.md
> +`Array.from`은 추가적으로 사용할 수 있는 함수 'mapping'을 제공합니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%ED%95%A8%EC%88%98

이 모범사례에서 아래쪽에 해당하는 경우인것같은데 (`매핑` 함수) 어떻게 생각하시나요?

2020-08-30 06:27 UTC, Violet-Bora-Lee reviewed
의견부탁드립니다.

2020-08-30 07:46 UTC, OMEGA-Y commented
저도 번역할 때 모범사례를 읽어봤었는데요! 

**특정 범주에 속하는 함수를 지칭할 땐 위 규칙을 지키지 않아도 됩니다.**에서 특정 범주가 어떤 것을 구체적으로 의미하는지 모르겠더라고요ㅠㅠ

2020-08-30 07:48 UTC, OMEGA-Y commented on 1-js/05-data-types/06-iterable/article.md
> +`Array.from`은 추가적으로 사용할 수 있는 함수 'mapping'을 제공합니다.
저도 번역할 때 모범사례를 읽어봤었는데요! 

'특정 범주에 속하는 함수를 지칭할 땐 위 규칙을 지키지 않아도 됩니다.'에서 특정 범주가 어떤 것을 구체적으로 의미하는지 모르겠더라고요ㅠㅠ

2020-08-30 08:11 UTC, Violet-Bora-Lee commented on 1-js/05-data-types/06-iterable/article.md
> +`Array.from`은 추가적으로 사용할 수 있는 함수 'mapping'을 제공합니다.
음.. 커스텀 함수의 경우가 위쪽 사례이고, 내장 함수같은 경우는 아래쪽 (특벙 범주에 속하는 함수)라고 생각하였는데요, 어떻게 위키를 업데이트하는게 좋을까요

2020-08-30 11:37 UTC, OMEGA-Y commented on 1-js/05-data-types/06-iterable/article.md
> +`Array.from`은 추가적으로 사용할 수 있는 함수 'mapping'을 제공합니다.
특정 범주에 속하는 함수가 내장 함수 말고 또 어떤게 있을까요??

위키에서 `~ 본 튜토리얼에선 함수 앞에 붙이기로 결정하였습니다.` 뒤에 

만약 내장 함수만 있다면,
 `단, 내장 함수의 경우 위 규칙을 지키지 않아도 됩니다.` 이런 식으로 특정 범주보다는 명확하게 내장 함수라고 표기하는게 좋을 것 같습니다.

만약 내장 함수 외에 또 있다면,
 `단, 특정 범주에 속하는 함수(ex. 내장함수, ~함수 등)의 경우 위 규칙을 지키지 않아도 됩니다.` 이런 식으로 특정 범주에 해당하는 예시를 괄호 안에 몇 개 열거해 놓으면 기존보다 이해하기 더 수월할 것 같습니다.

+ 위키에 적혀 있는 `다만 특정 범주에 속하는 함수를 지칭할 땐 위 규칙을 지키지 않아도 됩니다.`를 읽으면,
이 경우에는 함수 이름을 `함수` 앞에 붙이든 뒤에 붙이든 다 괜찮다는 말 같습니다. 그래서 번역하다가 특정 범주에 속하는지 잘 모르겠을 때는 그냥 앞에 붙여야겠다는 생각을 했습니다..!

2020-08-30 13:16 UTC, Violet-Bora-Lee commented on 1-js/05-data-types/06-iterable/article.md
> +`Array.from`은 추가적으로 사용할 수 있는 함수 'mapping'을 제공합니다.
정리해주신 내용 좋네요 ㅎㅎ 

번역해주신 사례에서 매개변수로 넘겨지는 `매핑 함수`도 저는 규칙을 지키지 않는 사례라고 생각했는데요. 따라서 두 번째 제안주신 내용으로 위키를 업데이트하는것이 좋아보입니다.

위키 업데이트 부탁드려도될까요?

2020-08-31 04:31 UTC, OMEGA-Y commented on 1-js/05-data-types/06-iterable/article.md
> +`Array.from`은 추가적으로 사용할 수 있는 함수 'mapping'을 제공합니다.
네 해보겠습니다!

2020-08-31 04:45 UTC, OMEGA-Y commented on 1-js/05-data-types/06-iterable/article.md
> +`Array.from`은 추가적으로 사용할 수 있는 함수 'mapping'을 제공합니다.
위키 업데이트하고 commit 수정했습니다 :)

2020-08-31 13:39 UTC, Violet-Bora-Lee requested changes
제가 조금 더 문장을 다듬어보았는데요,
지금도 이미 잘 해주셔서 큰 문제는 없는데
상세히 풀어주는 식으로 수정을 쬐끔 해보았습니다.

괜찮다고 생각하시면 반영해주시고, 아니라면 완료 코멘트 남겨주세요

2020-08-31 13:39 UTC, Violet-Bora-Lee commented on 1-js/05-data-types/06-iterable/article.md
> +`(*)`로 표시한 줄에 있는 `Array.from`은 객체를 받아 이터러블이나 유사 배열인지 조사합니다. 이터러블이나 유사 배열인 경우 새로운 배열을 만들어 객체의 모든 요소를 배열로 복사합니다.
```suggestion
`(*)`로 표시한 줄에 있는 `Array.from`은 객체를 받아 이터러블이나 유사 배열인지 조사합니다. 넘겨 받은 인수가 이터러블이나 유사 배열인 경우, 새로운 배열을 만들고 객체의 모든 요소를 새롭게 만든 배열로 복사합니다.
```

2020-08-31 13:39 UTC, Violet-Bora-Lee commented on 1-js/05-data-types/06-iterable/article.md
> +`(*)`로 표시한 줄에 있는 `Array.from`은 객체를 받아 이터러블이나 유사 배열인지 조사합니다. 이터러블이나 유사 배열인 경우 새로운 배열을 만들어 객체의 모든 요소를 배열로 복사합니다.
대명사를 좀 더 풀어써보았습니다.

2020-08-31 13:39 UTC, Violet-Bora-Lee commented on 1-js/05-data-types/06-iterable/article.md
> +`Array.from`은 추가적으로 사용할 수 있는 'mapping' 함수를 제공합니다.
```suggestion
`Array.from`엔 '매핑(mapping)' 함수를 선택적으로 넘겨줄 수 있습니다.
```

2020-08-31 13:39 UTC, Violet-Bora-Lee commented on 1-js/05-data-types/06-iterable/article.md
> +두 번째 인수 `mapFn`은 새로운 배열에 `obj`의 요소를 추가하기 전에 각 요소에 적용할 수 있는 함수입니다. 각 요소에 `mapFn`을 적용하여 값이 반환되면 이 값을 새로운 배열에 추가하게 됩니다. `thisArg`는 각 요소에 대해 `this`를 설정할 수 있도록 합니다.
```suggestion
`mapFn`을 두 번째 인수로 넘겨주면 새로운 배열에 `obj`의 요소를 추가하기 전에 각 요소를 대상으로 `mapFn`을 적용할 수 있습니다. 새로운 배열엔 `mapFn`을 적용하고 반환된 값이 추가됩니다. 세 번째 인수 `thisArg`는 각 요소의 `this`를 지정할 수 있도록 해줍니다.
```

2020-08-31 13:51 UTC, OMEGA-Y commented
크으... 다듬어주신 문장 모두 좋은 것 같습니다!
번역하는 방법 많이 배워갑니다!

2020-08-31 13:56 UTC, Violet-Bora-Lee commented
늦은시간인데.. ㅎㅎ 이제 어서 마무리하고 주무세요.
기여해주셔서 감사드립니다.
바로 머지 진행할게요

2020-08-31 13:56 UTC, merged