MutationObserver 문법 번역
javascript-tutorial/ko.javascript.info pull request #782
Opened 2020-08-27 12:30 UTC by kyujonglee

mutation을 변경, 변화로 번역할 것인지 그냥 둘 것인지에 대한 합의가 필요함
mutationObserver와 관련된 용어들에 대한 번역을 어떻게 할 것인지 이야기가 필요함

# Pull Request 체크리스트
## TODO
- [x] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [x] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [x] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [x] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [x] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [x] PR 하나엔 번역문 하나만 넣으셨나요?
- [x] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

2020-08-31 13:54 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +먼저 문법을 살펴보고 뒤이어 실무의 예제를 살펴보면서 mutationObserver가 얼마나 유용한지 알아보겠습니다.
https://m.blog.naver.com/ojhnews/220840570533

이 글 한번 확인해주세요

2020-08-31 13:54 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +- `characterData` -- `node.data`(텍스트 내용)을 관찰할지에 대한 여부,
끝에 콤마랑 마침표 빼주세요

2020-08-31 13:54 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +- `oldValue` -- 해당 옵션이 `attributeOldValue`·`characterDataOldValue`으로 설정된 경우, 속성이나 텍스트 변경에만 따른 이전 값
명사형으로 끝나는 설명 뒤에 콤마는 빼주세요

2020-08-31 13:54 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +예를 들어 아래에 `contentEditable`속성을 가진 `<div>`가 있습니다. 해당 속성은 `div`에 포커스가 가고 수정할 수 있게 해줍니다.
```suggestion
예를 들어 아래에 `contentEditable`속성을 가진 `<div>`가 있습니다. `contentEditable`속성은 `div`에 포커스가 가고 (무엇을?????) 수정할 수 있게 해줍니다.
```
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EB%8C%80%EB%AA%85%EC%82%AC%EB%8A%94-%EB%AA%85%ED%99%95%ED%95%98%EA%B2%8C

대명사 모범사례 확인해주세요

2020-08-31 13:54 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +`<b>edit</b>`를 삭제하는 등 더 복잡한 수정 연산이 있다면 the mutation 이벤트는 다수의 mutation records를 포함할 수 있습니다.
```suggestion
`<b>edit</b>`를 삭제하는 등 더 복잡한 수정 연산이 있다면 mutation 이벤트는 다수의 mutation record를 포함할 수 있습니다.
```

'다수의' 에 이미 복수 개념이 들어가있어서 s를 빼는것이 좋아보입니다.


https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%96%B4%EC%83%89%ED%95%98%EC%A7%80-%EC%95%8A%EB%8B%A4%EB%A9%B4-%EB%8B%A8%EC%88%98%ED%98%95%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%A9%EC%8B%9C%EB%8B%A4

2020-08-31 13:54 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +  // ...mutation의 세부사항은 브라우저가 이런 삭제사항을 어떻게 처리하는지에 달려있습니다.
```suggestion
  // mutation의 세부사항은 브라우저가 이런 삭제사항을 어떻게 처리하는지에 달려있습니다.
```

'이런' 도 풀어써주세요

2020-08-31 13:54 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +  // 두 개의 인접한 텍스트 노드인 "edit " 과 " please"를 하나의 노드로 통합하거나,
```suggestion
  // 두 개의 인접한 텍스트 노드인 "edit "과 " please"를 하나의 노드로 통합하거나
```

2020-08-31 14:18 UTC, kyujonglee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +먼저 문법을 살펴보고 뒤이어 실무의 예제를 살펴보면서 mutationObserver가 얼마나 유용한지 알아보겠습니다.
먼저 문법을 살펴보고 뒤이어 실무 예제를 살펴보면서 mutationObserver가 얼마나 유용한지 알아보겠습니다.
불필요한 '~의'를 빼서 교정하면 될까요?

이 문장이 제대로 매끄럽게 번역되지 않아 이전에 여러 번 고쳤는데 어렵네요ㅜㅜ

2020-08-31 14:19 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +먼저 문법을 살펴보고 뒤이어 실무의 예제를 살펴보면서 mutationObserver가 얼마나 유용한지 알아보겠습니다.
네네 의만 제거하면 좋은 문장이 될것같아요

2020-08-31 15:12 UTC, kyujonglee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +  // mutation의 세부사항은 브라우저가 `<b>edit</b>`를 삭제하는 등 복잡한 삭제사항을 어떻게 처리하는지에 달려있습니다.
mutation의 세부사항은 브라우저가 `<b>edit</b>`를 삭제하는 것과 같은 삭제사항을 어떻게 처리하는지에 달려있습니다.
이렇게 번역할까도 생각해봤지만 '~것', '같은'이 들어가서 안 좋아보였습니다.

어떻게 하면 더 자연스럽게 변역할 수 있을까요?😭

2020-09-05 08:53 UTC, kyujonglee commented
/done

2020-09-10 15:18 UTC, kyujonglee commented
@Violet-Bora-Lee 번역할 때 일부만 PR을 하면 안되고, 전문을 다 번역하고 PR을 해야할까요?

2020-09-13 12:49 UTC, Violet-Bora-Lee requested changes
모범사례 잘 지켜주셔서 좋았습니다 👍 

최근 스펙인 만큼 자료가 많이 없어서 번역하는데 힘드셨을텐데요,

최대한 독자가 쉽게 이해할 수 있게 풀어써 보았습니다.

2020-09-13 12:49 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +변화가 생기고 나서 해당 `callback`이 실행됩니다. 변화는 첫 번째 인수로 [MutationRecord](https://dom.spec.whatwg.org/#mutationrecord) 객체의 배열이 들어가며 옵저버 자기자신이 두번째 인수로 들어갑니다.
```suggestion
이렇게 뮤테이션 옵저버를 만들고, 변화를 관찰할 DOM 노드를 옵저버에 등록하면 변화가 생길때마다 `callback`이 실행됩니다. 변경 내용은 배열 형태로 콜백 함수의 첫 번째 인수에 전달되는데, 배열 각 요소는 [MutationRecord](https://dom.spec.whatwg.org/#mutationrecord) 객체 형태를 띕니다. 여기에 더하여 앞서 정의한 옵저버는 콜백 함수의 두 번째 인수로 전달됩니다.
```

2020-09-13 12:49 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +[MutationRecord](https://dom.spec.whatwg.org/#mutationrecord) 객체는 프로퍼티를 가지고 있습니다.
이 줄 바로 앞에 
```
If we run this code in the browser, then focus on the given <div> and change the text inside <b>edit</b>, console.log will show one mutation:
```
이런 문장이 추가되었는데요, 이 부분도 번역부탁드릴게요. 9월에 추가된 내용이라 한국어 문서에는 아직 반영이 안됐는데, 추가해주시고 커밋 메시지에 설명도 적어주시면 됩니다.

```suggestion
개발자 도구의 콘솔창을 열고 예시를 실행해봅시다. <div>안쪽을 클릭하고 <b>edit</b>안에 있는 문자열을 수정하면  console.log가 실행되면서 뮤테이션 하나가 콘솔창에 기록됩니다.

콘솔창에서 확인할 수 있는 [MutationRecord](https://dom.spec.whatwg.org/#mutationrecord) 객체엔 다음과 같은 프로퍼티가 있습니다.
```

2020-09-13 12:49 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +- `type` -- mutation 타입, 아래의 타입들 중 하나
```suggestion
- `type` -- 뮤테이션 타입으로 다음 중 하나입니다.
```

2020-09-13 12:49 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +    - `"attributes"`: 속성 수정
```suggestion
    - `attributes`: 속성이 수정되었다는 것을 나타냅니다.
```

2020-09-13 12:49 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +    - `"characterData"`: 텍스트 노드에 사용되는 데이터 수정
```suggestion
    - `"characterData"`: 데이터가 수정되었다는 것을 나타내며 텍스트 노드 내용 변화를 감지합니다. 
```

2020-09-13 12:49 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +    - `"childList"`: 자식 요소의 추가·삭제
```suggestion
    - `"childList"`: 자식 요소가 추가·삭제되었다는 것을 나타냅니다.
```

2020-09-13 12:49 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +- `target` -- 변화가 발생한 곳: `"attributes"`의 요소, `"characterData"`의 텍스트 노드,  `"childList"` mutation의 요소 중 하나
```suggestion
- `target` -- 변화가 발생한 DOM 노드를 나타냅니다. 요소 노드인 경우 `"attributes"`, 텍스트 노드인 경우 `"characterData"`에 대한 정보가 나타납니다. 요소 노드인 경우엔 `"childList"`에서 발생한 변화 정보가 나타나기도 합니다.
```

2020-09-13 12:49 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +- `addedNodes/removedNodes`  -- 추가·삭제된 노드
```suggestion
- `addedNodes/removedNodes`  -- 추가·삭제된 노드를 나타냅니다.
```

2020-09-13 12:49 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +- `previousSibling/nextSibling` -- 추가·삭제된 노드의 이전 및 다음 형제 노드
```suggestion
- `previousSibling/nextSibling` -- 추가·삭제된 노드의 이전 및 다음 형제 노드를 나타냅니다.
```

2020-09-13 12:49 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +- `attributeName/attributeNamespace` -- 변경된 속성의 이름·네임스페이스(XML의 경우)
```suggestion
- `attributeName/attributeNamespace` -- 변경된 속성의 이름이나 네임스페이스(XML)를 나타냅니다.
```

2020-09-13 12:49 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +- `oldValue` -- 해당 옵션이 `attributeOldValue`·`characterDataOldValue`으로 설정된 경우, 속성이나 텍스트 변경에만 따른 이전 값
```suggestion
- `oldValue` -- 변경 이전 값을 나타내는데 `attributeOldValue`나 `characterDataOldValue`가 참으로 설정된 경우에만 나타나고 각각 속성이나 텍스트 변경 이전 값이 나타납니다.
```

2020-09-13 12:49 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +예를 들어 아래에 `contentEditable`속성을 가진 `<div>`가 있습니다. 해당 속성은 `div`에 포커스가 가고 텍스트를 수정할 수 있게 해줍니다.
```suggestion
예시를 살펴봅시다. `contentEditable` 속성이 있는 `<div>`가 있습니다. `contentEditable` 속성을 추가하고 해당 요소에 포커스를 주면 텍스트를 수정할 수 있습니다.
```

2020-09-13 12:49 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
>  <div contentEditable id="elem">Click and <b>edit</b>, please</div>
```suggestion
<div contentEditable id="elem">이곳을 클릭하고 <b>이곳을 수정</b>해주세요.</div>
```

2020-09-13 12:49 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +// 속성을 제외한 모든 것을 관찰
```suggestion
// 속성 변화를 제외한 모든 변화를 관찰
```

2020-09-13 12:49 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +이 코드를 브라우저에서 실행한 다음, 주어진 `<div>`에 포커스를 옮겨 `<b>edit</b>`안의 텍스트를 변경하면 `console.log`는 하나의 mutation을 출력합니다.
```suggestion
실제로 이 예시를 브라우저에서 실행한 다음, `<div>`안을 클릭해 포커스를 옮긴 후, `<b>이곳을 수정</b>`이라는 글자를 수정하면 콘솔창엔 다음과 같은 뮤테이션 하나가 출력됩니다.
```

2020-09-13 12:49 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +`<b>edit</b>`를 삭제하는 등 더 복잡한 수정 연산이 있다면 the mutation 이벤트는 다수의 mutation record를 포함할 수 있습니다.
```suggestion
`'<b>이곳을 수정</b>'`을 삭제하는 것과 같이 더 복잡하게 DOM을 조작하면 콜백 함수의 첫번 째 인수로 전달되는 배열인 `MutationRecords`엔 여러 개의 `MutationRecord` 객체가 들어갑니다.
```

2020-09-13 12:49 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +  // mutation의 세부사항은 브라우저가 `<b>edit</b>`를 삭제하는 등 복잡한 삭제사항을 어떻게 처리하는지에 달려있습니다.
```suggestion
  // 이때 실제 `MutationRecord` 객체 안은 브라우저가 텍스트 노드 삭제등의 DOM 조작을 어떻게 처리하냐에 따라 달라집니다.
```

2020-09-13 12:49 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +  // 두 개의 인접한 텍스트 노드인 "edit "과 " please"를 하나의 노드로 통합하거나
```suggestion
  // 인접한 두 텍스트 노드 "edit "과 " please"를 하나의 노드로 통합하거나
```

2020-09-13 12:49 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +  // "edit "과 " please"를 별도의 텍스트 노드로 둘 수도 있습니다.
```suggestion
  // 기존처럼 "edit "과 " please"를 별도의 텍스트 노드로 둘 수도 있습니다.
```

2020-09-13 12:49 UTC, Violet-Bora-Lee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +따라서 `MutationObserver`는 DOM 하위 트리의 변화에 반응할 수 있게 해줍니다.
```suggestion
이렇게 `MutationObserver`를 사용하면 DOM 하위 트리의 변화에 반응할 수 있습니다.
```

2020-10-01 12:24 UTC, kyujonglee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
>  # Mutation observer
다른 공학 분야에서 이미 사용되고 있었군요 몰랐습니다. 그렇다면 뮤테이션 옵저버라고 해도 의미가 통할 거 같아서 좋을 거 같습니다.

2020-10-01 12:37 UTC, kyujonglee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +먼저 콜백 함수와 함께 옵저버를 생성합니다.
네 추가하였습니다.

2020-10-01 12:39 UTC, kyujonglee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +`config`는 '어떤 변화의 종류에 반응할지'에 대한 참 거짓 옵션을 가지는 객체입니다.
더 명확하게 이해가 되는 것 같습니다 :)

2020-10-01 12:54 UTC, kyujonglee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +- `characterData` -- `node.data`(텍스트 내용)을 관찰할지에 대한 여부
`config`가 '어떤 종류의 DOM 변화를 감지하고 "반응"할지'를 참, 거짓 값을 통해 설정하는 객체이고, 
속성들을 설명할 때 childList, subtree, attributes에는 뒤에 '~변화에 반응, ~변할 때 반응'과 같이 번역을 해주고
attributeFilter, characterData는 그렇지 않습니다.
혹시 이렇게 번역하신 특별한 이유가 있을까요~?
아니면 통일을 하거나
config에서 '반응'이라는 의미를 내포하고 있기 때문에 '~변화에 반응'과 같은 말은 빼는게 좋아보입니다.

2020-10-01 13:07 UTC, kyujonglee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +[MutationRecord](https://dom.spec.whatwg.org/#mutationrecord) 객체는 프로퍼티를 가지고 있습니다.
실제로 확인해본 결과 위에 추가된 문장이 다음 부분에 추가되어 있어서 해당 부분에 추가로 넣어주도로 하겠습니다.
If we run this code in the browser, then focus on the given `<div>` and change the text inside `<b>edit</b>`, `console.log` will show one mutation:

```js
mutationRecords = [{
  type: "characterData",
  oldValue: "edit",
  target: <text node>,
  // other properties empty
}];
```

2020-10-01 14:53 UTC, kyujonglee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +이 코드를 브라우저에서 실행한 다음, 주어진 `<div>`에 포커스를 옮겨 `<b>edit</b>`안의 텍스트를 변경하면 `console.log`는 하나의 mutation을 출력합니다.
위에서는 똑같은 문장을 이렇게 번역해주셨는데요.
개발자 도구의 콘솔창을 열고 예시를 실행해봅시다. <div>안쪽을 클릭하고 <b>edit</b>안에 있는 문자열을 수정하면  console.log가 실행되면서 뮤테이션 하나가 콘솔창에 기록됩니다.

둘을 섞어서, 
개발자 도구의 콘솔창을 열고 예시를 브라우저에서 실행해봅시다. `<div>`안을 클릭해 포커스를 옮긴 후, `<b>이곳을 수정</b>`이라는 글자를 수정하면 콘솔창엔 다음과 같은 뮤테이션 하나가 출력됩니다.
로 번역하는게 좋아보이는데 어떻게 생각하시나요?

2020-10-01 15:02 UTC, kyujonglee commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +  // "edit "과 " please"를 별도의 텍스트 노드로 둘 수도 있습니다.
기존처럼 이라는 번역을 추가하신 이유가 무엇인가요?

2020-10-01 15:03 UTC, kyujonglee commented
/done

2021-01-03 02:21 UTC, Violet-Bora-Lee commented
안녕하세요. 충돌 해결해주시면 리뷰 다시 진행해보겠습니다.

2021-01-03 07:48 UTC, closed without merging