[오타수정] Part1 7.1 프로퍼티 플래그와 설명자 #787
javascript-tutorial/ko.javascript.info pull request #788
Opened 2020-08-27 13:18 UTC by OMEGA-Y

# Pull Request 체크리스트
## TODO
- [ ] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [ ] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [ ] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [ ] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [ ] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [ ] PR 하나엔 번역문 하나만 넣으셨나요?
- [ ] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

2020-08-30 06:15 UTC, Violet-Bora-Lee requested changes

2020-08-30 06:15 UTC, Violet-Bora-Lee commented on 1-js/07-object-properties/01-property-descriptors/article.md
> +이 챕터에선 객체 프로퍼티 추가 구성 옵션 몇 가지를 다룰 것입니다. 이어지는 챕터에선 이 옵션들을 이용해 손쉽게 getter나 setter 함수를 만드는 법을 알아보겠습니다.
```suggestion
이 챕터에선 객체 프로퍼티 추가 구성 옵션 몇 가지를 다루고, 이어지는 챕터에선 이 옵션들을 이용해 손쉽게 getter나 setter 함수를 만드는 법을 알아보겠습니다.
```

2020-08-30 06:15 UTC, Violet-Bora-Lee commented on 1-js/07-object-properties/01-property-descriptors/article.md
>  지금까진 프로퍼티를 단순히 "키-값" 쌍의 관점에서만 다뤘습니다. 그런데 사실 프로퍼티는 우리가 생각했던 것보다 더 유연하고 강력한 자료구조입니다.
여기도 '키-값' 으로 고쳐주세요 ㅎㅎ

2020-08-30 08:00 UTC, OMEGA-Y commented on 1-js/07-object-properties/01-property-descriptors/article.md
> +이 챕터에선 객체 프로퍼티 추가 구성 옵션 몇 가지를 다룰 것입니다. 이어지는 챕터에선 이 옵션들을 이용해 손쉽게 getter나 setter 함수를 만드는 법을 알아보겠습니다.
수정했습니다.

2020-08-30 08:00 UTC, OMEGA-Y commented on 1-js/07-object-properties/01-property-descriptors/article.md
>  지금까진 프로퍼티를 단순히 "키-값" 쌍의 관점에서만 다뤘습니다. 그런데 사실 프로퍼티는 우리가 생각했던 것보다 더 유연하고 강력한 자료구조입니다.
수정했습니다!

2020-08-31 13:28 UTC, Violet-Bora-Lee commented
감사합니다
머지진행하겠습니다

2020-08-31 13:28 UTC, merged