파트1 4.6 옵셔널체이닝 원문반영번역 #784
javascript-tutorial/ko.javascript.info pull request #792
Opened 2020-08-27 14:25 UTC by sowon-dev

# Pull Request 체크리스트
## TODO
- [x] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [x] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [x] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [x] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [x] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [x] PR 하나엔 번역문 하나만 넣으셨나요?
- [x] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

2020-08-31 13:57 UTC, Violet-Bora-Lee commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +변수 `user`가 전혀 선언되어있지 않으면 `user?.anything` 평가시 에러가 발생합니다.
'전혀'를 추가하신 이유가 있을까요?

2020-08-31 17:00 UTC, sowon-dev commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +변수 `user`가 전혀 선언되어있지 않으면 `user?.anything` 평가시 에러가 발생합니다.
저도 고민을 했던 부분입니다. 원문에 `at all`을 추가하셨더라구요. 최대한 원문 반영하고자 기재하였습니다.
아래 원문 커밋 공유드립니다. 77번째 행이예요!

[원문 커밋 77번째 행](https://github.com/javascript-tutorial/en.javascript.info/commit/1f0fcb7de6eaf288daf5b035c74b77c7f0644759)

2020-09-08 14:31 UTC, Violet-Bora-Lee requested changes
옵셔널 체이닝 글 전반적으로 한번 퇴고 하였습니다.
최신으로 소스코드 유지하시고, 리뷰드린부분 수정해주시면 바로 머지 진행할게요 👍

2020-09-08 14:31 UTC, Violet-Bora-Lee commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +위 예시에서 `user?.`는 오직 `user`만 `null/undefined`인 것을 허용합니다.
```suggestion
위 예시에서 `user?.`는 `user`가 `null`이나 `undefined`일 때만 의도한대로 동작합니다.
```

2020-09-08 14:31 UTC, Violet-Bora-Lee commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +만약 `user` 값이 존재한다면 `user.address` 프로퍼티가 꼭 있어야 합니다. 그렇지 않으면 `user?.address.street`의 두 번째 마침표에서 에러가 발생합니다.
```suggestion
`user`에 값이 있는 경우엔 `user.address` 프로퍼티가 반드시 있어야 합니다. 그렇지 않으면 `user?.address.street`의 두 번째 마침표에서 에러가 발생합니다.
```

2020-09-08 14:31 UTC, Violet-Bora-Lee commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +만약 `user` 값이 존재한다면 `user.address` 프로퍼티가 꼭 있어야 합니다. 그렇지 않으면 `user?.address.street`의 두 번째 마침표에서 에러가 발생합니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#if%EB%8A%94-%EC%83%9D%EB%9E%B5%ED%95%A0-%EC%88%98%EB%8F%84-%EC%9E%88%EC%8A%B5%EB%8B%88%EB%8B%A4

모범사례 참고하여 수정해보았습니다.

2020-09-08 14:31 UTC, Violet-Bora-Lee commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +변수 `user`가 전혀 선언되어있지 않으면 `user?.anything` 평가시 에러가 발생합니다.
'전혀'는 빼도 좋을것같아요.

2020-09-08 14:31 UTC, Violet-Bora-Lee commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +반드시 `let/const/var user`로 선언되어야 합니다. 옵셔널 체이닝은 선언된 변수만 평가합니다.
```suggestion
`user?.anything`이 의도한대로 동작하게 하려면 반드시 `let user`나 `const user`, `var user`를 사용해 `user`가 선언되어 있어야 합니다. 옵셔널 체이닝은 선언된 변수만 평가하기 때문입니다.
```

2020-09-10 12:29 UTC, sowon-dev commented
/done

2020-09-10 23:56 UTC, sowon-dev commented
어라 보라님 저는 컨플릿 안나는데,,,

![image](https://user-images.githubusercontent.com/53078820/92827125-7486d600-f40c-11ea-8961-7016f221bd89.png)

2020-09-11 00:05 UTC, Violet-Bora-Lee commented
저희 저장소는 리베이스 머지하고있어서요. 최신화해주셔야할것같아요

2020-09-13 12:56 UTC, Violet-Bora-Lee commented
Please make your branch up-to-date with rebase and check the commits on your PR.

![image](https://user-images.githubusercontent.com/6451384/93018608-eaa55b80-f60b-11ea-82f4-a0e5e62d82dd.png)

2020-09-29 14:20 UTC, sowon-dev commented
리베이스문제로 PR닫고 [재 PR하였습니다](https://github.com/javascript-tutorial/ko.javascript.info/pull/870).

2020-09-29 14:20 UTC, closed without merging