[번역]Part1 10.1 오류 다시 던지기 추가된 영문 번역
javascript-tutorial/ko.javascript.info pull request #799
Opened 2020-08-29 04:50 UTC by kbpark

# Pull Request 체크리스트
## TODO
- [ ] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [ ] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [ ] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [ ] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [ ] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [ ] PR 하나엔 번역문 하나만 넣으셨나요?
- [ ] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

2020-08-29 04:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ko.javascript.info?pullRequest=799) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ko.javascript.info?pullRequest=799) before we can accept your contribution.<br/><hr/>**KB Park** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ko.javascript.info?pullRequest=799) it.</sub>

2020-08-30 06:24 UTC, Violet-Bora-Lee requested changes
오랫만에 오셨네요!
환영합니다 👍 

몇가지 코멘트 달아보았습니다.

2020-08-30 06:24 UTC, Violet-Bora-Lee commented on 1-js/10-error-handling/1-try-catch/article.md
> +이런 문제를 피하고자, '다시 던지기(rethrowing)" 기술을 사용합니다. 규칙은 간단합니다.
```suggestion
이런 문제를 피하고자 '다시 던지기(rethrowing)' 기술을 사용합니다. 규칙은 간단합니다.
```
따옴표 관련 모범사례 확인부탁드립니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EA%B0%95%EC%A1%B0%EC%9D%B8%EC%9A%A9%EC%8B%9C-%EC%82%AC%EC%9A%A9%EB%90%98%EB%8A%94-%EB%94%B0%EC%98%B4%ED%91%9C

2020-08-30 06:24 UTC, Violet-Bora-Lee commented on 1-js/10-error-handling/1-try-catch/article.md
> +"다시 던지기(rethrowing)" 기술을 더 자세히 설명하겠습니다.
따옴표 모범사례 확인해주세요.

2020-08-30 06:24 UTC, Violet-Bora-Lee commented on 1-js/10-error-handling/1-try-catch/article.md
> +**Cathch는 알고 있는 에러만 처리하고 나머지는 다시 던져야 합니다.**
```suggestion
**catch는 알고 있는 에러만 처리하고 나머지는 다시 던져야 합니다.**
```

2020-08-30 06:24 UTC, Violet-Bora-Lee commented on 1-js/10-error-handling/1-try-catch/article.md
> +1. Catch가 모든 에러를 받습니다.
```suggestion
1. catch가 모든 에러를 받습니다.
```

2020-08-30 06:24 UTC, Violet-Bora-Lee commented on 1-js/10-error-handling/1-try-catch/article.md
> +3. 에러 처리 방법을 알지 못하면, `throw err`를 합니다.
```suggestion
3. 에러 처리 방법을 알지 못하면 `throw err`를 합니다.
```

https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%89%BC%ED%91%9C%EB%A5%BC-%EB%AA%A8%EB%91%90-%EC%98%AE%EA%B8%B8-%ED%95%84%EC%9A%94%EB%8A%94-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4

쉼표 모범사례 확인부탁드립니다.

2020-08-30 06:24 UTC, Violet-Bora-Lee commented on 1-js/10-error-handling/1-try-catch/article.md
> +    alert('ReferenceError'); //  정의되지 않은 변수에 접근하여 "ReferenceError" 발생
따옴표 모범사례 확인

2020-08-30 06:24 UTC, Violet-Bora-Lee commented on 1-js/10-error-handling/1-try-catch/article.md
> +`err.name` 프로퍼티로 에러 클래스 이름을 알 수도 있습니다. 기본형 에러는 모두 이 프로퍼티를 가집니다. 또는 `err.constructor.name`를 사용할 수도 있습니다.
```suggestion
`err.name` 프로퍼티로 에러 클래스 이름을 알 수도 있습니다. 기본형 에러는 모두 이 프로퍼티를 가집니다. 또는 `err.constructor.name`을 사용할 수도 있습니다.
```

2020-08-30 07:23 UTC, closed without merging

2020-08-30 07:23 UTC, kbpark commented
새로 Pull Request 하였습니다^^