Part1 9.2 클래스 상속 미번역된 부분 번역
javascript-tutorial/ko.javascript.info pull request #814
Opened 2020-08-30 13:50 UTC by OMEGA-Y

# Pull Request 체크리스트
## TODO
- [ ] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [ ] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [ ] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [ ] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [ ] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [ ] PR 하나엔 번역문 하나만 넣으셨나요?
- [ ] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

2020-09-03 12:38 UTC, Violet-Bora-Lee requested changes
번역 잘 해주셔서 크게 수정할 부분이 없네요.

맞춤법 관련 코멘트 몇개 달아보았습니다.

2020-09-03 12:38 UTC, Violet-Bora-Lee commented on 1-js/09-classes/02-class-inheritance/article.md
> +### 클래스 필드 오버라이딩 : 까다로운 내용
띄어쓰기는 쌍점 뒤에만 해주세요.

https://www.korean.go.kr/front/page/pageView.do?page_id=P000197&mn_id=30

2020-09-03 12:38 UTC, Violet-Bora-Lee commented on 1-js/09-classes/02-class-inheritance/article.md
> +이번 절에선 프로그래밍 언어에 대한 통찰력을 높이고 버그를 종종 유발할 수 있는 행동에 대해 알아갈 예정입니다.
it을 챕터로 써서 번역해주세요.

관련 사항은 용어집 chapter와 논의사항 시트를 확인해주세요.

https://docs.google.com/spreadsheets/d/1fYaEI8vz26N3R2VaxrlNnk9fMQ8zIy4RpvjRp4jZd0Q/edit#gid=1170768089

2020-09-03 12:38 UTC, Violet-Bora-Lee commented on 1-js/09-classes/02-class-inheritance/article.md
> +이번 절에선 프로그래밍 언어에 대한 통찰력을 높이고 버그를 종종 유발할 수 있는 행동에 대해 알아갈 예정입니다.
not often 에 대해 다시한번 버역 부탁드릴게요

2020-09-03 12:38 UTC, Violet-Bora-Lee commented on 1-js/09-classes/02-class-inheritance/article.md
> +**다시 말해서, 부모 생성자는 항상 자식 클래스에서 오버라이딩한 값이 아니라 부모 클래스 안의 필드 값을 사용합니다**
마침표가 빠져있습니다.

2020-09-03 12:38 UTC, Violet-Bora-Lee commented on 1-js/09-classes/02-class-inheritance/article.md
> +아래에 동일한 코드가 있습니다. 다른 점은 `this.name` 대신에 `this.showName()` 메서드가 있습니다.
주술구조가 조금 어색합니다.
정확히 어떻게 바꿔야 하는지는 모르겠는데 한번 더 검토 부탁드릴게요.

2020-09-03 12:38 UTC, Violet-Bora-Lee commented on 1-js/09-classes/02-class-inheritance/article.md
> +우리가 자연스럽게 예상한대로 상속받는 클래스에서 부모 생성자를 호출했을 때 오버라이딩한 메서드를 사용합니다.
```suggestion
예상한대로 상속받는 클래스에서 부모 생성자를 호출하면 오버라이딩한 메서드를 사용합니다.
```

2020-09-03 12:38 UTC, Violet-Bora-Lee commented on 1-js/09-classes/02-class-inheritance/article.md
> +...그런데 클래스 필드에서는 위와 같이 동작하지 않습니다. 앞서 말했듯이, 부모 생성자가 항상 부모 필드의 값을 사용합니다.
```suggestion
그런데 클래스 필드에서는 '요약' 동작하지 않습니다. 앞서 말했듯이, 부모 생성자가 항상 부모 필드의 값을 사용합니다.
```

2020-09-03 12:38 UTC, Violet-Bora-Lee commented on 1-js/09-classes/02-class-inheritance/article.md
> +그 이유는 필드 초기화 규칙(field initialization order) 때문입니다. 다음과 같은 순서로 초기화됩니다.
```suggestion
그 이유는 필드 초기화 규칙(field initialization order) 때문입니다. 필드 초기화 규칙이 적용되면 다음과 같은 순서로 필드가 초기화됩니다.
```

2020-09-03 12:38 UTC, Violet-Bora-Lee commented on 1-js/09-classes/02-class-inheritance/article.md
> +현재 `Rabbit`은 상속받는 클래스이고 `constructor()`를 갖고 있지 않습니다. 이런 경우 빈 생성자인 `super(...args)`를 갖고 있다고 보면 됩니다.
derived class를 어떻게 번역할지 기존 출판된 책을 기준으로 리서치 해주시고, 용어집에 해당 용어 추가 부탁드릴게요.

2020-09-03 12:38 UTC, Violet-Bora-Lee commented on 1-js/09-classes/02-class-inheritance/article.md
> +따라서 `new Rabbit()`은 `super()`를 호출하고 그 결과 부모 생성자가 실행됩니다. 부모 생성자가 실행된 직후 (상속받는 클래스의 필드 초기화 규칙에 따라) 클래스 `Rabbit`의 필드가 초기화됩니다. 부모 생성자가 실행되는 시점에 클래스 `Rabbit`의 필드는 아직 존재하지 않습니다. 이와 같은 이유로 위에서 필드 오버라이딩을 했을
```suggestion
따라서 `new Rabbit()`은 `super()`를 호출하게되는데, 그 결과 부모 생성자가 실행됩니다. 부모 생성자가 실행된 직후 (상속받는 클래스의 필드 초기화 규칙에 따라) 클래스 `Rabbit`의 필드가 초기화됩니다. 부모 생성자가 실행되는 시점에 클래스 `Rabbit`의 필드는 아직 존재하지 않습니다. 이와 같은 이유로 위에서 필드 오버라이딩을 했을 때 `Animal` 필드가 사용됐었습니다.
```

2020-09-03 12:38 UTC, Violet-Bora-Lee commented on 1-js/09-classes/02-class-inheritance/article.md
> +필드 오버라이딩이 문제가 된다면 메서드를 사용하거나 필드 대신에 getters/setters를 사용해 해결하면 됩니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%A7%9D%EC%9D%84-%EC%9D%B4%EB%A3%A8%EB%8A%94-%EB%8B%A8%EC%96%B4%EB%A5%BC-%EC%9D%B4%EC%9D%84-%EB%95%8C%EB%8A%94-%EA%B0%80%EC%9A%B4%EB%8E%83%EC%A0%90-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

모범 사례 확인 부탁드립니다.

2020-09-04 06:20 UTC, OMEGA-Y commented
수정했습니다!

2020-09-08 15:18 UTC, Violet-Bora-Lee requested changes
코멘트 남겨보았습니다.

마지막쪽에 약간 오역이 있었네요.

그렇지만 전반적으로 훌륭한 퀄리티의 번역이었습니다!

2020-09-08 15:18 UTC, Violet-Bora-Lee commented on 1-js/09-classes/02-class-inheritance/article.md
> +- 기본 클래스(아무것도 상속받지 않음)의 생성자 실행 이전에
```suggestion
- 아무것도 상속받지 않는 베이스 클래스는 생성자 실행 이전에 초기화 됨
```

2020-09-08 15:18 UTC, Violet-Bora-Lee commented on 1-js/09-classes/02-class-inheritance/article.md
> +- 하위 클래스의 경우 `super()` 실행 바로 후에
```suggestion
- 부모 클래스가 있는 경우엔 `super()` 실행 바로 후에 초기화 됨
```

2020-09-08 15:18 UTC, Violet-Bora-Lee commented on 1-js/09-classes/02-class-inheritance/article.md
> +현재 `Rabbit`은 하위 클래스이고 `constructor()`를 갖고 있지 않습니다. 이런 경우 빈 생성자인 `super(...args)`를 갖고 있다고 보면 됩니다.
```suggestion
위 예시에서 `Rabbit`은 상속받은 클래스이고 `constructor()`가 정의되어 있지 않습니다. 이런 경우 앞서 설명드린바와 같이 생성자는 비어있는데 그 안에 `super(...args)`만 있다고 보면 됩니다.
```

2020-09-08 15:18 UTC, Violet-Bora-Lee commented on 1-js/09-classes/02-class-inheritance/article.md
> +따라서 `new Rabbit()`은 `super()`를 호출하게 되는데, 그 결과 부모 생성자가 실행됩니다. 부모 생성자가 실행된 직후 (하위 클래스의 필드 초기화 규칙에 따라) 클래스 `Rabbit`의 필드가 초기화됩니다. 부모 생성자가 실행되는 시점에 클래스 `Rabbit`의 필드는 아직 존재하지 않습니다. 이와 같은 이유로 위에서 필드 오버라이딩을
```suggestion
따라서 `new Rabbit()`을 실행하면 `super()`가 호출되고 그 결과 부모 생성자가 실행됩니다. 그런데 이때 하위 클래스 필드 초기화 규칙에 따라 자손 클래스 `Rabbit`의 필드는 `super()` 실행 후에 초기화됩니다. 부모 생성자가 실행되는 시점에 `Rabbit`의 필드는 아직 존재하지 않죠. 이런 이유로 필드를 오버라이딩 했을 때 `Animal`에 있는 필드가 사용된 것입니다.
```

2020-09-08 15:18 UTC, Violet-Bora-Lee commented on 1-js/09-classes/02-class-inheritance/article.md
> +필드와 메서드 사이의 이렇게 미묘한 차이는 자바스크립트에만 해당됩니다.
```suggestion
이렇게 오버라이딩시 필드와 메서드의 동작 방식이 미묘하게 차이나는 것은 자바스크립트에만 해당됩니다.
```

2020-09-08 15:18 UTC, Violet-Bora-Lee commented on 1-js/09-classes/02-class-inheritance/article.md
> +다행히, 위와 같은 문제는 오버라이딩한 필드가 부모 생성자에서 사용될 때만 발생합니다. 다음 절에서는 지금까지 설명한 내용이 구체적으로 어떻게 동작하는지 다루겠습니다.
```suggestion
다행히도 이런 문제는 오버라이딩한 필드를 부모 생성자에서 사용할 때만 발생합니다. 이런 차이가 왜 발생하는지 모르면 결과를 해석할 수 없는 상황이 발생하기 때문에 별도의 공간을 만들어 필드 오버라이딩시 내부에서 어떤 일이 벌어지는지를 알아보았습니다. 
```

2020-09-08 15:18 UTC, Violet-Bora-Lee commented on 1-js/09-classes/02-class-inheritance/article.md
> +필드 오버라이딩이 문제가 된다면 메서드를 사용하거나 필드 대신에 getters·setters를 사용해 해결하면 됩니다.
```suggestion
개발을 하다가 필드 오버라이딩이 문제가 되는 상황이 발생하면 필드 대신 메서드를 사용하거나 getters·setters를 사용해 해결하면 됩니다.
```

2020-09-09 13:48 UTC, OMEGA-Y commented on 1-js/09-classes/02-class-inheritance/article.md
> +현재 `Rabbit`은 하위 클래스이고 `constructor()`를 갖고 있지 않습니다. 이런 경우 빈 생성자인 `super(...args)`를 갖고 있다고 보면 됩니다.
**derived class**를 어떻게 번역해야 할지 고민이 됩니다. 저도 원래 **상속받은 클래스**로 번역하였다가 보라님이 밋업 때 책 한 번 찾아보라고 하셔서 책을 찾아 봤었습니다. 책의 상속과 관련된 내용에서 등장하는 키워드가 상위 클래스와 하위 클래스 밖에 없었어 가지고, derived class를 **하위 클래스**로 번역하면 될 것 같아 일단 용어집에 등록해 놓기는 하였습니다. 

그런데, 하위 클래스보다는 상속받은 클래스가 뭔가 이해가 더 잘되는 번역 같기도 합니다.  마이크로소프트 Language Portal의 Terminology Search 페이지도 찾아봤는데 여기는 **파생 클래스**라고 번역을 하더군요.

어떻게 하면 좋을까요?

2020-09-09 14:00 UTC, Violet-Bora-Lee commented on 1-js/09-classes/02-class-inheritance/article.md
> +현재 `Rabbit`은 하위 클래스이고 `constructor()`를 갖고 있지 않습니다. 이런 경우 빈 생성자인 `super(...args)`를 갖고 있다고 보면 됩니다.
책에서 많이 쓰이는 표현을 써야 독자들이 이질감 없게 느껴지는 경향이 있는것같아요
저도 그렇구요
제가 가진 책들 대다수가 하위클래스로 쓰고있어서, 하위클래스로 하고 pharaprazing 용도로 적절히 섞어쓰면 좋을것같네요

2020-09-10 05:40 UTC, OMEGA-Y commented
꼼꼼한 리뷰 감사합니다!!
수정했으니 확인 부탁드립니다 :)

2020-09-10 10:38 UTC, Violet-Bora-Lee requested changes

2020-09-10 11:39 UTC, Canine89 reviewed
전반적으로 읽어보면서 원래 번역하신 분의 의미는 살리고, 다듬을 문장은 다듬었습니다.

2020-09-10 11:39 UTC, Canine89 commented on 1-js/09-classes/02-class-inheritance/article.md
> +이해하기 어렵다면 이 부분을 건너뛰었다가 나중에 다시 읽어도 됩니다.
어쩌면 조금 이해하기 어려울 수도 있을 것입니다. 그럴 때는 이 부분을 건너뛰고 나중에 다시 돌아와 읽어도 됩니다.

2020-09-10 11:39 UTC, Canine89 commented on 1-js/09-classes/02-class-inheritance/article.md
> +오버라이딩은 메서드뿐만 아니라 클래스 필드를 대상으로도 적용할 수 있습니다.
오버라이딩은 메서드와 클래스 필드에 적용할 수 있습니다.

2020-09-10 11:39 UTC, Canine89 commented on 1-js/09-classes/02-class-inheritance/article.md
> +부모 클래스의 생성자 안에 있는 오바라이딩한 필드에 접근하려고 할 때 자바스크립트는 다른 프로그래밍 언어와는 다르게 조금 까다롭지만 말이죠.
단, 자바스크립트는 부모 클래스 생성자 안에 오버라이딩한 필드에 접근하는 방식이 조금 까다롭습니다(다른 프로그래밍 언어와 접근 방식이 약간 다릅니다).

2020-09-10 11:39 UTC, Canine89 commented on 1-js/09-classes/02-class-inheritance/article.md
> +`Rabbit`에는 따로 생성자가 정의되어 있지 않기 때문에, `Rabbit`을 사용해 인스턴스를 만들면 `Animal`의 생성자가 호출됩니다.
`Rabbit`에는 따로 생성자가 정의되어 있지 않기 때문에 `Rabbit`을 사용해 인스턴스를 만들면 `Animal`의 생성자가 호출됩니다.

2020-09-10 11:39 UTC, Canine89 commented on 1-js/09-classes/02-class-inheritance/article.md
> +흥미로운 점은 `new Animal()`과 `new Rabbit()`을 실행할 때 두 경우 모두 `(*)`로 표시한 줄에 있는 `alert` 함수가 실행되면서 얼럿창에 `animal`이 출력된다는 점입니다.
얼럿창 -> 얼럿 창

2020-09-10 11:39 UTC, Canine89 commented on 1-js/09-classes/02-class-inheritance/article.md
> +이를 통해 우리는 **"부모 생성자는 자식 클래스에서 오버라이딩한 값이 아닌, 부모 클래스 안의 필드 값을 사용한다"**는 사실을 알 수 있습니다.
큰따옴표 -> 작은따옴표로 변경

2020-09-10 11:39 UTC, Canine89 commented on 1-js/09-classes/02-class-inheritance/article.md
> +상속을 받고 필드 값을 오버라이딩했는데, 새로운 값 대신 부모 클래스 안에 있는 기존 필드 값을 사용하다니 이상하지 않나요?
쉼표 제거

2020-09-10 11:39 UTC, Canine89 commented on 1-js/09-classes/02-class-inheritance/article.md
> +이렇게 자식 클래스에서 부모 생성자를 호출하면 오버라이딩한 메서드를 사용하는 게 우리가 원하던 결과이죠.
위와 같이 자식 클래스에서 부모 생성자를 호출하면 오버라이딩한 메서드가 실행되어야 합니다. 이게 우리가 바라던 결과죠.

2020-09-10 11:39 UTC, Canine89 commented on 1-js/09-classes/02-class-inheritance/article.md
> +- 아무것도 상속받지 않는 베이스 클래스는 생성자 실행 이전에 초기화됨
베이스 -> 기본

2020-09-10 11:39 UTC, Canine89 commented on 1-js/09-classes/02-class-inheritance/article.md
> +- 부모 클래스가 있는 경우엔 `super()` 실행 바로 후에 초기화됨
실행 후에 초기화됨

2020-09-10 11:39 UTC, Canine89 commented on 1-js/09-classes/02-class-inheritance/article.md
> +따라서 `new Rabbit()`을 실행하면 `super()`가 호출되고 그 결과 부모 생성자가 실행됩니다. 그런데 이때 하위 클래스 필드 초기화 순서에 따라 하위 클래스 `Rabbit`의 필드는 `super()` 실행 후에 초기화됩니다. 부모 생성자가 실행되는 시점에 `Rabbit`의 필드는 아직 존재하지 않죠. 이런 이유로 필드를 오버라이딩 했을 때
따라서 `new Rabbit()`을 실행하면 `super()`가 호출되면서 부모 생성자가 실행됩니다. 이때 '하위 클래스 필드 초기화 순서'에 따라 하위 클래스 `Rabbit`의 필드는 `super()`가 실행된 다음 초기화됩니다. 그러면 부모 생성자가 실행되는 시점에는 `Rabbit`의 필드가 없겠죠. 그래서 필드를 오버라이딩해도 `Animal`에 있는 필드가 사용되는 것입니다.

2020-09-10 11:39 UTC, Canine89 commented on 1-js/09-classes/02-class-inheritance/article.md
> +이렇게 오버라이딩시 필드와 메서드의 동작 방식이 미묘하게 차이 나는 것은 자바스크립트에만 해당합니다.
이렇게 자바스크립트에서는 오버라이딩 시 필드와 메서드의 동작 방식이 미묘하게 다릅니다.

2020-09-10 11:39 UTC, Canine89 commented on 1-js/09-classes/02-class-inheritance/article.md
> +다행히도 이런 문제는 오버라이딩한 필드를 부모 생성자에서 사용할 때만 발생합니다. 이런 차이가 왜 발생하는지 모르면 결과를 해석할 수 없는 상황이 발생하기 때문에 별도의 공간을 만들어 필드 오버라이딩시 내부에서 어떤 일이 벌어지는지를 알아보았습니다.
다행히도 이런 문제는 '오버라이딩한 필드를 부모 생성자에서 사용할 때'만 발생합니다. 하지만 다른 말로 하면 이런 상황은 '매우 드물게' 일어납니다. 그래서 '왜 이런 이상한 결과가 발생했는지 알 수 없는 상황'에 놓일 확률이 높을 것입니다. 그래서 여기서 특별히 '필드를 오버라이딩할 때 어떤 일이 벌어지는지'에 대해 자세히 설명했습니다. 잘 알아두고 넘어갑시다.

-> 원문을 그대로 살려야 한다면 제가 살린 문장은 틀린 번역일 것 같은데요. 원문을 쓴 글쓴이의 의도는 '그래. 다행히도 이건 아주 드문 경우야, 하지만 그만큼 잘 일어나는 일이 아니라서 막상 그 일이 발생하게 되면 이해하기 힘들걸?'이라는 뜻으로 이해했습니다. 리뷰 때 확인 부탁드립니다.

2020-09-10 11:39 UTC, Canine89 commented on 1-js/09-classes/02-class-inheritance/article.md
> +개발하다가 필드 오버라이딩이 문제가 되는 상황이 발생하면 필드 대신 메서드를 사용하거나 getters·setters를 사용해 해결하면 됩니다.
만약 이런 문제가 발생하면 필드 대신 메서드를 사용하거나 getters 또는 setters를 사용하면 됩니다.

2020-09-10 12:14 UTC, Violet-Bora-Lee commented on 1-js/09-classes/02-class-inheritance/article.md
> +이를 통해 우리는 **"부모 생성자는 자식 클래스에서 오버라이딩한 값이 아닌, 부모 클래스 안의 필드 값을 사용한다"**는 사실을 알 수 있습니다.
강조를 위해 사용된 따옴표이므로 작은 따옴표로 변경해주세요

https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=111347

2020-09-10 15:12 UTC, OMEGA-Y commented on 1-js/09-classes/02-class-inheritance/article.md
> +이렇게 오버라이딩시 필드와 메서드의 동작 방식이 미묘하게 차이 나는 것은 자바스크립트에만 해당합니다.
현규님! 리뷰해주신 것 중 좋은 부분 많이 참고하여 수정했습니다.
감사합니다 ㅎㅎ

2020-09-10 15:13 UTC, OMEGA-Y commented
수정했습니다!

2020-09-12 08:00 UTC, merged