[번역] Part1 변수와 상수 warn 부분
javascript-tutorial/ko.javascript.info pull request #818
Opened 2020-08-31 13:20 UTC by kyujonglee

# Pull Request 체크리스트
## TODO
- [x] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [x] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [x] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [x] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [x] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [x] PR 하나엔 번역문 하나만 넣으셨나요?
- [x] 의미 있는 커밋 메시지를 작성하셨나요?

2020-08-31 13:46 UTC, Violet-Bora-Lee requested changes
몇가지 suggestion 남겨보았습니다.

2020-08-31 13:46 UTC, Violet-Bora-Lee commented on 1-js/02-first-steps/04-variables/article.md
> +변수를 한 번만 선언해야 합니다.
```suggestion
변수는 한 번만 선언해야 합니다.
```

2020-08-31 13:46 UTC, Violet-Bora-Lee commented on 1-js/02-first-steps/04-variables/article.md
> +같은 변수를 반복적으로 선언하면 에러가 발생합니다.
```suggestion
같은 변수를 여러 번 선언하면 에러가 발생합니다.
```
이글 한번 읽어봐주세요.
https://m.blog.naver.com/PostView.nhn?blogId=ojhnews&logNo=220840570533

2020-08-31 13:46 UTC, Violet-Bora-Lee commented on 1-js/02-first-steps/04-variables/article.md
> +let message = "That"; // SyntaxError: 'message'는 이미 선언되었습니다.
에러메시지는 번역하지 말아주세요

2020-08-31 13:46 UTC, Violet-Bora-Lee commented on 1-js/02-first-steps/04-variables/article.md
> +따라서 변수를 한번 선언하고 나면 `let` 없이 해당 변수를 참조해야 합니다.
```suggestion
따라서 변수는 딱 한번만 선언하고, 선언한 변수를 참조할 때는 `let` 없이 변수명만 사용해 참조해야 합니다.
```

2020-08-31 14:20 UTC, Violet-Bora-Lee commented on 1-js/02-first-steps/04-variables/article.md
> +따라서 변수는 딱 한번만 선언하고, 선언한 변수를 참조할 때는 `let` 없이 변수명만 사용해 참조해야 합니다.
여기 맞춤법 검사기 돌려주세요 ㅎㅎ

2020-08-31 14:28 UTC, kyujonglee commented on 1-js/02-first-steps/04-variables/article.md
> +따라서 변수는 딱 한번만 선언하고, 선언한 변수를 참조할 때는 `let` 없이 변수명만 사용해 참조해야 합니다.
아ㅎㅎㅎ 리뷰 반영하고 돌리는 걸 깜박했네요😭

2020-09-05 08:52 UTC, kyujonglee commented
/done

2020-09-06 09:48 UTC, Violet-Bora-Lee commented
커밋 하나로 합쳐주시면 바로 머지하겠습니다.

2020-09-06 11:40 UTC, kyujonglee commented
/done 커밋합쳤습니다.

2020-09-06 13:00 UTC, Violet-Bora-Lee commented
감사합니다.
머지 진행할게요 👍

2020-09-06 13:01 UTC, merged