[CSS animation] A Bezier curve can make ~ 문단 번역
javascript-tutorial/ko.javascript.info pull request #821
Opened 2020-09-01 10:30 UTC by dazzel3

# Pull Request 체크리스트
## TODO
- [X] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [X] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [X] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [X] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [X] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [X] PR 하나엔 번역문 하나만 넣으셨나요?
- [X] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

2020-09-06 13:23 UTC, Violet-Bora-Lee requested changes
문장만 조금 더 다듬어주시면 될것같아요~

2020-09-06 13:23 UTC, Violet-Bora-Lee commented on 7-animation/2-css-animations/article.md
> +베지어 곡선에서 제어점의 `y` 좌표는 음수 또는 큰 값까지 가질 수 있습니다. 그러면 베지어 곡선도 매우 낮거나 높게 형성되어, 애니메이션이 정상 범위를 벗어나게 됩니다.
'그러면'이 나타내는 상황이 무엇인가요?
y좌표가 음수일때인가요 아니면 무한대의 값을 가질때인가요?
then이 어떤 상황을 나타내는지 풀어주세요.

https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EB%8C%80%EB%AA%85%EC%82%AC%EB%8A%94-%EB%AA%85%ED%99%95%ED%95%98%EA%B2%8C

모범사례 확인해주세요.

'형성되다'라는 동사와 '곡선'이 어울리는지 잘 모르겠어요. 조금만 더 리서치 해주셔서 베지어 곡선을 다룬 다른 글들에선 베지어 곡선의 높이를 묘사할 때 어떤 동사를 쓰고있는지 알아봐주실수 있을까요?

2020-09-06 13:23 UTC, Violet-Bora-Lee commented on 7-animation/2-css-animations/article.md
> +하지만 기차를 클릭하면 다음과 같은 것을 알 수 있습니다.
http://m.blog.naver.com/ojhnews/220840570533

'것'을 빼도 문장을 만들수 있을것같습니다.

2020-09-06 13:23 UTC, Violet-Bora-Lee commented on 7-animation/2-css-animations/article.md
> +확실히 '부드러운' 변형이죠. `y` 값으로 `-99`나 `99`를 넣으면 기차가 훨씬 더 멀리 뛰어오를 것입니다.
'것'을 뺄수있을것같아요

2020-09-07 04:44 UTC, dazzel3 commented
/done

리뷰참고해서 수정했습니다.

2020-09-10 14:39 UTC, closed without merging