[번역]Part2 1.11 Coordinates
javascript-tutorial/ko.javascript.info pull request #829
Opened 2020-09-02 12:33 UTC by kbpark

[번역]Part2 1.11 Coordinates

# Pull Request 체크리스트
## TODO
- [ ] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [ ] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [ ] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [ ] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [ ] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [ ] PR 하나엔 번역문 하나만 넣으셨나요?
- [ ] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

2020-09-19 08:41 UTC, Violet-Bora-Lee requested changes
코멘트에 있는 댓글들을 참고하여 퇴고 부탁드립니다.
아래쪽에도 유사한 실수가 반복되어서 위쪽만 먼저 리뷰하였습니다.

2020-09-19 08:41 UTC, Violet-Bora-Lee commented on 2-ui/1-document/11-coordinates/article.md
> +대부분의 JavaScript 메서드는 다음 두 좌표 체계 중 하나를 이용합니다.
```suggestion
대부분의 자바스크립트 메서드는 다음 두 좌표 체계 중 하나를 이용합니다.
```

2020-09-19 08:41 UTC, Violet-Bora-Lee commented on 2-ui/1-document/11-coordinates/article.md
> +    - 앞으로는 이 좌표를 `clientX/clientY`로 표시하며, 왜 이런 이름을 쓰는지는 나중에 event 프로퍼티를 공부할 때 명확히 알 수 있을 것입니다.
http://m.blog.naver.com/ojhnews/220840570533

이 글 한번 읽어보시고, 문장 개선 부탁드립니다

2020-09-19 08:41 UTC, Violet-Bora-Lee commented on 2-ui/1-document/11-coordinates/article.md
> +페이지를 스크롤 하려고 할 때, 맨 처음에는 window 상단/왼쪽 모서리가 document 상단/왼쪽 모서리와 정확히 일치합니다. 그 이후 document가 움직이면서 요소의 window 기준 좌표는 바뀌지만, document 기준 좌표는 그대로입니다.
```suggestion
스크롤을 움직이기 바로 전에는 window 상단/왼쪽 모서리가 document 상단/왼쪽 모서리와 정확히 일치합니다. 그런데 스크롤이 움직이기 시작하면 document가 움직이기 때문에 document 기준 좌표는 그대로이지만 요소의 window 기준 좌표는 바뀝니다.
```

2020-09-19 08:41 UTC, Violet-Bora-Lee commented on 2-ui/1-document/11-coordinates/article.md
> +1. window 기준 -- `elem.getBoundingClientRect()`.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EB%AC%B8%EC%9E%A5%EC%9D%B4-%EB%AA%85%EC%82%AC%ED%98%95%EC%9C%BC%EB%A1%9C-%EB%81%9D%EB%82%A0-%EB%95%8C%EB%8A%94-%EB%A7%88%EC%B9%A8%ED%91%9C%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4

모범사례 확인부탁드립니다

2020-09-19 08:41 UTC, Violet-Bora-Lee commented on 2-ui/1-document/11-coordinates/article.md
>  ## Element coordinates: getBoundingClientRect
번역 누락

2020-09-19 08:41 UTC, Violet-Bora-Lee commented on 2-ui/1-document/11-coordinates/article.md
> +`elem.getBoundingClientRect()` 메서드는 `elem`을 감쌀 수 있는 가장 작은 네모영역의 window 기준 좌표를 [DOMRect](https://www.w3.org/TR/geometry-1/#domrect) 클래스의 객체로 리턴합니다.
리턴도 번역해주세요

2020-09-19 08:41 UTC, Violet-Bora-Lee commented on 2-ui/1-document/11-coordinates/article.md
> +- `width/height` -- 네모영역의 너비/높이(음수 가능).
```suggestion
- `x/y` -- 네모영역의 window 기준 X/Y 좌표
- `width/height` -- 네모영역의 너비/높이(음수 가능)
```

https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EB%AC%B8%EC%9E%A5%EC%9D%B4-%EB%AA%85%EC%82%AC%ED%98%95%EC%9C%BC%EB%A1%9C-%EB%81%9D%EB%82%A0-%EB%95%8C%EB%8A%94-%EB%A7%88%EC%B9%A8%ED%91%9C%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4

2020-09-19 08:41 UTC, Violet-Bora-Lee commented on 2-ui/1-document/11-coordinates/article.md
> +또한, 여기에서 파생된 프로퍼티도 있습니다.
```suggestion
`x/y`, `width/height` 말고 다음과 같은 프로퍼티도 있습니다.
```

2020-09-19 08:41 UTC, Violet-Bora-Lee commented on 2-ui/1-document/11-coordinates/article.md
> +```warn header="Internet Explorer: `x/y` 미지원"
```suggestion
```warn header="Internet Explorer는 `x/y`를 지원하지 않습니다."
```

2020-09-19 08:41 UTC, Violet-Bora-Lee commented on 2-ui/1-document/11-coordinates/article.md
> +그래서 폴리필을 만들거나(`DomRect.prototype`에 getter 추가), `elem.getBoundingClientRect()` 결괏값에서는 `width/height`가 양수여서 `x/y`와 동일하기 때문에 그냥 `top/left`을 이용합니다.
```suggestion
그래서 `DomRect.prototype`에 getter를 추가해 폴리필을 만들거나 `elem.getBoundingClientRect()`를 호출하면 그 결괏값의 `width/height`가 양수라는 특징을 이용해 `x/y`대신 `top/left`을 이용합니다.
```

2020-09-19 08:41 UTC, Violet-Bora-Lee commented on 2-ui/1-document/11-coordinates/article.md
> +```warn header="right/bottom 좌표는 CSS position 프로퍼티와는 다릅니다"
```suggestion
```warn header="right/bottom 좌표는 CSS position 프로퍼티와는 다릅니다."
```

2020-09-19 08:41 UTC, Violet-Bora-Lee commented on 2-ui/1-document/11-coordinates/article.md
> +그러나 CSS position에서는, `right` 프로퍼티는 오른쪽 모서리로부터의 거리, `bottom` 프로퍼티는 하단 모서리로부터의 거리를 의미합니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%89%BC%ED%91%9C%EB%A5%BC-%EB%AA%A8%EB%91%90-%EC%98%AE%EA%B8%B8-%ED%95%84%EC%9A%94%EB%8A%94-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4

2020-09-19 08:41 UTC, Violet-Bora-Lee commented on 2-ui/1-document/11-coordinates/article.md
> +````warn header="window 밖으로 나간 좌표에서 `elementFromPoint`는 `null`을 리턴합니다"
```suggestion
````warn header="window 밖으로 나간 좌표에서 `elementFromPoint`는 `null`을 리턴합니다."
```

2020-09-19 18:40 UTC, kbpark commented
/done 

수정하였습니다.

2021-01-04 15:56 UTC, Violet-Bora-Lee commented
머지 진행하겠습니다.
리뷰 및 진행이 늦어져서 죄송합니다...

감사합니다 👍

2021-01-04 15:56 UTC, merged

2021-01-04 15:56 UTC, Violet-Bora-Lee commented
이슈와 대시보드 업데이트 부탁드릴게요