#713 [신규 번역] 파트2 - 3.3 드래그&드롭과 마우스이벤트 원문 번역
javascript-tutorial/ko.javascript.info pull request #833
Opened 2020-09-06 09:46 UTC by KimHunJin

# Pull Request 체크리스트
## TODO
- [x] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [x] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [x] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [x] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [x] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [x] PR 하나엔 번역문 하나만 넣으셨나요?
- [x] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

2020-09-06 09:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ko.javascript.info?pullRequest=833) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ko.javascript.info?pullRequest=833) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ko.javascript.info?pullRequest=833) it.</sub>

2020-09-10 11:08 UTC, Violet-Bora-Lee requested changes
http://m.blog.naver.com/ojhnews/220840570533

읽어보시고 퇴고 여러번 부탁드립니다.

2020-09-10 11:08 UTC, Violet-Bora-Lee commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +1. `mousedown`에서는 필요하다면 움직일 요소를 준비합니다. (복사본을 만들거나, 클래스를 추가하는 등 무엇이든 할 수 있습니다.)
```suggestion
1. `mousedown`에서는 움직임이 필요한 요소를 준비합니다. 이때 기존 요소의 복사본을 만들거나, 해당 요소에 클래스를 추가하는 등 원하는 형태로 작업할 수 있습니다.
```

https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EA%B4%84%ED%98%B8-%EC%95%88%EC%9D%98-%EB%AC%B8%EC%9E%A5

참고하여 띄워쓰기 수정부탁드립니다.

2020-09-10 11:08 UTC, Violet-Bora-Lee commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +2. 이후 `mousemove`에서 `position:absolute`의 `left/top`을 변경합니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%A7%9D%EC%9D%84-%EC%9D%B4%EB%A3%A8%EB%8A%94-%EB%8B%A8%EC%96%B4%EB%A5%BC-%EC%9D%B4%EC%9D%84-%EB%95%8C%EB%8A%94-%EA%B0%80%EC%9A%B4%EB%8E%83%EC%A0%90-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

모범사례 확인해주세요

2020-09-10 11:08 UTC, Violet-Bora-Lee commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +3. `mouseup`에서는 드래그&드롭의 완료와 관련된 모든 작업을 수행합니다.
'의'가 꼭 필요한건지 확인해주세요

드래그 앤 드롭의 완료와 관련된 모든 작업 <-- 이게 잘 이해가 안되네요

2020-09-10 11:08 UTC, Violet-Bora-Lee commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +여기까지가 기본입니다. 이후에는 이동 중인 요소 아래에 있는 다른 요소를 강조하는 기능 같은 것을 알아보겠습니다.
'것' 수정

2020-09-10 11:08 UTC, Violet-Bora-Lee commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +  // (1) absolute속성과 z-index속성으로 공이 제일 위에서 움직이기 위한 준비를 합니다.
```suggestion
  // (1) absolute와 zIndex 프로퍼티를 수정해 공을 움직이기 위한 준비를 합니다.
```

property이므로, 용어집을 참고해 '속성'이 아닌 '프로퍼티'로 번역해주세요

https://developer.mozilla.org/en-US/docs/Web/CSS/position

2020-09-10 11:08 UTC, Violet-Bora-Lee commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +  // 현재 부모에서 body로 직업 이동합니다.
퇴고 부탁드립니다

2020-09-10 11:08 UTC, Violet-Bora-Lee commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +코드를 실행시켜보면 무언가 이상한 점이 보일 겁니다. 드래그&드롭을 시작할 때 공이 포크 되고 복사된 공을 끌기 시작합니다.
포크도 번역해주세요

2020-09-10 11:08 UTC, Violet-Bora-Lee commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +이제 잘 될 것입니다.
'것' 퇴고

2020-09-11 11:00 UTC, KimHunJin commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +# 드래그&드롭과 마우스 이벤트
드래그 앤 드롭으로 변경하겠습니다.

2020-09-11 11:07 UTC, KimHunJin commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +드래그&드롭은 사용자와 컴퓨터 간 상호작용을 도와주는 훌륭한 방법입니다. 무언가를 끌어다가 놓는 것은 파일 매니저에서 문서를 복사 혹은 이동하는 것부터 장바구니에 물품을 담는 것까지 많은 것을 수행할 수 있는 단순하고, 명백한 방법입니다.
번역을 진행하면서 드래깅과 드롭핑에 대해서 어떻게 표현하는게 좋을 지 고민했는데, 참고하기 좋은 글이 될거 같아요 :)
다시 한번 전체적으로 검토하면서 변경하겠습니다. 감사합니다~

2020-09-11 11:31 UTC, KimHunJin commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +  // 현재 부모에서 body로 직업 이동합니다.
이 부분 혹시 도움을 받을 수 있을까요?
직업은 오타였는데 맞춤법이 틀린게 아니라서 발견을 못했네요... ㅋㅋ

직접으로 수정을 하더라도 문장이 너무 어색한데.. 어떻게 표현을 해야할까요..

2020-09-11 22:07 UTC, KimHunJin commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +코드를 실행시켜보면 무언가 이상한 점이 보일 겁니다. 드래그&드롭을 시작할 때 공이 포크 되고 복사된 공을 끌기 시작합니다.
포크되다 라는 걸 찍어 올리다 정도로 해석했는데 확인 부탁드립니다.

```
코드를 실행시켜보면 무언가 이상한 점이 보일 겁니다. 드래그 앤 드롭을 시작할 때 공을 찍어 올리고, 복사된 공을 끌기 시작합니다.
```

2020-09-11 22:08 UTC, KimHunJin commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +이제 잘 될 것입니다.
완료

```
이제 잘 됩니다.
```

2020-09-11 22:08 UTC, KimHunJin commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +  // (1) absolute속성과 z-index속성으로 공이 제일 위에서 움직이기 위한 준비를 합니다.
완료

```
absolute와 zIndex 프로퍼티를 수정해 공을 움직이기 위한 준비를 합니다.
```

2020-09-11 22:09 UTC, KimHunJin commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +여기까지가 기본입니다. 이후에는 이동 중인 요소 아래에 있는 다른 요소를 강조하는 기능 같은 것을 알아보겠습니다.
완료
```
여기까지가 기본 알고리즘입니다. 이후에는 이동 중인 요소 아래에 있는 다른 요소를 강조하는 기능을 알아보겠습니다.
```

2020-09-11 22:09 UTC, KimHunJin commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +여기에서는 마우스 이벤트를 사용하여 드래그&드롭을 구현하는 방법을 알아보겠습니다.
완료

```
여기에서는 마우스 이벤트를 사용하여 드래그&드롭을 구현하는 방법을 알아보겠습니다.
```

2020-09-11 22:10 UTC, KimHunJin commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +이 이벤트들은 OS의 파일 매니저로부터 파일을 끌고 와 브라우저 화면에 놓는 특별한 드래그&드롭을 제공합니다. 그러면 자바스크립트는 이 파일의 내용을 다룰 수 있습니다.
변경 완료
```
`dragstart`나 `dragend` 이벤트는 운영체제의 파일 관리 애플리케이션으로부터 파일을 드래그하여 브라우저 화면에 드롭하는 특별한 드래그 앤 드롭 기능을 제공합니다. 그러면 자바스크립트로 파일 관리 애플리케이션에서 드래그하여 가져온 파일의 내용을 다룰 수 있습니다.
```

2020-09-11 22:10 UTC, KimHunJin commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +현대 HTML 표준에서는 `dragstart`, `dragend` 등의 특수한 이벤트와 함께 드래그&드롭에 대한 절이 있습니다.
완료 및 누락된 내용 추가

```
모던 HTML 표준에서는 `dragstart`, `dragend` 등의 특수한 이벤트와 함께 [드래그 앤 드롭](https://html.spec.whatwg.org/multipage/interaction.html#dnd)에 대한 절이 있습니다.
```

2020-09-12 02:09 UTC, KimHunJin commented
/done

2021-01-09 11:57 UTC, Violet-Bora-Lee commented
안녕하세요. 오래된 PR이라 일단 머지후 보완이 필요한 부분은 재 리뷰하려고했는데,
충돌이 발생하여 작업이 불가능합니다.
충돌 해결을 부탁드릴게요

2021-01-11 15:40 UTC, KimHunJin commented
충돌 처리를 진행하다보니 리베이스 과정에서 다른 기여자분들의 커밋이 추가되어,
리뷰가 사실상 불가능하다고 판단 돼 close 후 다시 PR 올리도록 하겠습니다. 😢

2021-01-11 15:40 UTC, closed without merging