[CSS Animation] trans-timing-function 부터 끝까지 번역
javascript-tutorial/ko.javascript.info pull request #855
Opened 2020-09-10 14:38 UTC by dazzel3

# Pull Request 체크리스트
## TODO
- [X] [번역 규칙을 확인하셨나요?](https://github.com/javascript-tutorial/ko.javascript.info#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
  - [X] 줄 바꿈과 단락을 '원문과 동일하게' 유지하셨나요?
  - [X] [맞춤법 검사기](http://speller.cs.pusan.ac.kr/)로 맞춤법을 확인하셨나요?
  - [X] 마크다운 문법에 사용되는 공백(스페이스), 큰따옴표("), 작은따옴표('), 대시(-), 백틱(`) 등의 특수문자는 그대로 두셨나요?
- [X] [로컬 서버 세팅](https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%A1%9C%EC%BB%AC-%EC%84%9C%EB%B2%84-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0) 후 최종 결과물을 확인해 보셨나요?
- [X] PR 하나엔 번역문 하나만 넣으셨나요?
- [X] 의미 있는 커밋 메시지를 작성하셨나요?
  - 예시
    - [프락시] 번역
    - [프락시] 과제 번역
    - [if문과 조건부 연산자 '?'] 리뷰
    - [주석] 2차 리뷰
    - [Date 객체와 날짜] 번역

2020-09-12 03:53 UTC, Violet-Bora-Lee requested changes
직역이 많아서, 제가 독자라면 이해할 수 없을것같은 문장이 많습니다.

초등학생이나 중학생이 읽는다고 가정하고 쉽게 풀어써주세요.

2020-09-12 03:53 UTC, Violet-Bora-Lee commented on 7-animation/2-css-animations/article.md
> +함수 Timing에서는 애니메이션 프로세스가 시간에 따라 어떻게 분배되는지를 설정합니다. 애니메이션 프로세스가 천천히 시작하다가 빠르게 진행되거나 반대로 진행될 것입니다.
```suggestion
timing 함수를 사용하면 시간에 따라 애니메이션 효과를 어떻게 분배 할지를 설정할 수 있습니다. 애니메이션 효과가 초반엔 천천히 나타나다가 나중엔 빠르게 나타나도록 할 수 있고, 물론 이 반대로도 설정할 수 있죠.
```

2020-09-12 03:53 UTC, Violet-Bora-Lee commented on 7-animation/2-css-animations/article.md
> +처음 보면 복잡한 프로퍼티로 느껴질 수 있습니다. 하지만 시간을 조금만 투자하면 매우 간단해집니다.
```suggestion
`transition-timing-function`을 처음 접했다면 가장 복잡한 프로퍼티라고 느껴질 수 있습니다. 그렇지만 시간을 조금 투자해 학습하면 매우 간단한 프로퍼티라는 것을 알 수 있죠.
```

2020-09-12 03:53 UTC, Violet-Bora-Lee commented on 7-animation/2-css-animations/article.md
> +이 프로퍼티의 값으로는 베지어 곡선(Bezier curve)과 단계(Steps) 값이 가능합니다. 조금 더 자주 쓰이는 베지어 곡선부터 알아봅시다.
대명사는 항상 풀어써주세요(모범사례 확인하기)

```suggestion
`transition-timing-function` 프로퍼티 값엔 베지어 곡선(bezier curve)이나 단계(step)가 올 수 있습니다. 먼저 사용 빈도가 높은 베지어 곡선부터 알아봅시다.
```

2020-09-12 03:53 UTC, Violet-Bora-Lee commented on 7-animation/2-css-animations/article.md
> +### 베지어 곡선(Bezier curve)
```suggestion
### 베지어 곡선
```

2020-09-12 03:53 UTC, Violet-Bora-Lee commented on 7-animation/2-css-animations/article.md
> +함수 Timing에서는 아래의 조건을 만족하는 4개의 제어점을 가진 [베지어 곡선](/bezier-curve)을 설정할 수 있습니다.
```suggestion
timing 함수에는 아래 조건을 만족하는 4개의 제어점을 가진 [베지어 곡선](/bezier-curve)을 설정할 수 있습니다.
```

2020-09-12 03:53 UTC, Violet-Bora-Lee commented on 7-animation/2-css-animations/article.md
> +3. 중간 제어점들의 `x`값은 `0..1`구간이어야 하며, `y`값은 어떤 값이든 가능합니다.
```suggestion
3. 중간 제어점들의 `x`값은 `0`과 `1`사이에 있어야 합니다. 반면 `y`값엔 제약이 없습니다.
```

2020-09-12 03:53 UTC, Violet-Bora-Lee commented on 7-animation/2-css-animations/article.md
> +CSS의 베지어 곡선 문법은 `cubic-bezier(x2, y2, x3, y3)`입니다. 여기서 첫 번째 제어점은 `(0,0)`으로, 네 번째 제어점은 `(1,1)`로 고정되어 있으므로 두 번째와 세 번째 제어점만 설정하면 됩니다.
```suggestion
CSS에선 베지어 곡선을 `cubic-bezier(x2, y2, x3, y3)`형태로 정의합니다. 규칙에 따라 첫 번째 제어점은 `(0,0)`, 네 번째 제어점은 `(1,1)`로 고정되므로 우리는 두 번째와 세 번째 제어점만 설정하면 됩니다.
```

2020-09-12 03:53 UTC, Violet-Bora-Lee commented on 7-animation/2-css-animations/article.md
> +함수 Timing을 통해 애니메이션 프로세스가 시간 내에 얼마나 빨리 진행되는지 설정할 수 있습니다.
```suggestion
timing 함수엔 시간이 지남에 따라 얼마나 빠르게 애니메이션 효과가 나타나게 할 지를 설정합니다.
```

2020-09-12 03:53 UTC, Violet-Bora-Lee commented on 7-animation/2-css-animations/article.md
> +- `x`축은 시간을 의미합니다. `0`은 `transition-duration`의 시작하는 시간을, `1`은 끝나는 시간을 나타내죠.
```suggestion
- `x`축엔 시간을 설정합니다. `0`은 `transition-duration`에서 시작하는 시간, `1`은 끝나는 시간을 나타냅니다.
```

2020-09-12 03:53 UTC, Violet-Bora-Lee commented on 7-animation/2-css-animations/article.md
> +- `y`축은 프로세스의 완성을 명시합니다. `0`은 프로퍼티의 시작 상태를, `1`은 최종 상태를 나타내죠.
```suggestion
- `y`축엔 프로세스 완성 정도를 설정합니다. `0`은 프로퍼티 시작 값을, `1`은 최종 값을 나타냅니다.
```

2020-09-12 03:53 UTC, Violet-Bora-Lee commented on 7-animation/2-css-animations/article.md
> +가장 간단한 변형은 애니메이션이 같은 선형 속도로 균일하게 진행되는 경우입니다. `cubic-bezier(0, 0, 1, 1)`로 설정할 수 있습니다.
가장 간단한 변형은 애니메이션이 같은 선형 속도로 균일하게 진행되는 경우입니다. <-- 이 말이 잘 이해가 안갑니다. 어떤 걸 변형했는지, 선형 속도는 무엇인지 설명해주세요.

2020-09-12 03:53 UTC, Violet-Bora-Lee commented on 7-animation/2-css-animations/article.md
> +보시다시피, 그냥 직선입니다. 시간(`x`)이 지나면서, 애니메이션의 완성도(`y`)가 `0`에서 `1`로 꾸준히 올라갑니다.
https://github.com/javascript-tutorial/ko.javascript.info/wiki/%EB%B2%88%EC%97%AD-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80#%EC%89%BC%ED%91%9C%EB%A5%BC-%EB%AA%A8%EB%91%90-%EC%98%AE%EA%B8%B8-%ED%95%84%EC%9A%94%EB%8A%94-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4

불필요한 쉼표를 전반적으로 빼주세요

2020-09-12 03:53 UTC, Violet-Bora-Lee commented on 7-animation/2-css-animations/article.md
> +### 단계(Steps)
제목은 목차역할을 하므로 한-영 병기하지 않습니다

2020-09-13 14:01 UTC, dazzel3 commented
/done

@Violet-Bora-Lee 리뷰감사합니다. 수정했습니다.

2021-01-09 11:58 UTC, Violet-Bora-Lee commented
안녕하세요. 리뷰 핑퐁이 늦음에도 불구하고 오랫동안 작업 꾸준히 참여해주심에 감사드립니다.
머지 진행하도록 하겠습니다. 감사합니다!

2021-01-09 11:58 UTC, merged